### ISSUE TITLE
Aglomerados (clusters) não funcionam em tablets

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#101]
Na versão disponibilizada pelo designer este item funciona corretamente, na primeira versão entregue não temos o mesmo comportamento.

Links para comparação: http://homolog.search.scielo.org/, http://scielohomolog.parati.ag/iAHx/index.html

**Comment by deandr** [comment]
Aparentemente o ambiente de homologação não esta atualizado com a última versão do branch beta.  Pois o commit https://github.com/scieloorg/search-journals/commit/12c0447999867ada2192252e4ad70c56f09a42ab remove o botão de filtrar da interface e deve com isso ter efeito sobre o uso no tablet. 

Favor atualizar o ambiente e realizar novo teste para verificar se o problema ainda ocorre.

[]

**Comment by jamilatta** [comment]
:+1:

**Comment by jamilatta** [comment]
Preciso verificar isso em um tablet, para garantir que o teste.

**Comment by jamilatta** [comment]
O collapse dos cluster continuam não funcionando tanto no tablet quanto no navegador.

**Comment by jamilatta** [comment]
O collapse continua não funcionando, após a aprovação do PR.

**Comment by deandr** [comment]
Sim realmente só ficou claro que o problema era no collapse no comentário do issue (https://github.com/scieloorg/search-journals/issues/101#issuecomment-103627089) pois pelo título do ticket o problema reportado era na funcionalidade do cluster. 

No PR não aprovado já esta contemplado o ajuste deste item.

**Comment by jamilatta** [comment]
Hm... isso é um pegadinha, rsrs.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em tablets.
