### ISSUE TITLE
Alterar o formato de importação do processamento

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#105]
Com a última refatoração temos um pipeline que converte um JSON em XML, porém o Solr a partir da versão 3.1 aceita como entrada o formato JSON, ver: https://wiki.apache.org/solr/UpdateJSONrelease.

Aproveitando que o JSON é um formato menos verbose e mais performático e atualmente mais aderente a novas tecnologias é importante termos os dois tipos de formato de saída no processamento do sistema de busca.

Interessante seria termos um para ``-e`` em que as opções seriam ``XML`` ou ``JSON``.

**Comment by fabiobatalha** [comment]
@jamilatta 
Você acha mesmo que é interessante ter os 2 formatos? O XML atende as necessidades. O uso desse XML é apenas interno e apenas para carga de registros no Lucene.

Ter 2 formatos significa dar manutenção nos 2 formatos.

**Comment by jamilatta** [comment]
Sim, dar manutenção em dois formato é ruim :-), mas acho JSON mais interessante, podemos manter somente o JSON evitaria bastante coisa no processamento como o custo do ``json.loads`` e estaríamos mais aderentes a outros indexadores.

**Comment by fabiobatalha** [comment]
@jamilatta 

Não vejo o json.loads como um grande problema, mesmo porque você ainda terá que gerar o objeto Xylose para produzir um json adequado sem ter que passar o json original do articlemeta para o lucene.

Para mim isso é só retrabalho.

**Comment by jamilatta** [comment]
@fabiobatalha 

concordo que não podemos nos dar o luxo de re-trabalhos nesse momento.
