### ISSUE TITLE
Adicionando algumas informações não disponíveis no formato importação do sistema de pesquisa

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#107]
Existe algumas dados que não temos no formato de exportação para o sistema de pesquisa, ver: 

![screen shot 2015-05-12 at 11 39 05](https://cloud.githubusercontent.com/assets/373745/7589862/b42f2c34-f89b-11e4-9231-b41fcb84258f.png)

* Volume 
* Número
* Paginação e etc...

**Comment by jamilatta** [comment]
Para que possamos testar os itens citados, adicionei ainda no formato XML estes itens, como iremos mudar para JSON não me preocupei em gerar teste para os itens adicionados.

**Comment by fabiobatalha** [comment]
@jamilatta 

Não acho que devemos mudar para JSON. Pelo menos por hora isso não é necessário.

Na verdade os testes devem sempre existir se considerarmos que trabalhamos com TDD.

**Comment by jamilatta** [comment]
OK, vou realizar os ajustes.
