### ISSUE TITLE
Capacidade de busca pelo DOI

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#111]
Atualmente o sistema de pesquisa da SciELO não permite utilizar o DOI para retornar um artigo considerando que o DOI é um código para encontrar artigos podemos utiliza-lo com mais um recurso na pesquisa.

**Comment by fabiobatalha** [comment]
Acredito que sim.

Podemos incluir esse campo no XML.

**Comment by alexxxmendonca** [comment]
Atualmente, o PID está sendo indexado como texto. Devemos mudar isso para string, para garantir que a busca (match) seja exata.

**Comment by deandr** [comment]
@alexxxmendonca 

Acredito que este ticket já esteja OK. Realizei a busca pelo DOI e pelo PID de um artigo e o mesmo foi recuperado corretamente. 

Exemplo:

http://search.scielo.org/?q=S1806-11172017000100401

http://search.scielo.org/?q=10.1590/1806-9126-RBEF-2016-0155

**Comment by alexxxmendonca** [comment]
De fato parece estar OK.

Vou fechar.
