### ISSUE TITLE
Alterar a chave ``abrev_source`` para ``journal_title``

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#116]
Pensando em termos mais semântica... realizei algumas alterações no arquivo schema.xml para garantir que possamos identificar mais facilmente os termos(**chaves**). 

Agora avaliando a interface com mais calma identifico que o título não é abreviado e sim o título completo o que justifica mais ainda essa alteração.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
