### ISSUE TITLE
Diferença de apresentação em filtro por coleção.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/search-journals#119]
Quando o filtro vem do formulário de pesquisa, através do radio button, o filtro é apresentado da forma abaixo:

![screen shot 2015-05-26 at 4 23 55 pm](https://cloud.githubusercontent.com/assets/504142/7821224/ab76b214-03c3-11e5-9e87-b4bc032c132a.png)

Acredito que deveria ser da mesma forma como quando uma coleção é selecionada através dos clusters:

![screen shot 2015-05-26 at 4 24 08 pm](https://cloud.githubusercontent.com/assets/504142/7821237/be6c02f2-03c3-11e5-9d67-bacbfce38aa3.png)

Evitando aparecer as duas formas como esta aparecendo hoje:

![screen shot 2015-05-26 at 4 22 37 pm](https://cloud.githubusercontent.com/assets/504142/7821207/8d78d9c2-03c3-11e5-9604-f88c5108ea2e.png)

**Comment by alexxxmendonca** [comment]
Foi solicitado por SciELO que o primeiro filtro mostrasse a lógica booleana por trás do critério de busca, semelhante a como aparece no Web of Science.

**Comment by fabiobatalha** [comment]
Sinceramente a interface de busca do WoS é muito ruim.

**Comment by fabiobatalha** [comment]
Parece que foi resolvido, mantendo a expressão e aparecendo o filtro de forma que o usuário possa excluí-lo se assim quiser.
