### ISSUE TITLE
Título do artigo

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#120]
O título do artigo está aparecendo em 3 idiomas.

Mostrar apenas 1 título, correspondente à interface. Caso não haja tradução correspondente à interface, mostrar o título do idioma principal do artigo.

**Comment by scielo** [comment]
Alex,

Acho que esse tipo de regra é complicado de se estabelecer, mesmo porque em
muitos casos os títulos não serão associados ao idioma da interface devido
a falta de versão traduzida.

Isso cria uma falsa impressão ao usuário de que o idioma da interface
também esta alinhado ao idioma do conteúdo.

A sugestão seria apresentar no idioma original ou deixar como esta.

*Fabio Batalha C. Santos*
Colegiado SciELO
www.scielo.org
FAPESP - CNPq - BIREME - FapUNIFESP

2015-05-26 16:25 GMT-03:00 alexxxmendonca <notifications@github.com>:

**Comment by alexxxmendonca** [comment]
De acordo com mostrar o idioma principal.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
