### ISSUE TITLE
Busca deve funcionar ao digitar "enter" no campo

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#121]
A busca deve ser executada ao digitar o botão "enter" do teclado.

Atualmente, ao apertar "enter", o campo quebra uma linha, permitindo isso:

![image](https://cloud.githubusercontent.com/assets/4059679/7821348/7e34990a-03c4-11e5-9c29-b903a72c6bee.png)

**Comment by deandr** [comment]
@alexxxmendonca,

Também achei estranho o comportamento mas é como esta implementado no protótipo, inclusive o comportamento de aumentar a caixa da busca para se transformar em um textarea não é padrão do HTML e foi implementado de propósito. 

Portanto deverá ser verificado com o designer o que motivou e caso seja solicitado a alteração do comportamento é necessário que ele passe os ajustes necessários na interface que devemos aplicar.

http://scielohomolog.parati.ag/iAHx/index.html

[]s

**Comment by alexxxmendonca** [comment]
Conversei com o designer e ele informou que fará alguns ajustes no campo de busca. Ele acha que não deverá interferir no trabalho de vocês.

**Comment by alexxxmendonca** [comment]
Testado em http://homolog.search.scielo.org/

Não sei se o comportamento atual é o ideal. Após pressionar o botão "enter" do teclado, o cursor vai para a linha de baixo e executa a busca em seguida. Particularmente, acho esse comportamento estranho, mas o designer disse que iria fazer alguns ajustes nessa ferramenta e talvez o resultado seja melhor.

Talvez devêssemos discutir melhor o seu comportamento.

O que fazer com esse ticket? Fechar por ora?

**Comment by deandr** [comment]
@alexxxmendonca 

Acredito que sim, pois o recurso foi implementado. Caso o designer consiga uma solução melhor é só realizar o re-open que eu implemento.

[]s

**Comment by alexxxmendonca** [comment]
Ok.
