### ISSUE TITLE
Comportamento quando expressão de pesquisa é vazia

### ISSUE THREAD

**Issue by deandr** [scieloorg/search-journals#122]
Qual seria o comportamento desejado na interface quando o usuário não informa nenhuma expressão de pesquisa no formulário da página inicial?

1. Retornar toda a coleção (busca por ```*:*```)
2. Recarregar a página inicial para que o usuário informe uma expressão de busca.
3. Outro?

**Comment by alexxxmendonca** [comment]
O comportamento deve ser: executar a busca com o filtro "Publication - Newest first".

**Comment by deandr** [comment]
:+1:

**Comment by alexxxmendonca** [comment]
Testado em http://homolog.search.scielo.org/:

O primeiro resultado que aparece é um artigo de 2011. É isso mesmo? Esse foi o último incluído na base?

**Comment by deandr** [comment]
Não. Na verdade a implementação da pesquisa vazia acaba incluindo o filtro de coleção (in:"scl") e  portanto a busca nunca é realmente vazia uma vez que inclui o filtro e com isso não ativa a ordem de "Publication - Newest first". 

Vou tentar resolver.

**Comment by deandr** [comment]
@fabiobatalha 

Poderia por gentileza alterar o arquivo config.xml da homologação no elemento ```<sort_list>``` para

```
<sort_list>
        <sort>
                <name>YEAR_DESC</name>
                <value>da desc</value>
         </sort>
         <sort>
                <name>YEAR_ASC</name>
                <value>da asc</value>
         </sort>
         <sort>
                <name>RELEVANCE</name>
                <value>score desc</value>
          </sort>
         <sort>
                 <name>SJR</name>
                 <value>order_sjr desc</value>
          </sort>
</sort_list>
```

Esta alteração é para compatibilizar a orderm definida no protótipo para as opções de ordenamento com o a homologação:

http://scielohomolog.parati.ag/iAHx/resultados.html

Obrigado.

**Comment by fabiobatalha** [comment]
Editado.

**Comment by deandr** [comment]
:+1: 

@alexxxmendonca, Favor realizar novo teste.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
