### ISSUE TITLE
Ajustar nome de campos dos indices.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/search-journals#126]
@alexxxmendonca  fez a seguinte pergunta: Isso é mais uma opinião do que uma correção. Eu como usuário fiquei confuso com a forma as expressões de busca são escritas. Por exemplo, nome do periódico é identificado por "ta", título do artigo é "ti". @fabiobatalha, vamos continuar seguindo dessa forma?

Devemos avaliar o impacto e se possível realizar a substituição dos nomes dos indices para nomes mais adequados, uma vez que a interface de usuários apresenta esses nomes quando o usuário realiza pesquisas mais complexas.

**Comment by jamilatta** [comment]
Ref.: #110

**Comment by deandr** [comment]
Também estou de acordo que os nomes de índices poderiam ser mais representativos.

Pontos de mudança que deverão ser considerados para planejarmos esta tarefa:

- processamento
- apresentação das referências bibliográficas 
- clusters
- configuração dos índices de pesquisa

[]s

**Comment by fabiobatalha** [comment]
@deandr Você acha que isso pode ser feito dentro do escopo atual sem mudanças no orçamento?

**Comment by fabiobatalha** [comment]
Foi decidido que essa mudança reflete em diversos pontos de mudança impactando no orçamento atual do projeto. Essa melhoria poderá ser implementada no futuro.
