### ISSUE TITLE
Histórico de Buscas  - Interfaces EN e ES

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#128]
No "Histórico de Buscas", as interfaces Espanhol e Inglês não estão funcionando. Já deveriam estar funcionando?

**Comment by deandr** [comment]
Sim, somente esta funcionando se o idioma é alterado logo na primeira página da pesquisa. 

Vou corrigir. Favor marcar para a próxima interação.

**Comment by alexxxmendonca** [comment]
O botão "Buscar" permanece em português, mesmo quando a interface está em EN ou ES: 

![image](https://cloud.githubusercontent.com/assets/4059679/8305094/17789f62-1982-11e5-9027-aec8374e4f7d.png)

**Comment by deandr** [comment]
OK, já realizei a correção. Na próxima atualização já estará resolvido e peço para você realizar nova validação.

**Comment by alexxxmendonca** [comment]
Ok!

Aproveitando, isso também deve ser fácil de corrigir:

![image](https://cloud.githubusercontent.com/assets/4059679/8305582/e409e5f0-1986-11e5-920c-458b582d39e0.png)

Corrigir a concordância de gênero em: Todas os registros para "Todos os registros".

**Comment by deandr** [comment]
Opa, já corrigido também. Obrigado.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
