### ISSUE TITLE
Busca não condiz com ambiente em produção

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#129]
Fiz uma busca por "AIDS" no resumo e não encontrou nenhum resultado. Fiz a mesma busca no portal atual e encontrou mais de 3000 resultados: http://search.scielo.org/?output=site&lang=pt&from=0&sort=&format=abstract&count=20&fb=&page=1&q=aids&index=ab&where=ORG&search_form_submit=Pesquisar

**Comment by deandr** [comment]
Pelos meus testes me parece que nenhum resultado esta sendo recuperado ao utilizar o índice de resumo para busca.

@jamilatta,

Poderia verificar se encontra alguma alteração no processamento que tenha causado a não indexação do resumo. 

Se for possivel liberar para meu IP o acesso via web ao Solr em http://node1-search.scielo.org:8080/ posso também tentar verificar.

[]s

**Comment by jamilatta** [comment]
Vou verificar.

2015-06-16 10:23 GMT-03:00 deandr <notifications@github.com>:

> Pelos meus testes me parece que nenhum resultado esta sendo recuperado ao
> utilizar o índice de resumo para busca.
>
> @jamilatta <https://github.com/jamilatta>,
>
> Poderia verificar se encontra alguma alteração no processamento que tenha
> causado a não indexação do resumo.
>
> Se for possivel liberar para meu IP o acesso via web ao Solr em
> http://node1-search.scielo.org:8080/ posso também tentar verificar.
>
> []s
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/search-journals/issues/129#issuecomment-112426263>
> .
>



-- 

Jamil Atta Junior

**Comment by jamilatta** [comment]
O resumo esta indexado, ver: 
![screen shot 2015-06-16 at 13 08 08](https://cloud.githubusercontent.com/assets/373745/8188179/9e65d5d8-142a-11e5-949c-3ceef0fe9b3b.png)

**Comment by deandr** [comment]
@jamilatta 

O print indica que o resumo esta armazenado. Encontrei o commit onde a linha que realiza a indexação foi removida:

https://github.com/scieloorg/search-journals/commit/ceda6d32f87b016dd096c51a048daf453f22d70b#diff-52a8834e30fa29511d993cf10610837bL134

Vamos preciar analisar melhor as demais linhas que foram removidas para verificar outros efeitos colaterais.

Estarei adicionando a linha novamente no schema.xml.

@alexxxmendonca 

Favor marcar este ticket para iteração 4.

[]s

**Comment by jamilatta** [comment]
@deandr

acho mudou de linha somente, ver:
https://github.com/scieloorg/search-journals/commit/ceda6d32f87b016dd096c51a048daf453f22d70b#diff-52a8834e30fa29511d993cf10610837bR192

2015-06-16 14:06 GMT-03:00 deandr <notifications@github.com>:

> @jamilatta <https://github.com/jamilatta>
>
> O print indica que o resumo esta armazenado. Encontrei o commit onde a
> linha que realiza a indexação foi removida:
>
> ceda6d3#diff-52a8834e30fa29511d993cf10610837bL134
> <https://github.com/scieloorg/search-journals/commit/ceda6d32f87b016dd096c51a048daf453f22d70b#diff-52a8834e30fa29511d993cf10610837bL134>
>
> Vamos preciar analisar melhor as demais linhas que foram removidas para
> verificar outros efeitos colaterais.
>
> Estarei adicionando a linha novamente no schema.xml.
>
> @alexxxmendonca <https://github.com/alexxxmendonca>
>
> Favor marcar este ticket para iteração 4.
>
> []s
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/search-journals/issues/129#issuecomment-112498717>
> .
>



-- 

Jamil Atta Junior

**Comment by jamilatta** [comment]
Desconsiderar a msg anterior realmente foi removido.

**Comment by deandr** [comment]
OK, vamos aproveitar para verificar as demais linhas removidas no commit "Segunda organização no schema.xml".  https://github.com/scieloorg/search-journals/commit/ceda6d32f87b016dd096c51a048daf453f22d70b

Estarei adicionando comentários no commit para você informar se realmente a linha deveria ter sido removida.

**Comment by jamilatta** [comment]
OK.

**Comment by deandr** [comment]
@jamilatta 

Favor informar quando a coleção for re-indexada com a correção do schema.xml para nova validação deste item pelo @alexxxmendonca.

[]s

**Comment by jamilatta** [comment]
Ambiente de homologação do search esta sendo re-indexado.

**Comment by deandr** [comment]
@alexxxmendonca 

Acredito que este ticket já possa ser novamente avaliado uma vez que a coleção foi re-indexada.

[]s

**Comment by alexxxmendonca** [comment]
Temos mais de 3000 resultados em produção, versus 2.554 resultados em homolog.

**Comment by deandr** [comment]
@jamilatta 

O índice em homologação contem todas as coleções SciELO disponíveis na produção?  Pergunto pois a mesma busca em produção retorna itens em muito mais coleções, exemplos Africa do Sul, Argentina, Peru, Portugal, etc.

[]s

**Comment by jamilatta** [comment]
Srs, o índice de homologação não é igual ao índice de produção.

Ainda estou finalizando o processamento o que impacta diretamente na
quantidade dos resultados, nessa fase não podemos fazer comparações de
quantidade de resultado e sim se o resultado esta de acordo com a pesquisa,
a qualidade nessa fase é o mais importante.

Assim que o processamento estiver completo e operando de forma consistente,
irei notificar-los para que haja uma validação de comparações entre a
produção e homologação.



2015-06-29 10:19 GMT-03:00 deandr <notifications@github.com>:

> @jamilatta <https://github.com/jamilatta>
>
> O índice em homologação contem todas as coleções SciELO disponíveis na
> produção? Pergunto pois a mesma busca em produção retorna itens em muito
> mais coleções, exemplos Africa do Sul, Argentina, Peru, Portugal, etc.
>
> []s
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/search-journals/issues/129#issuecomment-116657354>
> .
>



-- 

Jamil Atta Junior

**Comment by deandr** [comment]
@jamilatta,

Obrigado.

@alexxxmendonca,

Favor fechar este ticket uma vez que a busca esta sendo realizada ou marcá-lo como processamento para ser avaliada quando o índice estiver completo.

[]s

**Comment by alexxxmendonca** [comment]
Ok!

**Comment by deandr** [comment]
Obrigado, favor desmarcar o milestone para que ele volte para backlog.

**Comment by deandr** [comment]
@alexxxmendonca 

Com a nova atualização do índice em homologação acredito que este item já possa ser re-avaliado. Uma busca rápida pelo termo "AIDS" agora esta retornando resultados compatíveis com a produção. Poderia re-validar?

[]s

**Comment by alexxxmendonca** [comment]
Não está exatamente igual... na produção retorna 3.907 resultados e no homolog retorna 4.250.

**Comment by deandr** [comment]
@alexxxmendonca,

O resultados não irão mais bater entre homolog e produção uma vez que foram realizadas alterações na configuração de indexação dos campos conforme mencionado nos meus comentários acima e também descrito nos comentários adicionados em https://github.com/scieloorg/search-journals/commit/ceda6d32f87b016dd096c51a048daf453f22d70b

Na minha opinião acredito que agora o importante é verificar se os valores são parecidos não tendo grandes diferenças, no exemplo acima o homolog esta retornando até mais documentos.

[]s

**Comment by alexxxmendonca** [comment]
Sim, antes não retornava nada.

Acho que podemos fechar esse ticket pois fiz um teste por amostragem e o teste foi bem sucedido.

**Comment by jamilatta** [comment]
O conteúdo entre homolog e produção não irão ser os mesmos, existe procedimentos na produção que deixa os ambientes diferentes na quantidade documentos. 

Concordo com o @deandr.
