### ISSUE TITLE
Busca combinada título do periódico AND título do artigo

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#130]
Fiz uma pesquisa com a seguinte expressão:

(ta:(arquivos)) AND in:("scl") and (ti:(aids))

Essa busca deveria trazer todos os periódicos que possuam "arquivos" no nome e artigos que possuam "aids" em seu título. A busca traz 4 resultados, sendo que 2 deles não tem a palavra "Aids" no título:

http://homolog.search.scielo.org/?q=%28ta%3A%28arquivos%29%29+AND+in%3A%28%22scl%22%29+and+%C2%A0%28ti%3A%28aids%29%29&lang=pt&count=&from=&output=&sort=&format=&fb=&page=1

**Comment by deandr** [comment]
O resultado esta condizente com o ambiente de produção:

http://search.scielo.org/?output=site&lang=pt&from=0&sort=&format=abstract&count=20&fb=&page=1&q=%28ta%3A%28arquivos%29%29+AND+in%3A%28%22scl%22%29+AND+%28ti%3A%28aids%29%29&index=&where=ORG&search_form_submit=Pesquisar

No resultado em produção se pode observar que os títulos em inglês possuem a palavras "aids" .

[]s

**Comment by alexxxmendonca** [comment]
De fato, está condizente com o ambiente de produção, é que como na nova interface aparece apenas o título principal do artigo e nesses casos o título principal é em PT e não aparece a palavra "Aids", gerou-me essa confusão.

@fabiobatalha isso deve ser mantido? Incluir nos resultados mesmo quando o termo está apenas na tradução?

**Comment by fabiobatalha** [comment]
@alexxxmendonca 
Acredito que sim, a final o objetivo da ferramenta de busca é trazer conteúdo relevante a pesquisa independente do idioma.

**Comment by alexxxmendonca** [comment]
Certo. Estou fechando o ticket nesse caso.
