### ISSUE TITLE
E-mail com resultados não é enviado

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#132]
Fiz um teste para enviar os resultados por e-mail mas não o recebi. Isso já deveria estar funcionando mesmo em homolog?

![image](https://cloud.githubusercontent.com/assets/4059679/8305405/2bb6947c-1985-11e5-9e3c-561d6b118057.png)

**Comment by deandr** [comment]
@jamilatta,

Poderia confirmar que o arquivo config-mail.php esteja configurado corretamente em homologação e se não existe nenhuma regra de bloqueio no server que esteja impedindo o envio da mensagem?

Pela aplicação aparentemente esta OK, fiz um teste usando um server smtp local e consegui o envio.

[]s

**Comment by jamilatta** [comment]
Vou verificar.

**Comment by fabiobatalha** [comment]
Esta configurado corretamente.

**Comment by fabiobatalha** [comment]
@alexxxmendonca @viniciusandrade @jamilatta 

O email esta sendo enviado. Mandei para meu e-mail pessoal e funcionou. provavelmente tem alguma restrição para enviar para o domínio scielo.org.

@alexxxmendonca 

tente enviar para uma conta pessoa.

**Comment by alexxxmendonca** [comment]
De fato, recebi o e-mail quando enviei para minha conta pessoal.

**Comment by deandr** [comment]
@alexxxmendonca 

Como foi detectado que o problema não é com a interface e sim uma restrição local podemos fechar este ticket?

Obrigado.
