### ISSUE TITLE
Ajuste nos templates da interface devido a alteração nos ID's das referências

### ISSUE THREAD

**Issue by deandr** [scieloorg/search-journals#133]
Os links das referências da interface de busca para o portal SciELO estão quebrados nesta última atualização devido a alteração no processamento que removeu o prefixo art- de todos os ID's.

Arquivos que possuem referência para o elemento alterado:

https://github.com/scieloorg/search-journals/search?q=doc.ur

**Comment by deandr** [comment]
@alexxxmendonca 

Este item já pode ser avaliado, o ajuste é referente aos links do título das referências, resumo, texto e pdf que estavam quebrados e agora já devem estar OK.

[]s

**Comment by alexxxmendonca** [comment]
Os links para Resumo, Texto e PDF estão funcionando corretamente. Testei por amostragem.

Entretanto, achei um problema. Não sei se isso cabe aqui ou se seria um novo ticket.

Encontrei um exemplo de texto que não possui resumo, entretanto a interface exibe um link para o Resumo e ao clicar nele, dá erro 404:

![image](https://cloud.githubusercontent.com/assets/4059679/8455202/474f2a6e-1fd9-11e5-8ea0-f0152f3e66fe.png)

**Comment by deandr** [comment]
@jamilatta 

Você saberia informar se nos elementos disponíveis atualmente no XML exista um elemento que indique se o resumo esta disponível ou não para que eu possa verificar na interface?

[]s

**Comment by jamilatta** [comment]
@deandr 

O resumo esta disponível na interface.

**Comment by deandr** [comment]
@jamilatta 

OK. Posso assumir como regra somente mostrar o link "Resumo" na interface quando o elemento resumo estiver presente no índice para a referência?

Poderia confirmar neste caso apontado pelo Alex se esta regra é valida ou seja ollhando pela interface de administração do Solr buscar pelo registro com a palavra SOBRADPEC para ver se esta referência não possui o elemento de resumo no índice?

Obrigado

**Comment by jamilatta** [comment]
@deandr 

esse registro não possui resumo, ver: 

![screen shot 2015-07-02 at 05 12 50](https://cloud.githubusercontent.com/assets/373745/8472624/2f863ec2-2079-11e5-8638-f2532037e87a.png)

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
