### ISSUE TITLE
Campos em branco(?) na exportação em CSV de resultados selecionados

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#134]
Ao exportar os resultados selecionados em CSV, alguns campos vêm em branco:

![image](https://cloud.githubusercontent.com/assets/4059679/8305510/287729b0-1986-11e5-960c-64853e1a4372.png)

1) Que dados deveriam aparecer em "Database", "Type" e "Descriptors"?
2) Por que "Publication Country" veio em branco?
3) No campo "Fulltext URL", não seria melhor colocar o link inteiro? Penso em um usuário que fizer o download, seria muito mais fácil se já viesse com a URL toda.

**Comment by deandr** [comment]
@alexxxmendonca 

Na verdade acredito que este formato de exportação nunca foi testado na interface, pois acabei de realizar uma exportação no ambiente de produção e o resultado é o mesmo.

Vou realizar a adequação para os campos corretos. Favor marcar como iteração 5. Aproveitando todos os tickets de teste que você esta trabalhando também podem ser marcados como iteração 5.

[]s

**Comment by alexxxmendonca** [comment]
Ok!

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
