### ISSUE TITLE
Comportamento do recurso "Itens selecionados"

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#135]
O recurso "Itens selecionados" não está se comportando como deveria.

Após alguns testes de selecionar e des-selecionar, o número às vezes não bate com a quantidade real de itens selecionados.

Veja o exemplo: 

![untitled-5](https://cloud.githubusercontent.com/assets/4059679/8305757/774a56f0-1988-11e5-9250-8c23739f849b.png)

Há 10 itens selecionados mas o contador mostra apenas 9.

Houveram outros comportamentos estranhos também, a maior parte deles relacionado com o botão "Selecionar todos". Às vezes, ao des-selecionar todos, o contador mostrava "1", por exemplo.

Verificar o comportamento geral do recurso.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/

**Comment by alexxxmendonca** [comment]
Ao selecionar todos os itens, aparecem 10 itens selecionados (até aí OK). 

Entretanto, ao mudar para a página 2, os itens 11-20 aparecem des-selecionados mas ainda constam 10 itens selecionados no contador.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/

Eu não havia me atentado ao fato da ferramenta "lembrar" a seleção das páginas anteriores, mesmo ao mudar de página. Sim, claro, faz mais sentido assim.

**Comment by jamilatta** [comment]
Muito bom o recurso de lembrar os selecionados mesmo na mudança de página :+1:
