### ISSUE TITLE
Paginação dos resultados

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#136]
A pesquisa abaixo retorna 2 páginas, entretanto ao mudar para a página 2, dá erro e diz que não que "Não foram encontrados documentos para sua pesquisa"

id:("S1516-05722015000200267-scl" OR "S1981-77462015000200397-scl" OR "S0034-72802015000300141-scl" OR "S0864-34662015000200010-cub" OR "S1516-05722015000200305-scl" OR "S1682-00372015000100005-cub" OR "S1809-68912015000200262-scl" OR "S1682-00372015000100012-cub" OR "S0004-28032015000200117-scl" OR "S0100-879X2015000500465-scl") AND in:("scl" OR "cub")

**Comment by alexxxmendonca** [comment]
O critério de busca especificado no ticket agora diz que não há resultados. Como pode isso?

**Comment by deandr** [comment]
@alexxxmendonca,

Existem 2 problemas que consegui identificar relacionado a este ticket. O primeiro é que ao listar os documentos selecionados estava trazendo também o filtro, neste caso **AND in:("scl" OR "cub")**

Este caso eu já resolvi e a correção e será enviada assim que for feito o merge da iteração 5.

O segundo problema é que o formulário de pesquisa inicial por padrão sempre adiciona o filtro pela coleção SciELO Brasil, ou seja qualquer coisa que você colar na caixa de busca será feito AND com a coleção Brasil.

Eu acredito que este não seja um comportamento muito adequado mais é como esta no protótipo, será que não seria melhor alterarmos a opção padrão para buscar em todas as coleções como é atualmente no portal SciELO.org?

[]s

**Comment by fabiobatalha** [comment]
@deandr 

Esta correto, a pesquisa padrão deve ser global.

**Comment by deandr** [comment]
@fabiobatalha,

OK. Vou alterar o default do form inicial para busca em todas as coleções.

[]s

**Comment by fabiobatalha** [comment]
Ok. Estou redirecionando este ticket para iteração 6.

**Comment by alexxxmendonca** [comment]
O questão do contexto global na busca default está resolvida, mas ainda não entendi por que o critério original não funciona mais (sendo que antes ele trazia resultados). Estou persistindo em algo que não faz sentido?

**Comment by deandr** [comment]
@alexxxmendonca,

O problema é que existia um bug na função de listar os itens selecionados que trazia também os filtros junto com os ID's das referencias que foram marcadas o que resultou em uma expressão de busca inválida pois combina uma lista de ID's com duas coleções, no caso **AND in:("scl" OR "cub")**. 

Agora este problema não deve ocorrer mais, por isso sugiro realizar um novo teste desde o começo ou seja marcando os itens, listando e depois copiando a estratégia de busca e colando na caixa inicial de busca.

[]s

**Comment by alexxxmendonca** [comment]
Eu não lembro a estratégia que eu usei, e não consigo reproduzi-la me orientando pelo string da busca.

**Comment by deandr** [comment]
Pode ser qualquer outra, é simplesmente para passar pelos mesmos passos: pesquisa > selecionar referências > listar os itens selecionados > copiar a estratégia de identificadores gerado > colar a pesquisa na página inicial.

**Comment by alexxxmendonca** [comment]
Nesse caso, sim, está funcionando.

Notei uma coisa: inseri a seguinte string:

+id:("S0123-91552012000100012-col" OR "S0123-91552012000100013-col" OR "S0123-91552012000100010-col") AND in:("col")

Ela já vem com 3 artigos selecionados (por conta desse "+", acredito eu). Se eu des-seleciono todos através do checkbox "Selecionar esta página", todos os itens são des-selecionados mas no contador ainda mostra "1".

Talvez isso esteja relacionado com o #135.

**Comment by deandr** [comment]
@alexxxmendonca 

Sim, vou revisar #135. 

Se o problema original deste issue que era a paginação esta OK favor fechar.

[]s

**Comment by alexxxmendonca** [comment]
Acabo de perceber uma coisa.

Ao recuperar uma pesquisa do histórico e mudar de página, não acontece nada no primeiro clique (a aplicação dá um refresh).

Somente ao clicar uma segunda vez que a página, de fato, muda.

**Comment by deandr** [comment]
OK. Já identifiquei o problema e vou corrigir. 

:+1:

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
