### ISSUE TITLE
Mudar de página manualmente

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#138]
O campo para mudar de página manualmente não está funcionando.

![image](https://cloud.githubusercontent.com/assets/4059679/8409634/92d183aa-1e4f-11e5-9e98-36f4031226d6.png)

Ao digitar um valor e pressionar "enter", não acontece nada.

**Comment by deandr** [comment]
@alexxxmendonca,

Fiz um teste aqui e aparentemente esta funcionando. Uma coisa que notei é o servidor de homologação esta um pouco lento hoje. Será que no seu teste a página carregou completamente? Poderia limpar o cache e também tentar testar em outros navegadores para ver se o problema ocorre em todos os casos?

[]s

**Comment by alexxxmendonca** [comment]
Testei novamente, inclusive em um navegador que nunca utilizo (IE) mas o problema persiste.

Notei também que o campo tem um espaço a mais, de forma que se o usuário clicar na extrema direita do campo, pode acontecer isso "1 0" ao invés disso "10".

**Comment by deandr** [comment]
Esta questão do espaço já pode ser uma dica do problema.

Quando você digita o valor e pressiona "Enter" é feito o refresh da página pelo navegador voltando para a página 1 ou o "Enter" é ignorado completamente e nada ocorre?

**Comment by alexxxmendonca** [comment]
O "Enter" é ignorado completamente e nada ocorre.

**Comment by alexxxmendonca** [comment]
Espaço em branco da caixa de paginação removido, porém permanece o problema de não executar a função ao pressionar "enter".

**Comment by fabiobatalha** [comment]
@alexxxmendonca 

Aqui esta funcionando.

**Comment by fabiobatalha** [comment]
@deandr 

Testado e identificado que o problema acontece somente quando preenchido o campo no final da página.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/.
