### ISSUE TITLE
Mensagem "Sem resultados"

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#140]
Ao fazer uma busca onde não há resultados, o comportamento atual é:

- a busca retorna para a página inicial com uma busca em branco e exibe a mensagem "Sem resultados".

![image](https://cloud.githubusercontent.com/assets/4059679/8431435/e40b8390-1f0f-11e5-95aa-b1780fc08d5c.png)

O ideal seria:

- a busca anterior ser mantida (ou seja, não redirecionar para a página inicial zerada) e exibir a mensagem "Sem resultados". A ferramenta deve permitir fechar a mensagem sem afetar a exibição da página atrás da caixa de diálogo.

**Comment by deandr** [comment]
@alexxxmendonca 

Concordo com seu comentário mas a forma proposta não é possível de se implementar sem maiores desenvolvimentos uma vez que a interface atual precisa realizar o refresh da página para enviar a consulta para o servidor e retornar uma página de resultado. 

A alteração que realizei nesta última iteração foi manter a expressão utilizada pelo usuário para que ele possa corrigir e tentar novamente. 

Note também que o comportamento atual esta de acordo com o protótipo:

http://scielohomolog.parati.ag/iAHx/notFound.html

[]s

**Comment by alexxxmendonca** [comment]
De acordo. Aguardo então a posição de @fabiobatalha e @jamilatta

**Comment by jamilatta** [comment]
@deandr 

por gentileza poderia indicar como podemos simular esse comportamento no interface proposta, estou utilizando o seguinte link: http://scielohomolog.parati.ag/iAHx/

**Comment by deandr** [comment]
@jamilatta 

Só encontrei forma de acessar a página de documentos não localizados diretamente pelo navegador. 

Acho que por se tratar de um site estático o designer não teve oportunidade de colocar uma forma de inserir uma expressão inválida e direcionar para a página em questão.

[]s

**Comment by jamilatta** [comment]
Hum, vou verificar com o designer. Grato @deandr.

2015-07-06 11:32 GMT-03:00 deandr <notifications@github.com>:

> @jamilatta <https://github.com/jamilatta>
>
> Só encontrei forma de acessar a página de documentos não localizados
> diretamente pelo navegador.
>
> Acho que por se tratar de um site estático o designer não teve
> oportunidade de colocar uma forma de inserir uma expressão inválida e
> direcionar para a página em questão.
>
> []s
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/search-journals/issues/140#issuecomment-118873591>
> .
>



-- 

Jamil Atta Junior

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
