### ISSUE TITLE
Mostrar todos os anos da base no campo "Ano"

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#141]
Atualmente, os anos disponíveis vão de 1997 a 2015:

![image](https://cloud.githubusercontent.com/assets/4059679/8431514/62adf750-1f10-11e5-96c7-4cef868c355b.png)

Entretanto, o artigo mais antigo da base SciELO Brasil é datado de 1909 (@fabiobatalha pode confirmar isso se eu estiver errado). De qualquer maneira, a ferramenta deve ser capaz de identificar o ano da publicação mais antiga na base e exibir nessa listagem.

**Comment by deandr** [comment]
O ano inicial mostrado no formulário é configuravél através do elemento **publication_year_start** do arquivo **config.xml** da interface.

**Comment by jamilatta** [comment]
Adicionar essa quantidade de anos em uma arquivo de configuração é no mínimo insano, existe componentes que resolvem isso de forma dinâmica e mais elegante. 

Fiz uma pesquisa e encontrei um componente que pode evitar um arquivo com 100 linhas contendo anos :-(): 

Página para documentação(nem precisa olha a documentação o exemplo resolve): http://bootstrap-datepicker.readthedocs.org/en/latest/options.html
 
Exemplo do bootstrap datepicker: http://jsfiddle.net/BjtNY/2/

@alexxxmendonca por gentileza poderia avaliar e dar uma sugestão sobre o componente proposto?

**Comment by deandr** [comment]
@jamilatta 

Acho que você não entendeu no arquivo de configuração basta informar o ano inicial pois a lista é gerada através de um loop do ano inicial até o ano atual. Eu não seria tão ruim assim com vocês  8-)

[]s

**Comment by jamilatta** [comment]
:+1: , vou alterar o arquivo de configuração para que possamos verificar a usabilidade.

**Comment by jamilatta** [comment]
Srs, arquivo de configuração alterado, de qualquer forma acredito que a lista ficou grande.

**Comment by jamilatta** [comment]
@alexxxmendonca segue outro link para testar o componente: http://goo.gl/DfOzpi

**Comment by alexxxmendonca** [comment]
Acho que o componente é mais interessante do que a listagem de ano. Por mim, podemos adotá-lo no lugar na lista, mas temos que garantir que irá funcionar corretamente mesmo em versões mais antigas de browser e também nos tablets.

**Comment by deandr** [comment]
@alexxxmendonca 

Podemos então marcar com label **Melhorias** este ticket e remover o milestone Iteração 6 uma vez que na interface esta de acordo com o protótipo?

[]s

**Comment by alexxxmendonca** [comment]
ok!

**Comment by alexxxmendonca** [comment]
#217
