### ISSUE TITLE
"Visualizar Resultados" não funciona no IE 10

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#142]
Fica nessa janela, carregando em loop.

![image](https://cloud.githubusercontent.com/assets/4059679/8432006/b1401aee-1f13-11e5-86a5-ac8f22e83f71.png)

Ao fechar a janela, a tela congela, sendo necessário dar refresh para continuar.

**Comment by deandr** [comment]
@alexxxmendonca 

Este ticket e também o #143 foram resultado de um efeito colateral na resolução de um ticket. Já providencie o ajuste e quando for atualizado o homolog te aviso para novo teste.

[]s

**Comment by jamilatta** [comment]
Ambiente atualizado.

**Comment by deandr** [comment]
@jamilatta 

Conforme comentário https://github.com/scieloorg/search-journals/pull/139#issuecomment-117204215 foram adicionados novos commits ontem e também hoje ao PR. É necessário atualizar novamente.

Obrigado

**Comment by jamilatta** [comment]
@deandr 

executei o comando agora :-)

**Comment by deandr** [comment]
@jamilatta 

Obrigado mais aparentemente ainda não pegou as últimas atualizações, por exemplo o commit https://github.com/deandr/search-journals/commit/4d3f1bc3b20c32e07175705afaccb5a44d3daca6 adicionado ontem que remove os links do menu superior do template ainda não aparece no homolog.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/ no IE 10.
