### ISSUE TITLE
Posição de "Adicionar outro campo +" e "Histórico de busca"

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#145]
O posicionamento dos links "Adicionar outro campo +" e "Histórico de busca" na Homepage (apenas na home) não condiz com a proposta do designer:

Versão atual:
![image](https://cloud.githubusercontent.com/assets/4059679/8454763/40ccc7d0-1fd6-11e5-9e70-8e99902c4e71.png)

Versão do designer:
![image](https://cloud.githubusercontent.com/assets/4059679/8454767/45a650fa-1fd6-11e5-99b9-03f76e8f4173.png)

**Comment by deandr** [comment]
@alexxxmendonca 

Este item já pode ser avaliado.

Obrigado

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
