### ISSUE TITLE
Adicionando itens no histórico ao utilizar a paginação 

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#146]
@deandr 

ao utilizarmos a paginação é adicionado itens no histórico, logo abaixo esta um teste que realizei os itens de # 3 a # 4 são cliques de paginação: 

![screen shot 2015-07-02 at 05 39 46](https://cloud.githubusercontent.com/assets/373745/8473066/ea497dd4-207c-11e5-8a44-fb69af413b0d.png)

**Comment by deandr** [comment]
@jamilatta 

Obrigado por identificar o problema. Foi ajustado o comportamento. Quando possível favor re-avaliar.

[]s

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/

**Comment by jamilatta** [comment]
Aprovado.

On Mon, Jul 6, 2015 at 10:53 AM, alexxxmendonca <notifications@github.com>
wrote:

> Testado e aprovado em http://homolog.search.scielo.org/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/search-journals/issues/146#issuecomment-118860592>
> .
>



-- 

Jamil Atta Junior
