### ISSUE TITLE
Link "Share" não funciona

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#149]
Nenhuma das opções do link "Share" estão funcionando:

![image](https://cloud.githubusercontent.com/assets/4059679/8679140/3ef4ab90-2a2f-11e5-8648-2a6569568384.png)

**Comment by deandr** [comment]
@jamilatta 

Acredito que esteja faltando informar no **config.xml** o id referente ao serviço sharethis utilizado pelo designer para esta funcionalidade.

Favor adicionar a seguinte linha no arquivo config.xml dentro do elemento ```<dia_config>```:
```
<sharethis_pub>42009467-3534-44d9-901d-6bfa29a807c4</sharethis_pub>
```

Obrigado

**Comment by fabiobatalha** [comment]
@deandr, @alexxxmendonca 

Configuração feita, verificar se esta ok.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
