### ISSUE TITLE
Incluir botão "Enviar link por e-mail"

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#150]
Na proposta original do designer está previsto um botão de enviar link por e-mail, para cada resultado:

![image](https://cloud.githubusercontent.com/assets/4059679/8679205/a0d68a0e-2a2f-11e5-8077-51bf6307da8e.png)

**Comment by deandr** [comment]
@alexxxmendonca 

Como a funcionalidade de compartilhar um link não existe no sistema e o protótipo do designer aponta para a mesma janela de envio de emails das referências foi necessário adaptar esta opção para utilizar o mesmo serviço de compartilhamento de links (sharethis) para o enviar o link por email.

Quando o ambiente de homologação for atualizado favor verificar se esta adaptação atende as necessidades.

[]s

**Comment by alexxxmendonca** [comment]
Não entendi a solução proposta. Onde está o link para enviar por e-mail?

**Comment by alexxxmendonca** [comment]
Ignorar o comentário acima. Devia ser cache do navegador. 

Agora vejo o ícone, entretanto ele está ativando com mouse over quando deveria ser mouse click.

**Comment by deandr** [comment]
@alexxxmendonca,

Favor realizar novo refresh da página de resultados pois alterei o comportamento para não mais ser ativado com o mouse over.

[]s

**Comment by alexxxmendonca** [comment]
Mouse click OK, entretanto o cursor do mouse está com a seta e deveria estar com a "mãozinha", como os demais links da página.

**Comment by deandr** [comment]
@alexxxmendonca,

Foi alterado o comportamento do cursor para ficar igual aos demais links. Favor quando possível verificar.

[]s

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
