### ISSUE TITLE
Ajustes interface Espanhol

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#151]
Notei alguns ajustes necessários na interface em Espanhol:

![image](https://cloud.githubusercontent.com/assets/4059679/8679638/37fd0f3c-2a32-11e5-8b67-5d2fddecf674.png)

**Comment by deandr** [comment]
@alexxxmendonca 

Ajustes realizados. Favor quando possível validar.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
