### ISSUE TITLE
Permanecer números do histórico de buscas

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#154]
Enviado pelo Abel:

Ao excluir uma busca da lista do histórico de buscas, as demais devem permanecem com o mesmo número, ou seja, não devem ser renumeradas.

A razão é que elas podem estar referenciadas em outras buscas, por ex, #10= #2 or #7.  Se Vc deletar a #4 a buscar passa a ser efetivamente com o #8 atual.

**Comment by alexxxmendonca** [comment]
O problema persiste, mesmo após atualização do ambiente.

**Comment by scielo** [comment]
@deandr

É necessário sincronizar com o último pull-request?

*Fabio Batalha C. Santos*
Colegiado SciELO
www.scielo.org
FAPESP - CNPq - BIREME - FapUNIFESP

**Comment by deandr** [comment]
@fabiobatalha 

Pensei que não fosse necessário mas acabei de realizar um teste local e vi que tinha modificações no repositório do search-journals não enviadas 8-(

Poderia por gentileza atualizar com o último pull request?

Obrigado.
[]s

**Comment by fabiobatalha** [comment]
@deandr @alexxxmendonca 

Atualizado com pullrequest.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em homolog.search.scielo.org
