### ISSUE TITLE
Substituição dos links de redes sociais para um único botão "Share"

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#155]
Enviado pelo Abel:

O link de share nas referências dos resultados da busca deve substituir o facebook, twitter e delicious. Ele contém ou deveria conter todos os serviços de links para redes sociais e outros.

**Comment by deandr** [comment]
@alexxxmendonca 

Desculpe mas não entendi este issue. Se é um botão novo ou já existente no protótipo que deve abrir um menu com os outros ícones já existentes. Poderia tentar anexar uma imagem representando o que se deseja?

[]s

**Comment by alexxxmendonca** [comment]
@deandr 

Penso que seria algo mais genérico como o serviço fornecido pelo AddThis: http://www.addthis.com/

![image](https://cloud.githubusercontent.com/assets/4059679/9382417/fbc70cbe-4716-11e5-8a91-81aeb97529da.png)

**Comment by deandr** [comment]
@alexxxmendonca 

Foi feito um trabalho de customização do serviço sharethis pelo designer para permitir compartilhar cada referência individualmente. No caso de se usar o botão fornecido pelos serviços addthis ou sharethis sempre é compartilhado a página inteira do resultado uma vez que eles se baseiam na URL corrente para realizar o compartilhamento.

Favor remover este ticket da iteração 8 uma vez que será necessário primeiro definir como deve ser a saída desejada e depois verificar se é possível a implementação.

[]s

**Comment by alexxxmendonca** [comment]
#190
