### ISSUE TITLE
Classificação dos clusters por ordem alfabética

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#156]
Enviado pelo Abel:

A classificação das categorias dos clusters por ordem alfabética deve considerar o conjunto das categorias e não somente as que estão visíveis.

**Comment by deandr** [comment]
Este issue esta relacionado ao #88 pois para as classificação considerar o conjunto é necessário sempre trazer a lista completa de itens para a interface.

**Comment by fabiobatalha** [comment]
Esse ticket será encerrado. Como explicitado por @deandr, a necessidade de carregar a lista completa de clusters para realizar o sort pela lista completa se torna inviável na arquitetura atual do IAHx devido ao custo de processamento, tempo de carga do site para todas as requisições, etc.

Sugerimos a inclusão desta reformulação complexa da arquitetura do IAHx no core do projeto IAHx.

**Comment by alexxxmendonca** [comment]
Em reunião com Abel na data de ontem, uma vez que não é possível classificar os clusters levando em conta o conjunto como um todo, ficou decidido por remover a possibilidade de classificar.

A lista deve ser exibida em ordem alfabética por default, sem possibilidade de classificação.

**Comment by deandr** [comment]
@alexxxmendonca 

Acredito que este ticket já pode ser considerado finalizado uma vez que agora já foi implementado a janela que apresenta todos os itens do cluster com as opções de ordenar, download e exportação. Concorda?

**Comment by alexxxmendonca** [comment]
Sim, bem observado.
