### ISSUE TITLE
Resultados - Separar os milhares

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#158]
Nos resultados, separar os milhares:

- por ponto em português e espanhol 
- por vírgula no inglês

**Comment by deandr** [comment]
@alexxxmendonca 

Poderia especificar se este ajuste é no total de documentos recuperados ou nos totais de itens apresentados nos filtros ou em ambos?

[]s

**Comment by alexxxmendonca** [comment]
Ambos. Trata-se de uma questão de idioma. No inglês, o milhar é indicado por vírgula.

**Comment by fabiobatalha** [comment]
Acho que todos totais devem ficar sem pontuação. Esse é o tipo de complexidade que pode ser evitado e o resultado prático para o usuário é indiferente.

**Comment by fabiobatalha** [comment]
![screen shot 2015-08-18 at 11 32 37 am](https://cloud.githubusercontent.com/assets/504142/9332804/db3a6da4-459c-11e5-8f4d-fbdd25ad287d.png)
Basta tirar a pontuação e atender os dois idiomas sem necessidade de implementações complexas.

**Comment by alexxxmendonca** [comment]
Eu discordo. Acho confuso mostrar "Resultados: 562141".

Se for muito complexo, sou a favor de adotarmos uma forma padrão para todos. Nesse caso, creio ser melhor utilizarmos o ponto.

**Comment by deandr** [comment]
Da parte de implementação o mais prático seria padronizar um único formato para todos. De qualquer forma vocês decidem. 

@alexxxmendonca  Favor marcar este issue como "Melhoria" uma vez que o atual esta de acordo com o protótipo.

**Comment by fabiobatalha** [comment]
@alexxxmendonca Você decide.

**Comment by alexxxmendonca** [comment]
É possível utilizar um espaço como separador milhar? 

Exemplo: 

"Resultados: 562 141"

Parece que a maioria dos países entende esse tipo de separação (https://en.wikipedia.org/wiki/Decimal_mark#Examples_of_use)

Como os resultados serão sempre inteiros e não trabalharemos com números decimais, não haveria a necessidade de vírgula ou ponto.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
