### ISSUE TITLE
Reduzir tamanho da coluna à esquerda

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#159]
A pedido do Abel, a coluna da esquerda deve ser reduzida de tamanho em 5 caracteres.

**Comment by fabiobatalha** [comment]
Sério? Qual o resultado efetivo desta mudança?

**Comment by alexxxmendonca** [comment]
Ele não informou. Talvez por estética apenas. Estou satisfeito com o tamanho atual.

Talvez possamos conversar com ele sobre isso.

**Comment by alexxxmendonca** [comment]
Com o ticket #228, esse ticket não faz mais sentido.
