### ISSUE TITLE
Saída dos resultados apenas em um idioma

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#160]
Comentário do Abel: 

"A indicação dos idiomas presentes está errada.

Apresenta somente apenas uma opção de idioma quando deveria ser pelo menos duas sempre. Às vezes o texto é em português e indica espanhol. Não indica as diferentes versões de resumo."

**Comment by fabiobatalha** [comment]
Nem sempre haverá 2 idiomas para apresentação, não é verdade afirmar que deveria ser pelo menos duas sempre.

Entretanto, existem erros na identificação de idiomas, existem situações onde o texto completo, abstract e PDF estão presentes em mais de 1 idioma e a interface não esta apresentando.

Verifiquei também com o Jamil que alguns ajustes precisam ser feitos no XML.


Caso em que o texto completo aparece apenas em 1 idioma e sem PDF.
http://www.scielo.br/scielo.php?script=sci_issuetoc&pid=0011-525819990002&lng=en&nrm=iso

Caso sem abstract:
http://www.scielo.br/scielo.php?script=sci_issuetoc&pid=0011-525820080002&lng=en&nrm=iso

Caso onde PDF, HTML e Abstract estão disponíveis somente em 1 idioma.
http://www.scielo.br/scielo.php?script=sci_issuetoc&pid=1809-486420140002&lng=en&nrm=iso

**Comment by deandr** [comment]
A interface esta utilizando o atributo **la** do XML para mostrar a informação de idiomas disponíveis e montar o links.

Acredito que para contemplar todos os casos seja necessário adicionar outros elementos no XML que permitam montar os links somente para os formatos (PDF, HTML e Abstract) disponíveis e nos idiomas correspondentes.

Sugiro mover este item para "Processamento" e retirar do "Escopo .." pois com os elementos do XML atual não é possível esta separação no template.

[]s

**Comment by fabiobatalha** [comment]
Correto @deandr,

Vamos incluir esses ajustes no XML.

**Comment by jamilatta** [comment]
@deandr 

os elementos solicitado estão agora disponíveis no índice, ver: 

![screen shot 2015-08-18 at 16 24 56](https://cloud.githubusercontent.com/assets/373745/9340400/dcb72e46-45c5-11e5-9657-267f7eb0934f.png)


Considere ``fulltext_pdf_*`` e ``fulltext_html_*``

**Comment by fabiobatalha** [comment]
@deandr 
O atributo *la* apresenta os idiomas disponíveis independente da manifestação do documento nas versões HTML, PDF e ABSTRACT.

Neste caso pode ser que em *la* indique a existência de PT, ES e EN

Entretanto pode ser que:

 * Os PDF's estejam disponíveis somente em PT, EN 
 * Os ABSTRACTS estejam disponíveis em PT, ES, EN
 * Os HTML's estejam disponíveis apenas em PT
.......

Em fim, a interface tem que apresentar links somente para as manifestações existentes.

**Comment by deandr** [comment]
@fabiobatalha 

Só para verificar se entendi corretamente:

Pela descrição inicial do issue eu havia entendido que o atributo **la** não estava coerente com as opções de idioma disponíveis para o artigo além de não ser suficiente para indicar se o PDF e HTML estavam presentes. 

Pelo seu último comentário entendo que o atributo **la** esta correto e posso realizar o loop sobre ele para então buscar pela existência dos atributos correspondentes ao PDF e HTML, é isso mesmo?

Outra questão é que foi criado somente os atributos que indicam a existência do PDF e HTML, posso assumir que o ABSTRACT estará sempre disponível para o **la** correspondente?

Obrigado
[]s

**Comment by fabiobatalha** [comment]
@deandr 

Sua primeira afirmação esta correta. Iterar por LA e apresentar links apenas para os idiomas presentes em PDF, HTML e ABSTRACT.

Quanto ao Abstract ele também pode não existir para alguns idiomas.

O campo abstract segue o seguinte formato: ab_{language}, sendo assim, você consegue seguir o mesmo esquema utilizado para apresentar o link de HTML e PDF.

**Comment by deandr** [comment]
@fabiobatalha 

OK. Realizei a implementação usando estas condições de verificação.

[]s

**Comment by alexxxmendonca** [comment]
Acho que o problema ainda persiste...

**Comment by deandr** [comment]
@alexxxmendonca 

Poderia informar alguns exemplos de casos com problema para que possamos verificar?

Obrigado

**Comment by alexxxmendonca** [comment]
Busca por "diabetes":

http://homolog.search.scielo.org/?q=diabetes&lang=pt&count=15&from=0&output=site&sort=&format=summary&fb=&page=1

No primeiro resultado, ambos os links do resumo (PT e EN) retornam o resumo em inglês.

**Comment by deandr** [comment]
@alexxxmendonca 

OK. Obrigado, realizei um ajuste no template e o Jamil já atualizou o ambiente novamente. Quando puder realize um novo teste.

[]s

**Comment by alexxxmendonca** [comment]
Agora sim, parece que está OK.

Só uma dúvida: notei que alguns registros não possuem link para o texto completo. Ex: http://homolog.search.scielo.org/?fb=&q=%28ta%3A%28enfermagem%29%29&lang=en&count=15&from=1&output=site&sort=YEAR_DESC&format=summary&page=1&where=&filter%5Bta_cluster%5D%5B%5D=Rev.+Latino-Am.+Enfermagem

Isso tem a ver com processamento?

**Comment by deandr** [comment]
@jamilatta 

Poderia confirmar se já foram re-processados todos os documentos e caso afirmativo se os  artigos citados pelo Alex possuem os elementos de fulltext_html_*?

Obrigado

**Comment by jamilatta** [comment]
Vou verificar.

Atenciosamente, 

Jamil Atta Junior

**Comment by jamilatta** [comment]
@deandr e @alexxxmendonca  

por conta de vários ajustes realizados vou reprocessar o índice isso pode demorar algumas horas assim que terminar avisa para revalidarem as atividades.

**Comment by jamilatta** [comment]
@deandr e @alexxxmendonca 

estou com quase 80% do índice processado é possível reavaliar essa pendências.

Para a query: 

```
http://homolog.search.scielo.org/?fb=&q=%28ta%3A%28enfermagem%29%29&lang=en&count=15&from=1&output=site&sort=YEAR_DESC&format=summary&page=1&where=&filter%5Bta_cluster%5D%5B%5D=Rev.+Latino-Am.+Enfermagem
````

olhando por amostragem e considerando os registros avaliados, todos constam com o atributo fulltext_html_pt.

**Comment by jamilatta** [comment]
É possível verificar utilizando a url: http://node1-search.scielo.org:8080/iahx-controller/?site=solr%2Fscielo&col=articles&count=15&output=site&lang=en&sort=da+desc&op=search&q=%28ta%3A%28enfermagem%29%29&fq=ta_cluster%3A%28%22Rev.+Latino-Am.+Enfermagem%22%29%20

**Comment by deandr** [comment]
@jamilatta,

Obrigado pelo retorno.

@alexxxmendonca,

Realizando a pesquisa do seu comentário anterior (https://github.com/scieloorg/search-journals/issues/160#issuecomment-135858754) é possível concluir que era um detalhe de processamento. Portanto se os links estiverem corretos para as opções (Resumo, PDF e Texto completo) para os idiomas favor encerrar este issue.

[]s

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
