### ISSUE TITLE
Incluir botão de "Filtrar" nos clusters

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#161]
Comentário do Abel:

"Ao selecionar uma categoria de um cluster com múltiplas opções, não é possível pois ao clicar uma vez efetua de imediato a seleção e não permite múltipla escolha. Por exemplo, ano de publicação, se quero selecionar os anos 2013 e 2014 consigo somente um deles e não os dois. Se o sistema for incapaz de fazer OR, o que seria uma pena, a seleção deveria ser feita por radio box. Mas, prefiro que seja checkbox."

"...[o botão] deve ficar fixo no alto da página de modo que ao efetuar as seleções o botão filtrar está logo acima e não precisar correr o texto."

**Comment by deandr** [comment]
Este item foi discutido durante a etapa inicial de desenvolvimento e o botão foi considerado não intuitivo.

https://github.com/scieloorg/search-journals/pull/83#discussion_r29369609

[]s

**Comment by fabiobatalha** [comment]
@deandr

Acho que o botão de filtrar é desnecessário mesmo uma vez que o evento de filtragem pode ser disparado através da seleção de um item do cluster.

Entretanto a lista dos clusters deveria se manter completa mesmo após um filtro ser realizado permitindo que o usuário possa selicionar 1 ou mais itens de um mesmo cluster. Se essa implementação não é possível, então o botão de filtrar passa a ter sentido e mesmo assim, pouco intuitivo.

**Comment by alexxxmendonca** [comment]
Concordo com a solução proposta: a lista dos clusters deveria se manter completa mesmo após um filtro ser realizado permitindo que o usuário possa selicionar 1 ou mais itens de um mesmo cluster.

**Comment by deandr** [comment]
@fabiobatalha 

A lista dos clusters é sempre baseada no conjunto das referências do resultado, desta forma quando é feito a seleção de um item o conjunto de referências retornada no resultado é um subconjunto do primeiro e desta forma os itens mostrados no cluster também serão um subconjunto da lista inicial. 

Desta forma não é possível manter a lista completa, pois ela é dinamicamente gerada levando-se em consideração o conjunto de referências retornada.

Lembrando que a opção de múltipla seleção de itens de um cluster ainda existe e somente foi movida pelo designer para a opção "Selecionar" ao se clicar no ícone ao lado do título do cluster.

[]s

**Comment by alexxxmendonca** [comment]
Retomando esse assunto, os clusters não devem ser baseados no conjunto das referências do resultado, mas sim na busca original.

Analisem o seguinte comportamento:

- Ao fazer uma busca por "dengue", a busca retorna os seguintes valores no cluster de idiomas:

![image](https://cloud.githubusercontent.com/assets/4059679/15550911/f2e99dba-2289-11e6-9386-19a0f8fb1023.png)

- Ao selecionar o idioma "Português", os valores alteram para:

![image](https://cloud.githubusercontent.com/assets/4059679/15550928/080ef514-228a-11e6-956f-26d6f7cf871d.png)

- Por fim, ao selecionar novamente, os valores em inglês voltam para os originais:

![image](https://cloud.githubusercontent.com/assets/4059679/15550977/33eed08c-228a-11e6-8c5c-a39ba92c4299.png)

Se não for possível manter os clusters na busca original (ao invés de baseados no conjunto das referências do resultado), precisaremos do botão de "Filtrar".

**Comment by alexxxmendonca** [comment]
Cada cluster deverá possuir opção "AND" e "OR" (traduzido de acordo com a interface), válido para a seleção daquele cluster.

Entre clusters, a operação deverá ser sempre "AND".

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
