### ISSUE TITLE
Adicionar no resultado da pesquisa o total de citação por artigo.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#166]
Na interface proposta, ver: http://scielohomolog.parati.ag/iAHx/resultados.html, devemos adicionar a quantidade de citação que cada artigo recebeu.

Desenvolvemos um script que utiliza o http://citedby.scielo.org para coletar esse indicador e atualiza o índice.

Realizei uma alteração no ``schema.xml`` adicionando o campo ``total_received``(reconheço que o nome não esta bom, mas logo irei renomear).

Ver: https://github.com/scieloorg/search-journals/blob/beta/solr/schema.xml#L170

Para essa tarefa considere o campo ``total_received``.

Desenho para o resultado de pesquisa: 

![screen shot 2015-08-20 at 09 55 33](https://cloud.githubusercontent.com/assets/373745/9383840/4d8762aa-4722-11e5-8ae7-09a9b5445544.png)

Atenção: O processamento que adicionar esse indicador ainda não finalizou portanto nem todos os registros contém esse indicador, por hora, segue alguns IDs:

http://homolog.search.scielo.org/?q=total_received%3A*&lang=pt&count=10&from=0&output=site&sort=&format=summary&fb=&page=1

**Comment by jamilatta** [comment]
Lembrando que devemos ter esse item na ordenação: 

![screen shot 2015-08-20 at 14 40 09](https://cloud.githubusercontent.com/assets/373745/9390752/7498e284-4749-11e5-9216-34aa5ea82fb5.png)

**Comment by fabiobatalha** [comment]
Lembrando que o texto "no SciELO Citation Index" deve ser substituido por "no SciELO"

**Comment by jamilatta** [comment]
Para essa atividade é necessário que possamos configurar qual coleção mostrará essa métrica. Acredito que uma lista com o acrônimo da coleção no arquivo de configuração seria o ideal.

**Comment by deandr** [comment]
@jamilatta,

No template de apresentação é feita a verificação se a métrica esta presente no documento antes de apresentar a linha contendo a informação. 

Você acredita que isso pode substituir a necessidade de termos uma configuação, uma vez que o processamento só adiciona este dado nos documentos onde o total esta disponível?

[]s

**Comment by jamilatta** [comment]
@deandr 

de acordo, acredito que a avaliação da presença do campo no índice é suficiente, lembrando que não devemos adicionar qualquer valor padrão, devemos omiti a métrica removendo por consequência o texto ``Citado xx vezes....``.

**Comment by deandr** [comment]
:+1:

**Comment by jamilatta** [comment]
Todas as citação estão cadastradas no ambiente de homologação.

**Comment by alexxxmendonca** [comment]
Quando peço para ordenar por "Mais citados primeiro", os primeiros registros aparecem sem título. Isso é normal?

![image](https://cloud.githubusercontent.com/assets/4059679/9552561/7457b7e0-4d8f-11e5-9644-00ca94ab3d5b.png)

Os títulos só voltam a aparecer lá pela página 100.

**Comment by deandr** [comment]
@alexxxmendonca 

Verifiquei com o @jamilatta e esse compartamento é normal. Ele pode dar mais detalhes.

[]s

**Comment by jamilatta** [comment]
@alexxxmendonca e @deandr 

ainda estamos ajustando os processamento e portanto existem item que estão em título. 

Este problema é de conteúdo não esta relacionado com a aplicação, assim que alinharmos todas as inconsistências notifico para voltarmos nesse ponto, mas por hora esse comportamento é normal.

**Comment by alexxxmendonca** [comment]
O problema dos títulos que não apareceriam foi resolvido.

Fica agora uma última correção: corrigir "na SciELO" por "no SciELO"

**Comment by deandr** [comment]
@alexxxmendonca 

Foi solicitado via hangout pelo @jamilatta a alteração do texto para "na SciELO" e também a remoção do nome da coleção ao lado do total de downloads.

[]s

**Comment by alexxxmendonca** [comment]
@jamilatta qual seria a justificativa para essa escolha?

**Comment by jamilatta** [comment]
@alexxxmendonca 

essa foram solicitações realizadas pelo @fabiobatalha, apenas retransmiti para @deandr, verifiq

**Comment by alexxxmendonca** [comment]
O último pedido registrado do Fábio pedia "no SciELO": https://github.com/scieloorg/search-journals/issues/166#issuecomment-134229235

**Comment by jamilatta** [comment]
Alex,

acredito que em uma conversa com ele falamos em "na SciELO" por ser a *rede
SciELO*, mas para facilitar verifique com ele, por gentileza.

On Mon, Sep 21, 2015 at 4:33 PM, alexxxmendonca <notifications@github.com>
wrote:

> O último pedido registrado do Fábio pedia "no SciELO": #166 (comment)
> <https://github.com/scieloorg/search-journals/issues/166#issuecomment-134229235>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/search-journals/issues/166#issuecomment-142086452>
> .
>



-- 

Jamil Atta Junior

**Comment by alexxxmendonca** [comment]
@fabiobatalha favor confirmar se é "no" ou "na"

**Comment by fabiobatalha** [comment]
Senhores,

Eu pedi para tirar o "Citation Index".

Quanto ao gênero do SciELO, da SciELO. Depende do que estamos falando.

O SciELO (Projeto SciELO)
A SciELO (Biblioteca SciELO)

Neste caso para mim faz sentido falar da biblioteca, então o gênero seria feminino.
ex:
122 citações na SciELO
333 acessos na SciELO

**Comment by alexxxmendonca** [comment]
Ok, manteremos como "na SciELO" então.
