### ISSUE TITLE
Adicionar no resultado da pesquisa o total de acesso por artigo. 

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#167]
Semelhante ao ticket de citação.... tk #166, devemos ter a quantidade de acessos por artigo. 

Seguindo a mesma linha de ação da citação irei adicionar um campo no ``schema.xml`` chamado ``total_access``.

Considere esse campo para mostrar na interface.  

Interface: 

![screen shot 2015-08-20 at 09 55 33](https://cloud.githubusercontent.com/assets/373745/9390846/082253aa-474a-11e5-84d8-cfb34e106184.png)

**Comment by fabiobatalha** [comment]
Lembrando que o texto "no SciELO Citation Index" de ser substituido por "no SciELO".

**Comment by jamilatta** [comment]
Para essa atividade é necessário que possamos configurar qual coleção mostrará essa métrica, pois atualmente temos somente os dados da coleção Brasil. 

Acredito que uma lista com o acrônimo da coleção no arquivo de configuração seria o ideal.

**Comment by jamilatta** [comment]
O índice esta atualizado com todos os acessos da coleção SciELO Brasil.

**Comment by alexxxmendonca** [comment]
Ainda há 2 pequenos detalhes:

1) a cor da fonte deve ser diferente (cinza) em "na SciELO"
2) na quantidade de downloads, não está especificando a Coleção (Brasil, Cuba, etc) -- vai ficar assim mesmo?

**Comment by deandr** [comment]
1) No meu navegador a cor da fonte para o rótulo esta de acordo com o protótipo. Poderia realizar um refresh e confirmar?

![scielo-referencia](https://cloud.githubusercontent.com/assets/5338655/10019618/c711660a-6114-11e5-98d7-c0189cf03d8e.png)

2) Solicitado via hangout pelo @jamilatta ...  "se possível na métrica de acesso:  729 downloads no SciELO" remover: "no SciELO"

[]s

**Comment by alexxxmendonca** [comment]
Ok! Tudo certo agora.
