### ISSUE TITLE
Bug no histórico de pesquisa

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#168]
Ao utilizarmos o histórico de pesquisa combinado com AND e o resultado é vazio o campo de pesquisa não mantém a estratégia de busca anterior... ficando com o valor #XX do histórico e impossibilitando uma nova pesquisa.

**Comment by jamilatta** [comment]
Segue uma sequência como exemplo:

1. Pego um histórico:

![screen shot 2015-08-25 at 17 33 41](https://cloud.githubusercontent.com/assets/373745/9478671/86d5483e-4b4f-11e5-82f4-43fbb423be55.png)

2. Utilizo o AND para combinar com outra coisa (estou provocando o erro): 

![screen shot 2015-08-25 at 17 34 58](https://cloud.githubusercontent.com/assets/373745/9478693/a54f7fe6-4b4f-11e5-8bd4-10c2dfffd297.png)

3. Ao clicar em pesquisar, retorna um msg: 

![screen shot 2015-08-25 at 17 35 57](https://cloud.githubusercontent.com/assets/373745/9478719/c77d7528-4b4f-11e5-8191-1e425ce81b43.png)

4. A partir daí a pesquisa deixa de ser HISTÓRICO + AND + QUALQUER COISA para ser ``#1`` + AND + QUALQUER COISA

![screen shot 2015-08-25 at 17 37 29](https://cloud.githubusercontent.com/assets/373745/9478756/fdaa7fec-4b4f-11e5-8843-b6c90785387c.png)

**Comment by deandr** [comment]
@jamilatta 

Obrigado pela sequência de passos descrita para o problema, mas mesmo assim não consegui identificar o erro.

Quando você indica:
 "A partir daí a pesquisa deixa de ser HISTÓRICO + AND + QUALQUER COISA para ser #1 + AND + QUALQUER COISA"

Na realidade é a mesma coisa pois para o sistema #1 + AND + QUALQUER COISA quando for processado o #1 será trocado por HISTÓRICO 1 + AND + QUALQUER COISA

Desculpe se não entendi corretamente.

[]s

**Comment by jamilatta** [comment]
O resultado final é http://homolog.search.scielo.org/?q=%232+AND+que+coisa+dificil+....&lang=pt&count=10&from=0&output=site&sort=&format=summary&fb=&page=1, implicando em que o comentário **"será trocado por HISTÓRICO 1 + AND + QUALQUER COISA"** não é verdade.

Sugiro, realizar os passos descritos para que possa visualizar o erro.

**Comment by jamilatta** [comment]
O bug descrito não ocorre em todos dos momentos hora funciona hora não funciona.

**Comment by deandr** [comment]
@jamilatta 

Sugiro marcamos uma reunião presencial ou virtual para verificarmos este issue. 

@alexxxmendonca 

Poderia realizar testes adicionais para confirmar este bug? Note que o processo de troca do ```#1``` pela pesquisa do histórico é realizado internamente assim como no pubmed.

[]s

**Comment by jamilatta** [comment]
Por hora, irei remover este ticket da interação 8 para não interromper a entrega.

**Comment by alexxxmendonca** [comment]
Sinceramente não entendi o bug e portanto não sei como reproduzi-lo.

**Comment by jamilatta** [comment]
Existe uma intermitência entre a interface e o controller que implica nesse sintoma, portanto o problema não existe isso é uma consequência, irei fechar esse Bug e irei analisar a comunicação do hosts que hospeda a interface com o host que hospeda o endpoint do controller.
