### ISSUE TITLE
Tradução dos itens do cluster "WoK Áreas Temáticas"

### ISSUE THREAD

**Issue by deandr** [scieloorg/search-journals#170]
@jamilatta 

Notei que a interface não esta mais traduzindo os itens do cluster "WoK Áreas Temáticas" e verifiquei que foi devido a alteração do tipo definido no schema de "string" para "lowercase" conforme https://github.com/scieloorg/search-journals/commit/ceda6d32f87b016dd096c51a048daf453f22d70b#diff-52a8834e30fa29511d993cf10610837bR127 devido a ajustes de processamento.

É necessário adequar os arquivos de tradução para refletir esta alteração alterando os itens para lowercase.  Você poderia realizar este ajuste ou indicar se eu tenho que realizar marcando este issue como "Melhorias"?

Obrigado.

**Comment by deandr** [comment]
:+1:

**Comment by deandr** [comment]
@alexxxmendonca 

Traduções ajustadas e incluído novos termos que não estavam presentes na tabela de tradução anterior. Já disponível no ambiente de homologação.

[]s

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
