### ISSUE TITLE
Adicionar item à lista de ordenação

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#171]
@alexxxmendonca e @deandr 

em conversa com a equipe visualizamos que seria interessante inserir mais dois itens na lista de ordenação do resultado de pesquisa. Os itens seria: 

* Acessos - Mais acessados primeiro
* Acessos - Menos acessados primeiro

Segue imagen para facilitar:

![screen shot 2015-09-25 at 11 10 19](https://cloud.githubusercontent.com/assets/373745/10102709/5768b93e-6376-11e5-8639-0a48b490827d.png)

**Comment by alexxxmendonca** [comment]
Estou totalmente de acordo.

**Comment by jamilatta** [comment]
:+1:
