### ISSUE TITLE
Remoção de serviços do cluster.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/search-journals#173]
Remover engrenagem, os serviços disponíveis nesta engrenagem não têm sentido se não forem aplicados a todos os itens do Cluster.

![screen shot 2015-11-30 at 10 26 52 am](https://cloud.githubusercontent.com/assets/504142/11471463/e0549e98-974c-11e5-9afc-ba1c509157e3.png)

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
