### ISSUE TITLE
Páginas e Elocation

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/search-journals#175]
Priorizar a apresentação do e-location quando houver.
Apresentar página apenas se houver dado.
Quando não houver páginas e e-location a indicação de páginas deve ser suprimida.

Na presença do elocation, a apresentação na interface deve ser:
elocation: e12989128

**Comment by fabiobatalha** [comment]
Incorporado o elemento elocation no XML.

**Comment by deandr** [comment]
@fabiobatalha 

Assim como no issue #176 devemos aguardar o retorno do designer com a nova disposição dos elementos na referência?

[]s

**Comment by fabiobatalha** [comment]
@deandr 

Acredito que podemos assumir que quando existir elocation o mesmo será apresentado no lugar das páginas.

elocation: e19219281

**Comment by deandr** [comment]
:+1:

**Comment by fabiobatalha** [comment]
@deandr 
O que acontece quando não existe nem página e nem elocation?

**Comment by deandr** [comment]
@fabiobatalha 
Não sera apresentado o rótulo para estes campos. A condição esta se existir o elocation apresenta no lugar das páginas, caso não tenha elocation então verifica a presença das páginas. Esta implementado equivocadamente?

**Comment by fabiobatalha** [comment]
@deandr 
A regra de elocation e páginas esta ok, entretanto se também não houver página o template tenta apresentar as páginas.

Deixando algo como:

Páginas: -

**Comment by fabiobatalha** [comment]
Ops @deandr Ignorar meus comentários, esta tudo certo.

**Comment by deandr** [comment]
:+1:

**Comment by alexxxmendonca** [comment]
Alguém sabe algum periódico que possua elocation para poder validar esse ticket?

**Comment by fabiobatalha** [comment]
@alexxxmendonca 

http://homolog.search.scielo.org/?q=S0034-89102015000100602&lang=pt&count=15&from=0&output=site&sort=&format=summary&fb=&page=1

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org

Periódicos verificados: Revista de Saúde Pública, Biota Netropica
