### ISSUE TITLE
DOI no resultado da pesquisa

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/search-journals#176]
Apresentar o número DOI no resultado da pesquisa de cada documento quando estiver disponível. Verificar com Alex e Caramez onde e como o DOI será apresentado.

**Comment by deandr** [comment]
@fabiobatalha 

Estou adicionando a informação do número DOI em uma nova linha abaixo da páginação para poder finalizar este milestone. Quando for informado a posição ideal podemos retomar este issue para eventual ajuste.

**Comment by fabiobatalha** [comment]
Ok.

2015-12-10 14:39 GMT-02:00 deandr <notifications@github.com>:

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
