### ISSUE TITLE
Versões do Documento

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/search-journals#177]
Garantir que todas versões disponíveis sejam apresentadas.

Verificar: http://www.scielo.br/scielo.php?script=sci_issuetoc&pid=0034-891020110003&lng=en&nrm=iso

**Comment by deandr** [comment]
@fabiobatalha 

Entendo que versões disponíveis são os links para resumo, texto e pdf nos diversos idiomas, correto?

@jamilatta 

Caso seja isso mesmo poderia isolar alguns casos da lista e colar o XML referente ao retorno do Solr para estes casos para que seja possível identificar se todas as versões que devem ser apresentadas estão presentes no XML?

[]s

**Comment by fabiobatalha** [comment]
Vinícius,

Um exemplo que esta no ticket já pode ser considerado ponto de partida.

Att,

2015-12-01 17:40 GMT-02:00 deandr <notifications@github.com>:

**Comment by deandr** [comment]
@fabiobatalha 

A idéia é essa mas não tenho acesso ao XML de retorno do Solr para analisar qualquer um dos artigos.

[]s

**Comment by fabiobatalha** [comment]
@deandr 

Não é só colocar output=xml?

**Comment by fabiobatalha** [comment]
@deandr 

neste issue falta apresentar o link para o abstract em ES.

**Comment by deandr** [comment]
@fabiobatalha 

O output=xml me da um subconjunto dos dados filtrados por uma XSL de exportação. Mas já foi suficiente para verificar a questão do abstract. Vou verificar.

[]s

**Comment by deandr** [comment]
@fabiobatalha 

Neste exemplo em especifico o documento não possui no elemento "la" a informação "es" indicando que não existe versão em espanhol.

A regra implementada e confirmada em https://github.com/scieloorg/search-journals/issues/160#issuecomment-134718178 indica a iteração no elemento "la" para apresentar as versões disponíveis de abstract, texto e pdf.

Adicionar este idioma no elemento "la" teria um impacto no cluster de idiomas pois indicaria erroneamente que o artigo possui versão em espanhol quando ele somente tem o resumo em espanhol.

[]s

**Comment by scielo** [comment]
@deandr

Podemos incluir um outro campo com todos os idiomas para não impactar na
contagem de idiomas em texto completo, ou você poderia coletar os dados do
abstract pelos idiomas disponíveis em abstract_[*]


*Fabio Batalha C. Santos*
Colegiado SciELO
www.scielo.org
FAPESP - CNPq - BIREME - FapUNIFESP

2015-12-01 18:16 GMT-02:00 deandr <notifications@github.com>:

**Comment by deandr** [comment]
@fabiobatalha 

Acredito que teremos que seguir pela primeira alternativa com um campo adicional de controle contendo todas as versões de idiomas, pois pela linguagem de template eu não encontrei uma forma de iterar sobre os elementos que começam com certa string, e mesmo que encontrasse o design proposto apresenta primeiramente o idioma e depois os links para resumo, texto e pdf quando os elementos estiverem presentes.

[]s

**Comment by deandr** [comment]
@fabiobatalha 

Outra opção seria manter no config.xml um elemento contendo a lista de opções de idiomas disponíveis na coleção SciELO.org (ex. available_article_languages). Esta solução seria mais simples de implementar, pois não envolveria alteração no processamento, mas é claro tem como ponto negativo a manutenção desta lista ao longo do tempo.

**Comment by scielo** [comment]
Ajustaremos o processamento e incluiremos um field all_languages.

Manteremos o la para referência aos idiomas disponíves texto completo,
podemos renomear de la para fulltext_languages?

*Fabio Batalha C. Santos*
Colegiado SciELO
www.scielo.org
FAPESP - CNPq - BIREME - FapUNIFESP

2015-12-02 9:04 GMT-02:00 deandr <notifications@github.com>:

**Comment by deandr** [comment]
OK. Aguardo a inclusão do elemento e re-indexação para realizar o ajuste no formato das referências.

Sobre renomear o "la" acho melhor neste momento não, pois seria necessário ajustes adicionais em outras partes da interface (arquivos de tradução, etc).

**Comment by jamilatta** [comment]
Somente para melhorar os termos: languages será o utilizando no "futuro" como está previsto no schema: https://github.com/scieloorg/search-journals/blob/beta/solr/schema.xml#L97, ``all_languages`` acredito que é redundante.

Adicionado **available_languages**

Item realizando no commit: https://github.com/scieloorg/search-journals/commit/9a847ce2abf02873a9177f3eae53460e47d7e033

Durante essa madrugada o processamento irá realizar a atualização dos registros com esse novo campo.

ID de uma artigo para conferir: S0011-52581997000300008-scl

**Comment by fabiobatalha** [comment]
@jamilatta 
O XML ainda esta errado. Veja que ele traz o abstract para o dioma PT enquanto esse não existe.

**Comment by fabiobatalha** [comment]
@jamilatta 
Corrigido em #185, por favor validar e reprocessar dados.

**Comment by jamilatta** [comment]
@fabiobatalha 

essa correção não esta relacionado com essa atividade, não entendi o por que essa correção nesse TK!!!!

**Comment by fabiobatalha** [comment]
@jamilatta 
Esta sim Jamil. A descrição do ticket diz: "Garantir que todas versões disponíveis sejam apresentadas."

Esse erro impacta diretamente na apresentação das versões do documento fazendo com que versões sejam apresentadas mesmo quando não existem.

Att

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/

Periódico verificado: Revista de Saúde Pública, Revista Latino-Americana de Enfermagem
