### ISSUE TITLE
Traduções

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/search-journals#179]
As traduções abaixo devem ser verificadas em todo o site:

* Renomear revista para periódico no português;

**Comment by alexxxmendonca** [comment]
O único local que há a informação "Periódico" é no menu dropdown dos índices da busca.

Tem também no cluster de títulos mas este não está disponível em homologação.

@fabiobatalha vou deixar para você fechar esse.

**Comment by fabiobatalha** [comment]
@alexxxmendonca Aparentemente não existem mais termos "revista" no arquivo de traduções, sendo assim, acho que foi tudo removido.

@deandr Existe outro local onde podemos encontrar termos de tradução?

**Comment by deandr** [comment]
@fabiobatalha Não, as traduções ficam somente nos arquivos **texts.ini** divididos por idioma.
