### ISSUE TITLE
Verificar cores de redes sociais

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/search-journals#181]
Verificar com Caramez as cores dos links de compartilhamento, verificar se não seria melhor por questões de design e estética se essas cores deveriam ser diferentes com o objetivo de destacá-las.

**Comment by fabiobatalha** [comment]
@alexxxmendonca  Me parece que este ticket já foi solucionado. Por favor, confirmar.

**Comment by alexxxmendonca** [comment]
Sim, já foi solucionado.
