### ISSUE TITLE
Código XHTML de itálico não está aplicado no título

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#189]
Nos títulos que possuem itálico, está mostrando o código XHTML ao invés da formatação em itálico em si:

Draft genome sequence of a multidrug-resistant **<italic>Acinetobacter baumannii</italic>** ST15 (CC15) isolated from Brazil

http://search.scielo.org/?q=genomic%20data&where=ORG#sthash.WLEb148H.dpuf

**Comment by scielo** [comment]
Este é um erro de metadado que deve ser corrigido na base de dados, o
registro deve ser reprocessado. Não esta relacionado com bugs na ferramenta
de busca.


*Fabio Batalha C. Santos*
Colegiado SciELO
www.scielo.org
FAPESP - CNPq - BIREME - FapUNIFESP

**Comment by fabiobatalha** [comment]
Acompanhar em: https://github.com/scieloorg/PC-Programs/issues/1975
