### ISSUE TITLE
Botão "Compartilhar em outras redes" aponta para o artigo HTML

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#190]
O botão "Compartilhar em outras redes" (ao lado do botão do Delicious) está apontando para o artigo em HTML ao invés de listar a relação de redes sociais.

**Comment by deandr** [comment]
Este comportamento é o observado desde o protótipo inicial desenvolvido pelo designer:

http://scielohomolog.parati.ag/iAHx/resultados.html

[]s

**Comment by fabiobatalha** [comment]
@deandr Você esta certo, se não puder resolver este bug dentro do orçamento, favor comunicar que será solucionado pela nossa equipe.

@alexxxmendonca Dado que o problema esta presente desde o protótipo, por favor, verificar qual será o comportamento ao clicar neste item. Se possível pedir que o designer implemente a parte de interface.

**Comment by deandr** [comment]
@fabiobatalha OK. Quando for definido o comportamento no protótipo favor informar para que eu possa avaliar se é possível ajustar no código existente de forma simples.

**Comment by scielo** [comment]
@deandr OK.

*Fabio Batalha C. Santos*
Colegiado SciELO
www.scielo.org
FAPESP - CNPq - BIREME - FapUNIFESP

2016-01-22 16:50 GMT-02:00 deandr <notifications@github.com>:

**Comment by alexxxmendonca** [comment]
De acordo com o designer, trata-se de uma incompatibilidade no CSS e que talvez seja necessário alterar o HTML. Ele está trabalhando nisso.

Acham que devemos remover o botão enquanto isso?

**Comment by scielo** [comment]
Acho que não é necessário, ao clicar no botão não acorre nada demais, o
usuário é redirecionado para o artigo no SciELO.

*Fabio Batalha C. Santos*
Colegiado SciELO
www.scielo.org
FAPESP - CNPq - BIREME - FapUNIFESP

2016-01-26 15:18 GMT-02:00 alexxxmendonca <notifications@github.com>:

**Comment by alexxxmendonca** [comment]
O designer ajustou o layout para atender esse problema:

http://scielohomolog.parati.ag/iAHx/resultados.html

Para download:
http://review.parati.ag/scielo/SciELO-prototipo-15-12-14.zip

**Comment by deandr** [comment]
@fabiobatalha 

Implementei o código HTML referente a caixa com as outras opções de compartilhamento, porém não consegui ajustar o layout para que a caixa fique na posição correta. 

O último zip para download não contém a caixa de compartilhamento, talvez seja questão de atualizar o css com a última versão disponibilizada pelo designer. De qualquer forma solicito o apoio de vocês para ajustar o layout visto que este item não era um bug.

Obrigado.

**Comment by jamilatta** [comment]
Srs, 

referente a caixa com as outras opções de compartilhamento, atualizei com a última versão que o designer enviou e mesmo assim não funcionou, solicito que verifique esse erro junto com o designer.

Ambiente de homologação atualizado.

**Comment by alexxxmendonca** [comment]
O designer não tem acesso ao ambiente de homologação para poder verificar.

**Comment by jamilatta** [comment]
@alexxxmendonca 

você verificou com o designer?

**Comment by alexxxmendonca** [comment]
No protótipo enviado pelo designer (http://scielohomolog.parati.ag/iAHx/resultados.html) o problema não ocorre, apenas no nosso homolog, do qual o designer não tem acesso para diagnosticar o problema.

Alguma sugestão de como ele pode ter acesso?

**Comment by fabiobatalha** [comment]
Ajustes de CSS podem ser feitos diretamente pelo browser. Ele pode verificar o problema sem acessar o código fonte no servidor.

**Comment by alexxxmendonca** [comment]
Como se ele não tem acesso ao endereço http://homolog.search.scielo.org/?

Essa URL está apenas interna.....

**Comment by jamilatta** [comment]
Confirmei com o Rondineli e a url esta com acesso público. O designer pode acessar e corrigir. 

Atenciosamente, 

Jamil Atta Junior

**Comment by alexxxmendonca** [comment]
O designer disse que não consegue acessar, aparece:

You don't have permission to access / on this server.

**Comment by jamilatta** [comment]
Vou verificar com a infra. 

Atenciosamente, 

Jamil Atta Junior

**Comment by jamilatta** [comment]
Realmente estava sem acesso solicitei para a infra que realiza-se a liberação para que possamos, assim que a infra liberar aviso.

**Comment by alexxxmendonca** [comment]
Alguma novidade sobre isso?

**Comment by jamilatta** [comment]
@alexxxmendonca 

Enviei um e-mail para a infra acho que agora escrito e documentado foi, verifique juntamente ao consultor (Caramez.)

**Comment by alexxxmendonca** [comment]
O designer/consultor (Caramez) conseguiu o acesso e está avaliando a demanda.

**Comment by jamilatta** [comment]
👍
