### ISSUE TITLE
Caracteres exclusivos do XML devem ser restaurados na contrução do HTML.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/search-journals#194]
Caracteres escapados <, >, ", devido ao uso do XML para carga de registros no Solr devem ser reestabelecidos na construção da interface.

http://search.scielo.org/?q=S0074-02762015000500691

**Comment by deandr** [comment]
@fabiobatalha 

Este issue foi ajustado, quando possível validar usando o homolog:

http://homolog.search.scielo.org/?q=S0074-02762015000500691

Obrigado

**Comment by fabiobatalha** [comment]
Testado e Ok.

@alexxxmendonca por favor verificar também.

**Comment by alexxxmendonca** [comment]
Eu tinha visto esse ticket mas não entendi do que se tratava. O que tenho que verificar exatamente?

**Comment by scielo** [comment]
Olhe o link do ticket e verá que o título tem tags HTML <italic>

Veja em homolog, essas tags foram suprimidas da interface.

*Fabio Batalha C. Santos*
Colegiado SciELO
www.scielo.org
FAPESP - CNPq - BIREME - FapUNIFESP

**Comment by alexxxmendonca** [comment]
Ah, sorry, não tinha visto o link!

Se não tiver como deixar em itálico mesmo, ta aprovado.

**Comment by scielo** [comment]
Alex,

O Correto no HTML para apresentar algo em italico é o <i>Blalll</i>

O italic veio provavelmente do XML quando deveria ter sido convertido para
<i>. Esse é um problema no dado que deve ser reportado para verificação no
Converter.

Vou abrir esse ticket lá e encerrar este no Search.

Att,

*Fabio Batalha C. Santos*
Colegiado SciELO
www.scielo.org
FAPESP - CNPq - BIREME - FapUNIFESP
