### ISSUE TITLE
Links da versão mobile quebraram após as atualizações.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/search-journals#195]
http://search.scielo.org/?view=mobile&output=site&lang=pt&from=0&sort=&format=summary&count=15&fb=&page=1&q=Educa%C3%A7%C3%A3o+superior+pol%C3%ADticas+

Link esta sendo construido com um PID errado.

**Comment by deandr** [comment]
@fabiobatalha,

Realizei o ajuste deste erro. Quando possível favor verificar se esta OK usando o homolog:

http://homolog.search.scielo.org/?view=mobile&output=site&lang=pt&from=0&sort=&format=summary&count=15&fb=&page=1&q=Educação+superior+políticas

Obrigado

**Comment by fabiobatalha** [comment]
Verificado, ok

@alexxxmendonca você pode verificar também?

**Comment by alexxxmendonca** [comment]
Testado e aprovado!
