### ISSUE TITLE
Erro ao selecionar todos os itens do cluster.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/search-journals#197]
Request-URI Too Large
The requested URL's length exceeds the capacity limit for this server.
Apache/2.2.24 (Unix) DAV/2 PHP/5.3.27 Server at homolog.search.books.scielo.org Port 80

![screen shot 2016-02-05 at 10 17 50 am](https://cloud.githubusercontent.com/assets/504142/12846129/df65ed28-cbf1-11e5-8343-a85402c98dab.png)

Essas requisições devem ser feitas via POST.

**Comment by alexxxmendonca** [comment]
@fabiobatalha testei aqui e aparentemente foi resolvido. Poderia confirmar por favor?

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
