### ISSUE TITLE
Erro na interface mobile utilizando as últimas páginas.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#198]
Ao clicar nas últimas páginas da interface mobile o **link** para o artigo não funciona e no lugar do **título** aparece um número desconhecido.

![screen shot 2016-02-11 at 10 24 11](https://cloud.githubusercontent.com/assets/373745/12976673/05ef0cbc-d0ad-11e5-872b-6ab20c25ff1e.png)

**Comment by jamilatta** [comment]
O número desconhecido que citei no comentário anterior é o número sequencial dos registro no resultado da busca. Esse número é **desnecessário**.

**Comment by alexxxmendonca** [comment]
Pelo o que eu pude perceber, aparece em mais do que nas últimas duas páginas e todos esses links dão 404 Not Found.

Do que se tratam exatamente?

**Comment by scielo** [comment]
Parece ser documentos sem metadados suficientes.

*Fabio Batalha C. Santos*
Colegiado SciELO
www.scielo.org
FAPESP - CNPq - BIREME - FapUNIFESP

**Comment by alexxxmendonca** [comment]
Testado e aprovado na interface mobile.
