### ISSUE TITLE
Ajustes no formato RIS.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/search-journals#200]
* Trocar ordem do nome do autor apresentando antes o sobrenome e depois o nome.
* Incluir dado de volume (VL)
* Incluir dado de número (IS)

**Comment by patrickhilt** [comment]
O formato tem que ser:
sobrenome vírgula nome(s)
Ex.: 
Ramos, Maurício de Carvalho

**Comment by deandr** [comment]
Prezados,

Sobre a informação do autor atualmente o formato que exporta no formato RIS utiliza o mesmo campo de autor utilizado no formato de apresentação do resultado, ou seja **au**, minha percepção é que esta informação já esta no formato requerido: sobrenome vírgula nome(s), exemplo que acabo de exportar:

T1  - Sobre o trabalho e a formação de agentes de saúde em tempos de zika
AU  - Fonseca, Angélica Ferreira

Esta correto o formato para o elemento autor? Neste caso só faltaria os campos VL e IS?

Obrigado.

**Comment by patrickhilt** [comment]
O autor está correto sim. 
Faltam os campos
VL, IS, DO (DOI)
Se for possível exportar também o título traduzido, seria para o campo 
TT
Também faltam AB (Abstract/Resumo), KW (Palavras chave)
Os ultimos não sirvem para a bibliografia, mas são importantes sim como informação adicional no gerenciador.
Convém exportar toda a informação possível, p.e.
J2  - Alternate Journal (utilizado para o nome abreviado da revista)

A lista completa dos campos RIS para "Journal article":
TY  -	`JOUR`
AB  -	Abstract
AD  -	Author Address
AN  -	Accession Number
AU  -	Author
C1  -	Legal Note
C2  -	PMCID
C6  - 	NIHMSID
C7  - 	Article Number
CA  -	Caption
CN  -	Call Number
DA  -	Date
DB  -	Name of Database
DO  -	DOI
DP  -	Database Provider
ET  -	Epub Date
J2  -	Alternate Journal
KW  -	Keywords
L1  -	File Attachments
L4  -	Figure
LA  -	Language
LB  -	Label
IS  -	Issue
M2  - 	Start Page
M3  -	Type of Article
N1  -	Notes
OP  -	Original Publication
PY  -	Year
RI  -	Reviewed Item
RN  -	Research Notes
RP  -	Reprint Edition
SN  -	ISSN
SP  -	Pages
ST  - 	Short Title
T2  -	Journal
TA  -	Translated Author
TI  -	Title
TT  -	Translated Title
UR  -	URL
VL  -	Volume
C8  -	PubMedId
Y2  -	Access Date

**Comment by patrickhilt** [comment]
Mais uma coisa:
É ruim exportar o título do artigo em LETRAS CAPITAIS, porque impossível transformar de maneira automatizada em formato frase. O contrario (formato frase em letras capitais) é fácil.

**Comment by patrickhilt** [comment]
O formato RIS a partir da página dum artigo é diferente. Aquí tem VL e SN, mas faltam
IS, DO, DB, ID, LA, DA, AB (N2 na lista), KW. Também sería bom incluir os títulos traduzidos em TT.

**Comment by alexxxmendonca** [comment]
Segue abaixo o conteúdo do arquivo exportado após as modificações:

TY  - JOUR
AU  - Nash II, Don
AU  - Mwakalonge, Judith L.
AU  - Perkins, Judy A.
TI  - An investigation of factors influencing performance of Radio Frequency Identification (RFID): applications in transportation
TT  - An investigation of factors influencing performance of Radio Frequency Identification (RFID): applications in transportation
JO  - Journal of Transport Literature
VL  - 10
IS  - 4
DO  - 10.1590/2238-1031.jtl.v10n4a5
DB  - SciELO Brasil
DP  - http://www.scielo.org/
ID  - S2238-10312016000400025-scl
LA  - en
SP  - 25
EP  - 29
DA  - 2016-12
PY  - 2016
AB  - Abstract This study investigates the effect of speed, tag and reader location, vehicle speed, and over-shadowing on RFID performance. The study tested two reader/antenna heights and three tag locations. Three vehicle speeds were tested for each tag location including the simultaneous placement of RFID tags on the vehicle. The study results show, with tags individually placed on the vehicle, the appropriate position for a tag is on the vehicle windshield, and the reader/antenna set at 7ft above the ground on a signpost. Placing multiple tags on the vehicle simultaneously improved the signal strength and detection rates. Vehicle speed had a negative effect on tag detection rate; that is, at higher vehicle speeds the detection rate decreased. With respect to horizontal distance between the reader and the tag, the results show that, the closer the tag and reader are to each other the higher the signal strength and so is the detection rate.
UR  - http://www.scielo.br/scielo.php?script=sci_arttext&pid=S2238-10312016000400025&lang=pt
ER  -

Artigo: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S2238-10312016000400025&lang=pt

Arquivo para download: [export.txt](https://github.com/scieloorg/search-journals/files/366671/export.txt)

@patrickhilt  Poderia por favor validar?

**Comment by patrickhilt** [comment]
@alexxxmendonca 
Está quase perfeito:
TI e TT têm o título do artigo na mesma lingua, seria melhor usar TT só quando se trata duma tradução.

Poderia juntar mais informações?
J2 - J. Transp. Lit. // é o título abreviado da revista
SN - 2238-1031 // ISSN da revista

**Comment by patrickhilt** [comment]
@alexxxmendonca 
Também, se estiver disponível: 
KW - palavra chave 1
KW - palavra chave 2
...

**Comment by deandr** [comment]
@alexxxmendonca 

Foi corrigido a questão do título e adicionado o elemento J2 no formato.

Os demais elementos sugeridos não são possíveis de serem adicionados neste momento pois não fazem parte do processamento. Caso este campos sejam necessários favor criar novos tickets direcionados ao processamento.

[]s

**Comment by alexxxmendonca** [comment]
Segue abaixo o conteúdo do arquivo exportado após as modificações:

TY  - JOUR
AU  - Nash II, Don
AU  - Mwakalonge, Judith L.
AU  - Perkins, Judy A.
TI  - An investigation of factors influencing performance of Radio Frequency Identification (RFID): applications in transportation
JO  - Journal of Transport Literature
J2  - J. Transp. Lit.
VL  - 10
IS  - 4
DO  - 10.1590/2238-1031.jtl.v10n4a5
DB  - SciELO Brasil
DP  - http://www.scielo.org/
ID  - S2238-10312016000400025-scl
LA  - en
SP  - 25
EP  - 29
DA  - 2016-12
PY  - 2016
AB  - Abstract This study investigates the effect of speed, tag and reader location, vehicle speed, and over-shadowing on RFID performance. The study tested two reader/antenna heights and three tag locations. Three vehicle speeds were tested for each tag location including the simultaneous placement of RFID tags on the vehicle. The study results show, with tags individually placed on the vehicle, the appropriate position for a tag is on the vehicle windshield, and the reader/antenna set at 7ft above the ground on a signpost. Placing multiple tags on the vehicle simultaneously improved the signal strength and detection rates. Vehicle speed had a negative effect on tag detection rate; that is, at higher vehicle speeds the detection rate decreased. With respect to horizontal distance between the reader and the tag, the results show that, the closer the tag and reader are to each other the higher the signal strength and so is the detection rate.
UR  - http://www.scielo.br/scielo.php?script=sci_arttext&pid=S2238-10312016000400025&lang=pt
ER  -

TY  - JOUR
AU  - Mendoza-Parra, Sara
TI  - Coverage, universal access and equity in health: a characterization of scientific production in nursing
TT  - Cobertura, acceso y equidad universal en salud, una caracterización de la producción científica de enfermería
TT  - Cobertura, acesso e equidade universal em saúde: uma caracterização da produção científica de enfermagem
JO  - Revista Latino-Americana de Enfermagem
J2  - Rev. Latino-Am. Enfermagem
VL  - 24
IS  - 
DO  - 10.1590/1518-8345.1082.2669
DB  - SciELO Brasil
DP  - http://www.scielo.org/
ID  - S0104-11692016000100301-scl
LA  - en
LA  - pt
LA  - es
SP  - 
EP  - 
DA  - 2016
PY  - 2016
AB  -  Objectives:  to characterize the scientific contribution nursing has made regarding coverage, universal access and equity in health, and to understand this production in terms of subjects and objects of study.  Material and methods:  this was cross-sectional, documentary research; the units of analysis were 97 journals and 410 documents, retrieved from the Web of Science in the category, &quot;nursing&quot;. Descriptors associated to coverage, access and equity in health, and the Mesh thesaurus, were applied. We used bibliometric laws and indicators, and analyzed the most important articles according to amount of citations and collaboration.  Results:  the document retrieval allowed for 25 years of observation of production, an institutional and an international collaboration of 31% and 7%, respectively. The mean number of coauthors per article was 3.5, with a transience rate of 93%. The visibility index was 67.7%, and 24.6% of production was concentrated in four core journals. A review from the nursing category with 286 citations, and a Brazilian author who was the most productive, are issues worth highlighting.  Conclusions:  the nursing collective should strengthen future research on the subject, defining lines and sub-lines of research, increasing internationalization and building it with the joint participation of the academy and nursing community.
AB  -  Objetivos:  caracterizar la contribución científica que ha realizado la enfermería respecto a cobertura, acceso y equidad universal en salud y conocer esta producción en términos de sujetos y fenómenos de estudio.  Material y métodos:  investigación documental y transversal, cuya unidad de análisis fueron 97 revistas y 410 documentos recuperados de la categoría &quot;Nursing&quot; de la Web of Science. De los tesauros DeCS y Mesh, se aplicaron descriptores asociados a cobertura, acceso y equidad en salud. Se utilizaron indicadores y leyes bibliométricas y análisis de artículos más destacados según citas y colaboración.  Resultados:  la recuperación documental permitió observar 25 años de producción, una colaboración institucional e internacional del 31% y 7% respectivamente. La co-autoría promedio fue de 3.5, con un índice de transitoriedad del 93%. El índice de visibilidad fue del 67.7% y 4 revistas núcleo que concentran el 24.6% de la producción. Destaca una revisión de la categoría Nursing con 286 citas y una autora brasilera como la más productiva.  Conclusiones:  el colectivo de enfermería debe fortalecer futuras investigaciones en el tema definiendo líneas y sub-líneas de investigación, aumentar la internacionalización y construirla con la participación conjunta de la academia y la enfermería comunitaria.
AB  -  Objetivos:  caracterizar a contribuição científica pela enfermagem em relação à cobertura, ao acesso e à equidade universal na saúde e conhecer essa produção, em termos de sujeitos e fenômenos de estudo.  Material e Métodos:  pesquisa documental e transversal, cuja unidade de análise foram 97 revistas e 410 documentos recuperados da categoria Nursing do Web of Science. Aplicaram-se descritores dos tesauros DeCS e Mesh, associados à cobertura, ao acesso e à equidade em saúde. Foram utilizados indicadores e regras bibliométricas e análise de artigos mais importantes em termos de citações e colaboração.  Resultados:  a recuperação de documentos permitiu observar 25 anos de produção, uma colaboração institucional e internacional de 31% e 7%, respectivamente. A coautoria média foi de 3,5, com uma taxa de transitoriedade de 93%. O índice de visibilidade foi de 67,7% e 4 revistas-núcleo concentram 24,6% da produção. Destacam-se uma revisão da categoria Nursing, com 286 citações, e uma autora brasileira como a mais produtiva.  Conclusões:  o coletivo de Enfermagem deve reforçar futuras investigações sobre o tema, definindo linhas e sublinhas de pesquisa, ampliar a internacionalização e construí-la com a participação conjunta da academia e da enfermagem comunitária.
UR  - http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0104-11692016000100301&lang=pt
ER  -

Artigo: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S2238-10312016000400025&lang=pt

Arquivo para download: [export.txt](https://github.com/scieloorg/search-journals/files/378639/export.txt)

@patrickhilt você pode validar?

**Comment by alexxxmendonca** [comment]
@patrickhilt por gentileza, poderia validar esse ticket?

**Comment by patrickhilt** [comment]
@alexxxmendonca Desculpe, estava de ferias. 
O resultado é bom. Tem um exemplo com o título traduzido para controlar isso também?
Os demais campos não são necessarios, mais seria bom poder exportar/importar. Onde posso criar os "novos tickets direcionados ao processamento"? (tenho pouca experiencia com o github)

**Comment by alexxxmendonca** [comment]
@patrickhilt tudo bem, obrigado pelo retorno!

Segue um exemplo com título traduzido:

TY  - JOUR
AU  - Alves, Tahiana Meneses
AU  - Rosa, Lúcia Cristina dos Santos
TI  - Usos de substâncias psicoativas por mulheres: a importância de uma perspectiva de gênero
TT  - The Use of Psychoactive Substances by Women: the Importance of a Gender Perspective
JO  - Revista Estudos Feministas
J2  - Rev. Estud. Fem.
VL  - 24
IS  - 2
DO  - 10.1590/1805-9584-2016v24n2p443
DB  - SciELO Brasil
DP  - http://www.scielo.org/
ID  - S0104-026X2016000200443-scl
LA  - pt
SP  - 443
EP  - 462
DA  - 2016-08
PY  - 2016
AB  - Abstract: The objective of this article is to promote, through literature theoretical research, a discussion on women&#039;s use of psychoactive substances. It recognizes the need for an interdisciplinary approach, but invests in socio-cultural aspects of such practices. Gender, as a socio-cultural determinant, is prioritized. Men and women - as different social / cultural actors - retain distinct involvements with the consumption of psychoactive substances. So, this work believes that women are a differentiated segment of users, with particular characteristics and needs that should be considered by public policies. However, women themselves are not a homogeneous group. Therefore, an approach to their psychoactive substance consumption should be fully made, considering their contexts and particularities and based on a perspective of harm reduction.
AB  - Resumo: O objetivo do artigo é promover, através de pesquisa teórica bibliográfica, uma reflexão sobre os usos de substâncias psicoativas por mulheres. Reconhecer a necessidade de uma abordagem interdisciplinar, mas investir nos aspectos socioculturais relativos a tais práticas é o foco. O gênero, enquanto um determinante sociocultural, é priorizado. Homens e mulheres - enquanto diferentes atores sociais/culturais - conservam envolvimentos distintos com o consumo de substâncias psicoativas. Assim, considera que as mulheres constituem um segmento diferenciado de usuárias, com características e necessidades particulares, que devem ser consideradas pelas políticas públicas. As próprias mulheres, porém, não constituem um grupo homogêneo. Portanto, uma abordagem aos seus consumos de substâncias psicoativas deve ser feita integralmente, levando em conta os seus contextos e particularidades, e pautada em uma perspectiva de Redução de Danos.
UR  - http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0104-026X2016000200443&lang=pt
ER  -

Artigo: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0104-026X2016000200443&lang=pt

Arquivo para download: [export.txt](https://github.com/scieloorg/search-journals/files/401548/export.txt)

Você consegue criar tickets? Procure por um botão verde chamado "New Issue", deixe conosco as marcações.

**Comment by patrickhilt** [comment]
@alexxxmendonca É quase perfeito, há uma coisinha: 
O côdigo html em vez do apostrofe ' no resumo do export.txt:
... a discussion on women&#039;s use ...

**Comment by alexxxmendonca** [comment]
@deandr pode ver isso para fecharmos esse ticket e milestone?

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
