### ISSUE TITLE
Erro na exibição do nome do autor no resultado de pesquisa.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#201]
Conforme e-mail, devemos realizar o ajuste na interface do sistema de pesquisa(atenção para o item em negrito): 
```
Prezada Rita,

Estou enviando seu comentário para análise da equipe responsável pelo desenvolvimento do search SciELO.
Por favor, aguarde.

Abraços,
Solange Santos
Colegiado SciELO
FAPESP- CNPq - BIREME- FapUNIFESP
________________________________________
Av. Onze de Junho, 269 - Vila Clementino
04041-050 São Paulo SP - Brasil
Telefone: (55 11) 5083-3639
www.scielo.org | www.scielo.br

Em 07/03/2016 08:25, Rita Lopes (DGEEC) escreveu:
Prezada Solange,
 
**Reparámos que na listagem de artigos aparece o fname seguido de vírgula e depois o surname (Jorge, Walter)
Não deveria ser sem a vírgula?
Exemplo retirado da pesquisa: http://search.scielo.org/?q=laboreal&where=ORG**
 
 
Obrigada,
Rita Lopes
 

 
Av. 24 de Julho, n.º 134
1399-054 Lisboa, PORTUGAL
Tel: +351 213 949 200  Fax: +351 213 957 610
www.dgeec.mec.pt
```

**Reparámos que na listagem de artigos aparece o fname seguido de vírgula e depois o surname (Jorge, Walter)
Não deveria ser sem a vírgula?
Exemplo retirado da pesquisa: http://search.scielo.org/?q=laboreal&where=ORG**

**Comment by patrickhilt** [comment]
Prezados,

 

Seria muito melhor a ordem, „surname, fname“ para saber exatamente quais são os elementos “surname” e quais os “fname”. 

Walter, Jorge

Ramos Carvalho, Elena Maria

 

No caso dos ficheiros RIS é mesmo imprescindível seguir a ordem “Surname vírgula fname”

 

Atte.

Patrick

 


Citavi

Organizar o conhecimento

—————————————

Patrick Hilt

Swiss Academic Software GmbH

Florhofstr. 2, 8820 Wädenswil, Suíça

T  +41 43 888 20 73

F  +41 44 687 14 58

patrick.hilt@citavi.com <mailto:patrick.hilt@citavi.com> 

citavi.com/patrick.hilt
www.citavi.com

 

 

 

 

Von: Jamil Atta Junior [mailto:notifications@github.com] 
Gesendet: Dienstag, 8. März 2016 15:28
An: scieloorg/search-journals <search-journals@noreply.github.com>
Betreff: [search-journals] Erro na exibição do nome do autor no resultado de pesquisa. (#201)

 

Conforme e-mail, devemos realizar o ajuste na interface do sistema de pesquisa(atenção para o item em negrito): 

Prezada Rita,
 
Estou enviando seu comentário para análise da equipe responsável pelo desenvolvimento do search SciELO.
Por favor, aguarde.
 
Abraços,
Solange Santos
Colegiado SciELO
FAPESP- CNPq - BIREME- FapUNIFESP
________________________________________
Av. Onze de Junho, 269 - Vila Clementino
04041-050 São Paulo SP - Brasil
Telefone: (55 11) 5083-3639
www.scielo.org | www.scielo.br
 
Em 07/03/2016 08:25, Rita Lopes (DGEEC) escreveu:
Prezada Solange,
 
**Reparámos que na listagem de artigos aparece o fname seguido de vírgula e depois o surname (Jorge, Walter)
Não deveria ser sem a vírgula?
Exemplo retirado da pesquisa: http://search.scielo.org/?q=laboreal&where=ORG**
 
 
Obrigada,
Rita Lopes
 
 
 
Av. 24 de Julho, n.º 134
1399-054 Lisboa, PORTUGAL
Tel: +351 213 949 200  Fax: +351 213 957 610
www.dgeec.mec.pt

Reparámos que na listagem de artigos aparece o fname seguido de vírgula e depois o surname (Jorge, Walter)
Não deveria ser sem a vírgula?
Exemplo retirado da pesquisa: http://search.scielo.org/?q=laboreal <http://search.scielo.org/?q=laboreal&where=ORG> &where=ORG

**Comment by jamilatta** [comment]
@patrickhilt 

estou consultado nossa bibliotecárias para avaliar as argumentações.

**Comment by javani** [comment]
@jamilatta Os dados são apresentados em nossa inteface de acordo com as regras presentes na AACR2, que obedece a regra de "LastName", "FirstName", contudo teria que ser avaliado o padrão de apresentação de autores nas buscas em bases de dados. Por exemplo, o Pubmed Central, da NLM, apresenta os autores na ordem "FirstName" "LastName".  Já Pubmed/Medline que também é uma base mantida pela NLM, os autores são apresentados na ordem inversa "LastName" "FirstName" (Norma Vancouver), mesma forma apresentada no Web Of Science.

**Comment by patrickhilt** [comment]
O formato como se apresenta numa pagina web é uma coisa, de fato não é tão importante (mas ao leitor ajuda saber exatamente quais elementos são do nome e quais são do sobrenome), mas uma coisa bem diferente é como aparecem os dados num ficheiro de exportação.

Nesse caso a única maneira que permite distingir o “LastName” do “FirstName” é o formato “LastName, Firstname”. 

 

Von: javani [mailto:notifications@github.com] 
Gesendet: Dienstag, 8. März 2016 18:28
An: scieloorg/search-journals <search-journals@noreply.github.com>
Cc: Patrick Hilt <patrick.hilt@citavi.com>
Betreff: Re: [search-journals] Erro na exibição do nome do autor no resultado de pesquisa. (#201)

 

@jamilatta <https://github.com/jamilatta>  Os dados são apresentados em nossa inteface de acordo com as regras presentes na AACR2, que obedece a regra de "LastName", "FirstName", contudo teria que ser avaliado o padrão de apresentação de autores nas buscas em bases de dados. Por exemplo, o Pubmed Central, da NLM, apresenta os autores na ordem "FirstName" "LastName". Já Pubmed/Medline que também é uma base mantida pela NLM, os autores são apresentados na ordem inversa "LastName" "FirstName" (Norma Vancouver), mesma forma apresentada no Web Of Science.

**Comment by jamilatta** [comment]
De acordo com o e-mail enviado pelo Abel e em conversa com a Javani iremos manter o padrão LastName, FirstName para o formato de apresentação dos autores: 

```
Alex, Fabio e Solange

A formatação dos resultados continua apresentando problemas. A apresentação dos nomes dos autores é [sobrenome, nome] e não o contrario --- esse é um erro primário. 

A legenda bibliográfica também tem problema pois se identifica o volume e pages mas número é N. Sugiro availar a volta para a legenda bibliográfica clássica: mes ano, vol(no):pages ou eLocation. 

Quando tem ahead of print atualmente aparece o "N ahead" que não tem sentido. Deve ser "ano:ahead of print" etc.

O ideal é contratarmos um/a bibliotecária/o para ajustar todos os diferentes tipos de registro. Pode ser a Maria Elisa ou mesmo a Eliana

Os clusters continuam simples sem apresentar todas as categorias. Quando se clica o link todas apresenta o mesmo conteúdo. Não é possivel fazer seleção not ou combinar clusters ainda. 

Os índices deveriam ser

Todos os índices ( os que vem abaixo)
Ano de publicação
Autor 
Autor - afiliação
Idioma
Palavras chaves
Palavras do título, resumo e palavras chaves
Palavras do texto completo
Periódico
Periódico - area temática
Sponsor
Título


Abc. Abel
```

**Comment by jamilatta** [comment]
Correção realizada. A correção foi realizado no processamento, estou executando o processamento total dos registros para que possamos visualizar essa correção em todos os registros.
