### ISSUE TITLE
Exportar referências nos formatos BibText

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#202]
Esses formatos não aceitam o RIS

BibText - http://www.bibtex.org/
Medlars - https://www.nlm.nih.gov/bsd/mmshome.html

**Comment by deandr** [comment]
@alexxxmendonca 

Verifiquei que o formato BibText esta disponível na opção "Como citar este artigo" mas estou em dúvida quanto ao Medlars ... este formato é compatível com alguma das opções apresentadas na janela do "Como citar este artigo"? Caso negativo poderia criar um exemplo do formato com os dados de um artigo SciELO para que eu possa criar o formato de exportação?

[]s

**Comment by alexxxmendonca** [comment]
Vamos deixar isso em outro ticket, ok? O formato Medlars parece ser adotado apenas pela National Library of Medicine e não encontrei muita informação a respeito.

**Comment by deandr** [comment]
OK.

**Comment by alexxxmendonca** [comment]
Não consegui testar. A aplicação fica carregando sem resposta e eventualmente pára de responder.

**Comment by deandr** [comment]
Realmente tem um problema com o código. Já corrigi e solicitei nova atualização do ambiente.

**Comment by deandr** [comment]
@alexxxmendonca 

Código atualizado na homologação. Quando possível realizar novo teste de exportação.

[]s

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
