### ISSUE TITLE
O botão ``Mostrar tudo...`` no final de cada cluster não apresenta todos os resultados.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#204]
Ao clicar no link ``Mostrar tudo...``, deveria apresentar uma lista com todas as opções, porém atualmente apresenta a mesma quantidade de itens que é apresentado no cluster.

E-mail enviado pelo Abel em 29/03/2016:

```
Os clusters continuam simples sem apresentar todas as categorias. Quando se clica o link todas apresenta o mesmo conteúdo. 
```

**Comment by alexxxmendonca** [comment]
isso não havia ficado para um segundo momento e não está relacionado com o ticket #184?

**Comment by jamilatta** [comment]
Acredito que não, pois, esta em produção.

**Comment by jamilatta** [comment]
Corrigido com a atualização do último PR.
