### ISSUE TITLE
Combinar cluster e seleção negativa.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#205]
Conforme solicitação do Abel e expectativa não especificada no projeto anterior, segue nova demanda: 

E-mail enviado por Abel em 29/03/2016: 

```
Não é possível fazer seleção not ou combinar clusters ainda.
```

Esse item não havia sido especificado no projeto anterior, portanto é uma nova definição que deve ser especificada com maior detalhamento.

**Comment by alexxxmendonca** [comment]
Em reunião de 30/06, ficou decidido a não necessidade de implantar essa demanda uma vez que é possível fazer esse tipo de filtro através da seleção de todos os itens do cluster e exclusão de itens específicos (ou seja, exceções).
