### ISSUE TITLE
Adicionar novos índices

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#207]
Conforme solicitação do Abel a lista de índices deve ser: 

```
Todos os índices ( os que vem abaixo)
Ano de publicação
Autor 
Autor - afiliação
Idioma
Palavras chaves
Palavras do título, resumo e palavras chaves
Palavras do texto completo
Periódico
Periódico - area temática
Sponsor
Título
```

**Comment by alexxxmendonca** [comment]
Definição dos índices de busca após reunião de 30/06:

--- todos
--- título
--- autor – por palavra e completo
--- país – afiliação do autor
--- palavras-chave
--- área temática (grande área, área WoS e seção sumário) – por palavras e frases
--- assunto (palavras do título + palavras do resumo + palavras-chave + áreas temáticas palavras + áreas temáticas completas)

--- idioma
--- periódico -titulo (curto e longo, palavras e completo)
--- número periódico ano de publicação
--- número periódico volume (usar ano quando não tiver volume)
--- financiador
--- outros ...

**Comment by fabiobatalha** [comment]
Indice de texto completo não será possível no momento. Como é sabido pelos envolvidos, o SciELO armazena textos completos em file system e não em bases de dados, desenvolvimentos devem ser feitos em todo o stack de produtos SciELO para permitir a indexação/busca pelo texto completo.

Não existe previsão para solução de busca por texto completo.

**Comment by alexxxmendonca** [comment]
@deandr 

O que falta para fecharmos esse ticket?

**Comment by deandr** [comment]
@alexxxmendonca 

Fiz uma revisão nos índices existentens e adicionei na lista as opções de busca por assunto e palavras-chave.

Temos que aguardar a aplicação deste último pull request e re-processamento da coleção para avaliarmos se esta OK para o fechamento deste ticket.

[]s

**Comment by deandr** [comment]
@alexxxmendonca 

Mesmo o processo de reindexação ainda em execução já é possível validar que os índices de assunto e palavras-chave estão criados e é possível realizar as devidas recuperações.

Favor, quando possível validar.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/ 

Feito busca por palavras-chave e assunto.
