### ISSUE TITLE
Processamento de contagem de acesso e citação 

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#209]
Após ajustes realizados no processamento do sistema de indexação a contagem de citação e acesso não estão sendo registrados.

Como consequência atualmente não contamos com esses dados no sistema de pesquisa. Ao utilizamos a opção *_Ordenar por citações ou acessos *_ os registros retornam sem o dado de citação ou acesso.

![screen shot 2016-03-30 at 14 10 42](https://cloud.githubusercontent.com/assets/373745/14150807/40d45b30-f681-11e5-9c8d-223e66b5c057.png)
- Apenas alguns registros que não receberam modificações nos últimos processamentos constam com registros de citação e acesso, mas repare que são poucos.

**Comment by alexxxmendonca** [comment]
Enquanto esse problema não for resolvido, desabilitar essa opção na interface.

**Comment by alexxxmendonca** [comment]
Esse ticket depende de processamento para ser resolvido?

**Comment by alexxxmendonca** [comment]
Quantidade de acessos já disponível em produção e sendo carregado em homologação.

Sobre a quantidade de citações, só pode ser exibido se o número for diferente de 0.

**Comment by fabiobatalha** [comment]
@alexxxmendonca @viniciusandrade 

O Processamento já esta ok. A questão de apresentar somente citações quando o valor for maior que 0 é um ajuste de interface.

Vou encerrar este ticket que trata somente o processamento.
