### ISSUE TITLE
Definição dos clusters

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#214]
--- coleção -- **já possui**
--- país afiliação autor
--- área temática SciELO -- **já possui**
--- índice WoS -- **já possui**
--- área temática WoS -- **já possui**
--- [área temática Scopus] **(definir)**
--- periódico – nome completo -- **já possui**
--- idioma(s) artigo -- **já possui**
--- ano de publicação -- **já possui**
--- citáveis e não citáveis
--- tipo de documento

**Comment by alexxxmendonca** [comment]
Desconsiderar [área temática Scopus], que ainda precisa de definição.

Incluir novos clusters:

--- país afiliação autor
--- índice WoS
--- citáveis e não citáveis
--- tipo de documento

**Comment by deandr** [comment]
@alexxxmendonca 

Poderia dar maiores informações sobre os clusters "índice Wos" e "citáveis e não citáveis".  Se conseguir informar por exemplo se estes campos já existem nos metadados do artigo ou são provenientes de recursos externos e também puder colocar alguns exemplos de valores dos mesmos.

**Comment by fabiobatalha** [comment]
@deandr 

-- país de afiliação
Não esta no XML, e será um problema apresentar pois este dado não é normalizado. Mas iremos incluir no processamento.

-- índices WoS
Já esta disponível, inclusive ja esta na interface da ferramenta

-- citáveis e não citáveis
Não esta disponível, vamos incluir no processamento

-- tipo de documento
Já esta disponível sob atributo **type**

**Comment by deandr** [comment]
@fabiobatalha 

OK. Criei tickets separados com marca de processamento para os campos "pais de afiliação do autor" e "citáveis e não citáveis".

Obrigado

**Comment by deandr** [comment]
@fabiobatalha 

Gostaria de solicitar um ajuste para o cluster "citáveis e não citáveis". Na forma como ele foi implementado esta sendo indexando os valores True e False, infelizmente a tradução dos valores na interface utiliza um arquivo INI onde não é possível informar como chave valores booleanos. Desta forma não consiguirei traduzir esta informação nos 3 idiomas.

Seria possível alterar para, por exemplo, "citable_true" e "citable_false" como valores para este elemento, ou qualquer outro valor que não seja interpretado como booleano?

Obrigado

**Comment by deandr** [comment]
Pessoal,

Você teria a tabela de tradução para português e espanhol dos tipos de artigos disponíveis no elemento **type** do XML?
Os tipos em inglês podem ser visualizados no ambiente de homologação após o filtro **SciELO Áreas Temáticas".

Obrigado

**Comment by alexxxmendonca** [comment]
@deandr 

O que falta para fecharmos esse ticket?

**Comment by deandr** [comment]
@alexxxmendonca 

Acredito que este ticket esta OK, uma vez que foram adicionados os filtros de **citáveis e não citáveis** e **tipo de documento** e vimos que o filtro por país de afiliação do autor não é possível pois o mesmo não esta normalizado.

**Comment by alexxxmendonca** [comment]
@deandr 

De acordo. O de país está relacionado com o #325 

Vou fechar esse ticket.
