### ISSUE TITLE
Links para autores

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#220]
Estudar definição de para onde apontar os links dos nomes dos autores nos resultados de busca – Google pode ser o melhor pensando no contexto Rede SciELO.

ORCID também deve ser considerado.

**Comment by alexxxmendonca** [comment]
Após reunião em 04/07/2016, ficou definido que quando o autor possuir ORCID e CV Lattes, serão dadas as duas opções (ao clicar no nome do autor).

A integração com o ORCID requer desenvolvimento, portanto, enquanto essa integração não for concluída, mostra-se apenas o CV Lattes do autor, quando houver, e quando não houver, busca no Google em uma nova janela.

Resumindo:

Apenas ORCID -> Link para perfil ORCID
Apenas CV Lattes -> Link para perfil Lattes
ORCID e CV Lattes -> Janela com as duas opções
Nenhum -> Link para Google.

**Comment by deandr** [comment]
Prezados,

Pela parte: 

"A integração com o ORCID requer desenvolvimento, portanto, enquanto essa integração não for concluída, mostra-se apenas o CV Lattes do autor, quando houver, e quando não houver, busca no Google em uma nova janela."

Entendo que o identificador do CV Lattes do autor já estaria disponível, correto? Este metadado já esta disponível na API de metadados? 

[]s

**Comment by fabiobatalha** [comment]
@deandr

Esse metadado não esta disponível, ainda não temos uma solução para esse
demanda.

**Comment by deandr** [comment]
@fabiobatalha 

Obrigado.

@alexxxmendonca,

Sugiro dividir este issue criando um issue para cada um destes indicadores.

No caso atual não temos nenhum indicador disponível, alteramos o link do autor para uma busca no Google? Google geral ou Scholar?

[]s

**Comment by alexxxmendonca** [comment]
@deandr 

Google geral.

Esse ticket fica sendo como incluir link para o Google. Vou abrir outros 2 para o ORCID e CV Lattes.

**Comment by deandr** [comment]
@alexxxmendonca 

OK. Obrigado.

Att.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
