### ISSUE TITLE
Quadro informativo para título do periódico

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#221]
Nos resultados de busca, ao passar o mouse em cima (?) do título, exibir dados resumidos do periódico:

título, ISSNs, Publicador, Google Metrics (H5,M5),  Scopus (IPP, SNIP, JCR), JCR (IF-2,IF-3)

Definir melhor esse comportamento.

**Comment by alexxxmendonca** [comment]
E-mail do Abel:

"Até o fim do ano quando o catálogo de periódicos estiver pronto (cc Ednilson e Solange) vamos abrir uma janela com dados institucionais e de impacto por citações, Altmetrics e downloads atualizado semanalmente de cada periódico nas diferentes bases.

O Link vai apontar para o Analytics. Inicialmente vamos dar destaque ao GS H5. Este é um compromisso que temos com o pessoal do Google Scholar."

**Comment by alexxxmendonca** [comment]
Comportamento atualizado:

Nos resultados de busca, ao clicar no título do periódico, exibir dados resumidos do periódico:

Título
ISSNs
Publicador
Google Metrics: H5M5 (do último ano, sendo os índices links para o Google Metrics do periódico).
Mais (sendo esse um link para a página do periódico no SciELO Analytics).

Se o periódico não tiver H5M5, não mostrar os dados do Google Metrics.

**Comment by alexxxmendonca** [comment]
@deandr 

Vamos precisar do designer para esse ticket?

**Comment by deandr** [comment]
@alexxxmendonca 

Será necessário primeiro o desenvolvimento de um serviço que responda por estes dados.

**Comment by alexxxmendonca** [comment]
@fabiobatalha 

Você consegue fornecer esses dados ao Vinicius em quanto tempo?

**Comment by fabiobatalha** [comment]
@viniciusandrade 

O Analytics já entrega esses dados.

http://analytics.scielo.org/ajx/bibliometrics/journal/google_h5m5_chart?journal=0102-8650

**Comment by fabiobatalha** [comment]
Scopus e JCR não possuem API's e tampouco temos esses indicadores.

**Comment by alexxxmendonca** [comment]
Scopus e JCR estão desconsiderados nesse primeiro momento.

É válido apenas https://github.com/scieloorg/search-journals/issues/221#issuecomment-251378826

O primeiro ticket ficou por motivos de histórico.

**Comment by deandr** [comment]
@fabiobatalha 

OK. Como eu não conheço sobre esta informação poderia me explicar melhor o que  significa o trecho 
H5M5 (do último ano, sendo os índices links para o Google Metrics do periódico).

Ou seja, dado este exemplo de chamada que você passou quais são os dados que preciso apresentar?  Seria sempre a última ocorrência do options.series.data?

Das outras informações solicitadas:
Título
ISSNs
Publicador

Entendo que o título seria o elemento **journal_title** e ISSN o elemento **issn**, desta forma já estão contemplados na indexação, certo? E o **Publicador**?

**Comment by scielo** [comment]
Publisher será incluído se não existir. Considerar que publisher é um dado
repetitivo.

Incluiremos na tag publisher

*Fabio Batalha C. Santos*
Lider de Tecnologia
www.scielo.org
FAPESP - CNPq - BIREME - FapUNIFESP

2016-10-04 10:23 GMT-03:00 deandr <notifications@github.com>:

**Comment by deandr** [comment]
@alexxxmendonca 

Versão inicial do quadro de informaçõe sobre o periódico implementado e disponível em homologação.

A informação do publicador ainda não esta disponível para apresentação pois depende do processamento.

**Comment by alexxxmendonca** [comment]
Quando o periódico não é da Coleção SciELO Brasil, o link para o Analytics aponta para a Coleção SciELO Brasil e como o ISSN não existe nessa Coleção, fica carregando _ad eternum_.

**Comment by deandr** [comment]
@fabiobatalha,

No código atual só estou passando o parâmetro journal= para a chamada ao analytics. Poderia me informar qual outro parâmetro obrigatório/recomendável para evitar o problema informado pelo Alex?

**Comment by deandr** [comment]
@fabiobatalha 

Adicionei o parâmetro **collection** na chamada ao analytics. Esta disponível no último PR, quando possível favor aplicar o patch.

Obrigado

**Comment by deandr** [comment]
@alexxxmendonca 

Homologação atualizada com o ajuste do parâmetro de coleção ao chamar o Analytics. Quando possível favor limpar o cache e realizar novo teste.

[]s

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
