### ISSUE TITLE
Altmetrics no resultado de busca

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#222]
Exibir índice do altmetrics para os resultados de busca, semelhante a:

![image](https://cloud.githubusercontent.com/assets/4059679/16522864/aaac197e-3f76-11e6-89d1-7744dfdf97c1.png)

https://www.scienceopen.com/search?1&f=collection_filter$@%7C3f2fc474-1b89-4787-a968-69184d0cc2f9&q=*&type=Content

**Comment by deandr** [comment]
@fabiobatalha 

Saberia me informar se este indicador esta disponível nos processamentos já existentes da SciELO e em caso afirmativo poderia ser adicionado na API de metadados XML e ser incluído no índice de pesquisa para uso na interface?

[]s

**Comment by fabiobatalha** [comment]
@deandr

Essa implantação deve ser feita utilizando um componente do altmetrics
apenas para os documentos com DOI.

https://www.altmetric.com/products/altmetric-badges/

Att,

2016-07-14 10:40 GMT-03:00 deandr <notifications@github.com>:

**Comment by deandr** [comment]
@fabiobatalha 

OK. Obrigado. Vou verificar.

[]s

**Comment by deandr** [comment]
@fabiobatalha 

Desculpe mas pelo que entendi o produto (altimetrics badges) em questão possui custo de uso:

"Pricing for the Altmetric Badges is based on the volume of published content and the number of titles (if applicable), discounts accumulating."

A SciELO já possui um ID para a utilização deste produto?

**Comment by deandr** [comment]
@fabiobatalha 

Verifiquei que nas página dos artigos o altimetrics já esta incorporado. Vou adicionar o mesmo código de JS e DIV na pesquisa para ver se funciona.

[]s

**Comment by fabiobatalha** [comment]
Achei que o icone do altmetrics ficou meio jogado na referência. Não seria melhor colocar ao lado de downlods e citações recebidas?

![screen shot 2016-07-15 at 12 23 26 pm](https://cloud.githubusercontent.com/assets/504142/16879460/078cdeec-4a87-11e6-97f2-43060ee5b868.png)

**Comment by deandr** [comment]
Era para ficar ao lado do ícone de compartilhar conforme meu ambiente local:

![screenshot from 2016-07-15 12 33 26](https://cloud.githubusercontent.com/assets/5338655/16879761/6976f628-4a88-11e6-8bbb-3b5f6b3953df.png)

Aparentemente preciso ajustar a CSS. Mas aguardo para verificar se é melhor ao lado do ícone de compartilhar ou na linha onde se encontra o DOI e os downloads.

**Comment by alexxxmendonca** [comment]
Sugiro colocar na mesma linha onde se encontra o DOI e downloads.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/

Talvez a posição altere depois que os dados de download e citação forem inseridos, mas vou considerar como atividade feita.

**Comment by alexxxmendonca** [comment]
Segundo Abel:

_Está feio e tem muito destaque  e a maioria é zero. Sugiro retirar por agora, discutirmos como publicar e publicar quando tivermos os links dos downloads. Quando o resultado é zero não colocamos._  

Desabilitar por ora. Vou deixar em discussão.

**Comment by alexxxmendonca** [comment]
@paratiuid retomando esse ticket, em anexo está um PPT com diretrizes para inserção do badge do ScienceOpen

[ScienceOpen Metrics Badge_171204.pptx](https://github.com/scieloorg/search-journals/files/2572564/ScienceOpen.Metrics.Badge_171204.pptx)

Ele deve ser inserido no dropdown de métricas do artigo, nos resultados de busca,

**Comment by alexxxmendonca** [comment]
@paratiuid essa foi a resposta que obtive do pessoal do ScienceOpen:

As I see on your page:

 

https://search.scielo.org/?q=&lang=pt&count=15&from=0&output=site&sort=&format=summary&fb=&page=1&q=sauda&lang=pt&page=1

 

you have the next tagging for the metric table:

 

```
<ul class="metricTable">

                <li>

                                <a target="_blank" href="https://analytics.scielo.org/w/accesses?document=S0121-07932017000100021&amp;collection=col">

                                                <div class="logo-statistc logo-statistc-scielo"></div>

                                </a>

                </li>

                <li>

                                <a target="_blank" href="https://analytics.scielo.org/w/accesses?document=S0121-07932017000100021&amp;collection=col">

                                                SciELO Analytics

                                </a>

                </li>

</ul>
```


You have 2 separate links in that dialog for each metric, one for the icon and the other for the name. Our current implementation calculates the link to ScienceOpen on the fly and displays the icon only if ScienceOpen has the article (avoiding clicking on broken links). If we want to add ScienceOpen into your metric dialog, we need to create a special JS for SciELO, which generates your `<ul class="metricTable">` element with the ScienceOpen links.

 
You original HTML page:

`<ul class=" metricTable  so-badge" data-badge-type="5" data-id-type= "scielo-sza" data-id="S0038-23532016000400001"></ul>`

 

The page when the JS found the article on ScienceOpen:

```
<ul class="metricTable">

                <li>

                                <a target="_blank" href="https://www.scienceopen.com/document?vid=e38327b9-92c8-4736-ac1a-6295069c4b57">

                                                <img src="https://www.scienceopen.com/content/badge/badge-5.svg?_=d22ffc52-c32c-5c97-484e-0b84b497c307" alt="ScienceOpen "/>

                               </a>

 

                </li>

                <li>

                                <a target="_blank" href="https://www.scienceopen.com/document?vid=e38327b9-92c8-4736-ac1a-6295069c4b57">

                                                ScienceOpen Metrics

                                </a>

                </li>

</ul>
```

What do you think?

**Comment by cesarbruschetta** [comment]
Branch com pullrequest fechado 
https://github.com/scieloorg/search-journals/tree/paratiuid-tk222

**Comment by gustavofonseca** [comment]
A equipe do ScienceOpen retomou o contato hoje (12/04/2019), em uma mensagem que diz que o badge que estava pendente foi desenvolvido e que exemplos podem ser encontrados no arquivo anexo.

[badge.html.zip](https://github.com/scieloorg/search-journals/files/3074509/badge.html.zip)

**Comment by alexxxmendonca** [comment]
Fechando este ticket pois atualmente o índice Altmetrics está disponível dentro do menu de métricas.
