### ISSUE TITLE
Ícone de acesso aberto

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#223]
Inserir ícone de acesso aberto nos resultados de busca, semelhante a:

![image](https://cloud.githubusercontent.com/assets/4059679/16523202/8440800c-3f78-11e6-9321-6bbbfe686379.png)

Ao passar o mouse em cima (?), exibir a atribuição da licença Creative Commons utilizada.

Definir melhor posicionamento do ícone e comportamento.

**Comment by alexxxmendonca** [comment]
Após reunião em 04/07/2016, ficou definido que o ícone deve ser inserido ao lado esquerdo do título do artigo e ao passar o mouse em cima, deve-se exibir a atribuição da licença Creative Commons utilizada.

**Comment by patrickhilt** [comment]
Possivelmente também exportar o enlace para o pdf no formato RIS, pois assim se pode diretamente descarregar o pdf com o dados bibliográficos.

**Comment by deandr** [comment]
Para que seja possível ao passar o mouse exibir a atribuição da licença utilizada será necessário adicionar esta informação nos metadados de indexação do artigo para ser utilizada pela interface.

**Comment by fabiobatalha** [comment]
@deandr 

Ok, implementar regra considerando que a informação estará sobre o atributo use_license

**Comment by deandr** [comment]
:+1:

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
