### ISSUE TITLE
Seleção de opções dos clusters

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#224]
A seleção dos clusters deve ter comportamento semelhante ao do filtro do Excel, ou seja:

- permitir selecionar todos os itens (mesmo aqueles que não aparecem no cluster e apenas na janela "mostrar todos")
- ao clicar/des-clicar, o comportamento deve ser: selecionar todos/des-selecionar todos (considerar todo o cluster e não apenas aqueles mostrados para o usuário).
- por padrão, as opções devem vir já selecionadas (atualmente essas opções vêm des-selecionadas), e o usuário escolhe aqueles que ele não quer mostrar.

**Comment by deandr** [comment]
@alexxxmendonca,

Sobre os itens deste ticket:

1. A criação da janela "listar todos" foi justamente pela inviabilidade técnica de realizar operações sobre todos os itens, portanto este item não podem ser implementados conforme já haviamos discutido no passado.

2. A opção de selecionar todos/des-selecionar todos só esta disponível na janela de "listar todos" e possui o comportamento descrito. Uma vez que não existe esta opção na lista do resultado e também não pode ser implementada devido ao problema já descrito no item 1. 

3. Devemos apresentar os itens da janela "listar todos" marcados quando a janela é apresentada?

[]s

**Comment by alexxxmendonca** [comment]
Ok em relação aos itens 1 e 2.

Sobre o item 3, o comportamento deve ser o seguinte:

A janela deverá vir com todos os itens des-selecionados, ou seja, como está agora.

Entretanto, ao selecionar um ou mais itens, a visualização dos resultados ou download deve ser apenas dos itens selecionados, portanto, a princípio os links "Visualizar resultados" e "Download dos resultados" devem começar desativados (sem link) -- pois não há clusters selecionados.

Deve ser inserido um novo link, acima dos links "Visualizar resultados" e "Download dos resultados", chamado "Aplicar seleção" (ou algo do tipo). Após clicar nesse link e quando houver uma ou mais seleção, os links devem ser ativados.

Renomear os links para "Visualizar resultados selecionados" e "Download dos resultados selecionados".

Isso é para manter os resultados e downloads contextualizados com a escolha do usuário.

**Comment by deandr** [comment]
Alex,

O mecanismo proposto de habilitar/desabilitar os botões de acordo com a marcação de algum item na lista de resultados é complicado de se implementar levando em consideração que todo o código original da interface foi desenvolvido pelo programador front-end.

Implementei uma mensagem que indica ao usuário que é necessário a seleção de um ou mais resultados. Por favor verifique se esta de acordo, caso contrário seria necessário envolver o programador front-end para ajustar o comportamento.

[]s

**Comment by alexxxmendonca** [comment]
Vinicius,

A solução proposta me parece ótima e creio que atende às nossas necessidades. Só sugiro um pequeno ajuste:

Exibir a mensagem quando não há seleção ativa: OK. Entretanto, quando é feito uma seleção e um dos dois links é clicado ("Visualizar resultados selecionados" ou "Download dos resultados selecionados"), a mensagem "Selecione um ou mais resultados" continua aparecendo.

Teria como apagar a mensagem depois que o usuário fez a seleção?

Ou outras palavras, exibir a mensagem somente enquanto não houver seleções ativas.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
