### ISSUE TITLE
Redimensionar largura da barra de clusters

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#228]
Permitir que o usuário possa redimensionar a largura da barra lateral de clusters para poder visualizar os títulos completos dos periódicos.

Será necessário envolver o designer nisso.

**Comment by caramez** [comment]
Pessoal, não é impossível de fazer. Porém é necessário refazer boa parte do layout, pois as colunas do resultados começam na parte superior da página. E, para redimensioná-los ao gosto do usuário seria necessária uma adaptação automática desta coluna que começa lá em cima.

A parte que tem as funcionalidades "Selecionar esta página" que flutua conforme a rolagem se tornaria bem complexa ao habilitar este tipo de navegação.

Vocês querem tocar em frente ou vamos reestruturar toda esta parte do layout?

**Comment by alexxxmendonca** [comment]
Devido às complicações justificadas pelo designer, essa demanda não será aplicada por ora.
