### ISSUE TITLE
Mostrar título completo dos periódicos nos clusters

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#229]
Não mostrar título abreviado, mostrar título completo dos periódicos.

![image](https://cloud.githubusercontent.com/assets/4059679/16567937/b6f14ef8-41fa-11e6-978f-741873402a24.png)

**Comment by deandr** [comment]
@alexxxmendonca 

Pelo último comentário do ticket #315, podemos assumir que este o filtro de períodicos passará a exibir o título completo da revista, correto?

E quando o título for muito longo será apresentado truncado com reticências e o título sem truncar será apresentado caso o usuário passe o mouse por cima do título, confere?

Obrigado

**Comment by alexxxmendonca** [comment]
Os títulos ficam da forma como estão, ou seja, truncados. Entretanto ao passar o mouse em cima, deve aparecer um tooltip com o título completo do periódico, mesmo para aqueles que não estão truncados.

**Comment by deandr** [comment]
Infelizmente isso não é possível de ser implementado. 

O título da revista já precisaria estar disponível no filtro no formato completo, ao se utilizar o título abreviado no filtro não existe forma de "buscar" o título completo uma vez que não estamos no escopo do artigo e sim no escopo do filtro.

**Comment by alexxxmendonca** [comment]
Tem como mostrar o título completo no cluster? Mesmo que fique cortado.

**Comment by deandr** [comment]
Sim, eu faria os ajustes de configuração e solicitaria a reindexação de toda a coleção alterando o campo de filtro para usar o título completo da revista e não mais o título abreviado.

Com isso na interface podemos mostrar o título completo até o limite da largura da coluna de filtros e adicionariamos o "..." para truncar.

**Comment by alexxxmendonca** [comment]
Sim, faça isso então. Vamos ver como fica e depois decidimos se manteremos assim ou revertemos para como estava antes.

**Comment by deandr** [comment]
:+1:

**Comment by alexxxmendonca** [comment]
Com a solução adotada no ticket #315, mais o fato do título do periódico aparecer por completo na janela modal, creio que podemos fechar esse ticket.
