### ISSUE TITLE
Alterar link "listar todos" por ícone da engrenagem

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#230]
Alterar link "listar todos" por ícone da engrenagem, como era anteriormente:

![image](https://cloud.githubusercontent.com/assets/4059679/16568403/36ccde26-4200-11e6-9e99-522e2bbeff5f.png)

O comportamento será o mesmo: abre janela para mostrar todos os itens do cluster, download e visualização dos resultados.

**Comment by deandr** [comment]
@alexxxmendonca 

Lembrando que o motivo por atualmente o sistema apresentar o link "Listar todos" era devido a impossibilidade técnica de resolver a questão da classificação, visualização em gráfico e download dos resultados totais do cluster ficando estas opções restritas aos itens do filtro disponíveis no resultado. 

Ao retornarmos a janela esta ciente de que este comportamento também voltará, correto? Ou seja os resultados completos do cluster, bem como Download e Visualização somente se o usuário clicar no item "Selecionar" da janela,  ok?

[]s

**Comment by alexxxmendonca** [comment]
@deandr 

Na verdade, apenas o ícone deve ser substituído e nada mais. Todo o comportamento atual permanece o mesmo.

Alterar "listar todos" pelo ícone da engrenagem.

Download e visualização devem estar disponíveis apenas na janela modal que aparece com todos os clusters, permitindo assim o download de todos os clusters.

**Comment by deandr** [comment]
@alexxxmendonca 

OK. Obrigado.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
