### ISSUE TITLE
Link ePDF nos resultados

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#231]
Inserir link para ePDF (ReadCube) nos resultados de busca.

**Comment by deandr** [comment]
@fabiobatalha,

Identifiquei o seguinte exemplo de chamada para o ePDF (ReadCube):

http://www.scielo.br/readcube/epdf.php?doi=10.5935/abc.20160060&pid=S0066-782X2016000600457&pdf_path=abc/v106n6/0066-782X-abc-20160060.pdf&lang=en

Retirei da chamada o parâmetro do **pdf_path**, pois já sei que não tenho esta informação atualmente no índice Solr e ainda consegui o acesso ao PDF com a URL:

http://www.scielo.br/readcube/epdf.php?doi=10.5935/abc.20160069&pid=S0066-782X2016000600464&lang=en

Ao retirar o DOI não consegui mais o acesso ao documento.

Pergunta: Posso assumir como parâmetros minímos para a chamada ao ReadCube o DOI e o PID do documento?

[]s

**Comment by fabiobatalha** [comment]
@alexxxmendonca 

O pdf_path é importante pois faz parte do processo de inclusão de pdfs na base de dados do ReadCube.

Quando o PDF ainda não foi carregado na base de dados do ReadCube, eles usam o pdf_path para carregar esse pdf, se o parâmetro pdf_path não estiver presente o ReadCube não conseguirá apresentar o PDF enriquecido gerando incosistência no comportamento do link ePDF.

O pdf_path esta presente no indice solr no atributo fulltext_pdf_* onde * igual idioma.

Os links devem ser montados corretamente para cada idioma existente para evitar inconsistências na caga de PDF's na base de dados do ReadCube.

**Comment by deandr** [comment]
@fabiobatalha 

Perfeito, obrigado pelos esclarecimentos. 

Vou trabalhar na implementação do link na interface.

**Comment by fabiobatalha** [comment]
@alexxxmendonca 

Outro ponto importante.

O ePDF é um serviço pago disponível para os documentos do SciELO Brasil, não acho interessante ter um serviço que funcione apenas para uma coleção na ferramenta de busca, mas se implementado isso deve ser levado em consideração.

**Comment by deandr** [comment]
Devo restringir a apresentação do link para o ePDF somente para documentos da coleção SciELO Brasil?

**Comment by fabiobatalha** [comment]
Deixo essa decisão para os experts em interface e user experience.

**Comment by deandr** [comment]
@fabiobatalha 

OK de acordo, mas atualmente existe esta restrição certo? Ou seja se eu passar para o ReadCube um documento de uma coleção diferente da Brasil ele irá conseguir carregar e apresentar o PDF?

[]s

**Comment by patrickhilt** [comment]
Seria bom ter o enlace para o PDF também no RIS para poder baixar automaticamente no gerenciador (não é o ePDF).
Formato:
L1  - Enlace.pdf

**Comment by fabiobatalha** [comment]
@deandr 

Nunca fizemos isso, então não sei qual será o comportamento. Mas sei que se eles carregarem isso na base de documentos poderemos ter uma surpresa nos custos de manutenção do serviço. Então este deve sem implantado apenas para documentos do SciELO Brasil.

**Comment by fabiobatalha** [comment]
@patrickhilt

Sim, o link do PDF pode ser incluído no RIS, isso deve ser sugerido no ticket do formato RIS, ou em um novo ticket caso o do RIS tenha sido encerrado.

**Comment by deandr** [comment]
@fabiobatalha 

OK, implementamos nesta primeira etapa para documentos do SciELO Brasil e aguardamos autorização para incluir o link para as outras coleções.

[]s

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
