### ISSUE TITLE
Link para ORCID profile

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#240]
Nos resultados de busca, ao clicar no nome do autor, deve apontar para o seu perfil no ORCID (quando houver).

Esse ticket está relacionado com o #220

**Comment by fabiobatalha** [comment]
A inclusão deste dado esta relacionada a reformulações em todo o stack de aplicações do SciELO. Não temos previsão para implementação desta atividade no search.scielo.org.

**Comment by alexxxmendonca** [comment]
Correção: para os autores que possuem ORCID informado, exibir o ícone do ORCID ao lado do nome com um link apontando para o respectivo ORCID iD do(a) autor(a).

**Comment by alexxxmendonca** [comment]
Aplicado em produção.

**Comment by alexxxmendonca** [comment]
Quando não há ORCID, o ícone ORCID aparece e aponta para https://orcid.org/

Exemplos:
https://search.scielo.org/?fb=&q=*&lang=pt&count=15&from=1&output=site&sort=&format=summary&page=1&where=&filter%5Bin%5D%5B%5D=mex&filter%5Bin%5D%5B%5D=chl&filter%5Bin%5D%5B%5D=spa&filter%5Bin%5D%5B%5D=arg&filter%5Bin%5D%5B%5D=cub&filter%5Bin%5D%5B%5D=esp&filter%5Bin%5D%5B%5D=sza&filter%5Bin%5D%5B%5D=rve&filter%5Bin%5D%5B%5D=prt&filter%5Bin%5D%5B%5D=ven&filter%5Bin%5D%5B%5D=per&filter%5Bin%5D%5B%5D=cri&filter%5Bin%5D%5B%5D=bol&filter%5Bin%5D%5B%5D=ury&filter%5Bin%5D%5B%5D=col&filter%5Byear_cluster%5D%5B%5D=2008 

Comportamento esperado: na ausência de ORCID ID, não exibir nem o ícone do ORCID e não linkar para nenhuma URL.
