### ISSUE TITLE
Zerar contador de itens selecionados para novas buscas

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#260]
Ao fazer uma busca e selecionar alguns itens, os mesmos itens persistem mesmo quando é feito uma nova busca.

A cada nova busca, os itens selecionados devem ser zerados.

**Comment by alexxxmendonca** [comment]
Esse erro persiste. Já está disponível em homolog?

**Comment by deandr** [comment]
Acho que entendi errado este ticket. O que implementei foi zerar os itens selecionados nos filtros pois quando o usuário muda a busca faz sentido zerar os filtros mas agora lendo novamente a descrição acredito que estava se referindo aos registros que o usuário marcou na listagem, é isso?

**Comment by alexxxmendonca** [comment]
Sim, isso mesmo! Embora limpar os filtros também faça sentido. Você pode manter essa alteração, certo?

**Comment by deandr** [comment]
Sim posso manter, mas gostaria de verificar se não seria o caso de discutir sobre zerar também os registros selecionados. Segue minha opinião:

- Os filtros selecionados estão relacionados a busca e por isso faz sentido ao se mudar a busca limpar os filtros para não interferir no resultado.

- Os registros selecionados estão relacionados aos documentos que o usuário achou interessante e que ele quer usar por exemplo na referência bibliográfica do seu artigo, ou seja na minha opinião não esta relacionado diretamente a busca e sim funcionam como uma lista de favoritos que ao terminar suas buscas o usuário pode exportar ou imprimir.

Agora se a decisão já foi tomada eu limpo a seleção mas gostaria de deixar registrado que a seleção de registros foi implementada inicialmente com este objetivo.

**Comment by alexxxmendonca** [comment]
Eu não havia pensado dessa forma. Vou discutir internamente e dou um retorno quando possível.

**Comment by deandr** [comment]
OK. Obrigado por considerar.

**Comment by alexxxmendonca** [comment]
O Abel concordou que o comportamento é interessante e devemos mantê-lo, porém como um novo contador com posição ainda a ser definida.

O contador atual deve manter apenas os itens selecionados da busca atual.

Serão então 2 contadores: um para a busca atual e outro para o histórico de buscas.

@deandr pode corrigir esse então, deixando-o limitado para a busca atual?

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
