### ISSUE TITLE
Acentuação em ordem alfabética nos clusters

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#261]
Ordem alfabética dos clusters está tratando os acentos de maneira diferenciada:

![image](https://cloud.githubusercontent.com/assets/4059679/17063858/c962738c-500f-11e6-84a3-70ea1c7896ad.png)

Ao menos na interface em Português (Espanhol também?), caracteres acentuados devem seguir a ordem alfabética correspondente da letra, independente do acento.

**Comment by deandr** [comment]
@alexxxmendonca 

Ajuste realizado e atualizado no ambiente de homologação. Favor limpar cache do navegador antes de realizar teste.

[]s

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
