### ISSUE TITLE
Adicionar os campos KW e IS ao formato RIS no processamento

### ISSUE THREAD

**Issue by patrickhilt** [scieloorg/search-journals#269]
Formato:
KW  - Keyword 1
KW  - Keyword 2
...

IS  - ISSN da revista

**Comment by fabiobatalha** [comment]
Removi o label de processamento pois já tem um ticket específico para processamento.

**Comment by alexxxmendonca** [comment]
Não encontrei o campo IS.

O campo KW aparece apenas a primeira palavra-chave nos 2 idiomas. É isso mesmo? Não deveria ter todas as palavras-chaves do artigo?

Segue RIS exportado do artigo http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0100-15742003000100008&lang=pt

TY  - JOUR
AU  - Jacobi, Pedro
TI  - Educação ambiental, cidadania e sustentabilidade
TT  - Environmental education, citizenship and sustainability
JO  - Cadernos de Pesquisa
J2  - Cad. Pesqui.
SN  - 0100-1574
VL  - 
IS  - 118
DO  - 10.1590/S0100-15742003000100008
DB  - SciELO Brasil
DP  - http://www.scielo.org/
ID  - S0100-15742003000100008-scl
LA  - pt
SP  - 189
EP  - 206
DA  - 2003-03
PY  - 2003
AB  - To reflect upon social practices, in a context marked by a permanent degradation of the environment and its ecosystem, involves a necessary articulation with the production of meanings on environmental education. The environmental dimension is now increasingly configured as an issue that comprises a team of players from the educational universe, strengthening the involvement of different knowledge systems, professional capacity building and the university community in an interdisciplinary perspective. The challenge posed is to formulate environmental education that is both critical and innovative on both the formal and informal levels. Thus, it must be primarily a political act concerned with social transformation. Its focus should be on searching for a holistic action perspective that correlates mankind, nature and the universe, having as a reference point the fact that natural resources run out and that mankind bears the main responsibility for its degradation.
AB  - A reflexão sobre as práticas sociais, em um contexto marcado pela degradação permanente do meio ambiente e do seu ecossistema, cria uma necessária articulação com a produção de sentidos sobre a educação ambiental. A dimensão ambiental configura-se crescentemente como uma questão que diz respeito a um conjunto de atores do universo educativo, potencializando o envolvimento dos diversos sistemas de conhecimento, a capacitação de profissionais e a comunidade universitária numa perspectiva interdisciplinar. O desafio que se coloca é de formular uma educação ambiental que seja crítica e inovadora em dois níveis: formal e não formal. Assim, ela deve ser acima de tudo um ato político voltado para a transformação social. O seu enfoque deve buscar uma perspectiva de ação holística que relaciona o homem, a natureza e o universo, tendo como referência que os recursos naturais se esgotam e que o principal responsável pela sua degradação é o ser humano.
UR  - http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0100-15742003000100008&lang=pt
L1  - http://www.scielo.br/pdf/cp/n118/16834.pdf
KW  - CITIZENSHIP
KW  - CIDADANIA
ER  -

**Comment by deandr** [comment]
@alexxxmendonca 

Já estou realizando o ajuste para o conteúdo do campo **KW**.

O campo de ISSN fica no prefixo **SN** conforme tabela informada em https://github.com/scieloorg/search-journals/issues/200#issuecomment-232685714 e esta disponível no exemplo citado acima.

[]s

**Comment by deandr** [comment]
Ajuste do campo **KW** realizado e ambiente de homologação atualizado.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
