### ISSUE TITLE
Incluir enlace para o PDF no formato RIS

### ISSUE THREAD

**Issue by patrickhilt** [scieloorg/search-journals#272]
Formato:
L1  - Enlace.pdf
Pode ser repetido no caso o artigo estiver presente em varios idiomas.

**Comment by alexxxmendonca** [comment]
Relacionado ao #200

**Comment by deandr** [comment]
@fabiobatalha 

Na interface atual estamos utilizando no link para o PDF  a chamada para o script **sci_pdf** para não expor diretamente o caminho para o arquivo PDF e não ter eventuais impactos de indicadores de acesso aos PDF's ou qualquer outro controle que se utilize atualmente que contabilize este acesso. 

No formato RIS podemos seguir esta mesma lógica de usar o **sci_pdf** ou podemos informar o caminho direto do PDF?

[]s

**Comment by scielo** [comment]
@deandr

As contagens de acesso aos pdf's não utilizam mais a página intermediária
sci_pdf, o apontamento pode ser feito diretamente para o PDF tanto no RIS
quanto na interface.

*Fabio Batalha C. Santos*
Colegiado SciELO
www.scielo.org
FAPESP - CNPq - BIREME - FapUNIFESP

2016-08-10 18:13 GMT-03:00 deandr <notifications@github.com>:

**Comment by deandr** [comment]
@fabiobatalha 

OK. Obrigado pelo esclarecimento.

[]s

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
