### ISSUE TITLE
Remover negrito do DOI

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#276]
Remover negrito do número do DOI que aparece nos resultados de busca.

**Comment by alexxxmendonca** [comment]
Parece que a cor alterou de preto para cinza mas o negrito continua ativo?

**Comment by deandr** [comment]
Segue print screen que tirei da minha maquina usando o homolog.search.scielo:

![doi-negrito](https://cloud.githubusercontent.com/assets/5338655/18181669/a677d77c-7062-11e6-98bd-61b7a5ff3038.png)

Me parece que esta OK. Poderia tentar limpar o cache e realizar novo teste?

Obrigado.

**Comment by alexxxmendonca** [comment]
Tens razão, agora foi!

**Comment by deandr** [comment]
:+1:
