### ISSUE TITLE
Compatibilizar os serviços de compartilhamento

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#280]
Há dois locais com serviço de terceiros (ShareThis) para compartilhamento: no resultado total da pesquisa e nos resultados individuais.

Embora ambos utilizem o ShareThis, certos serviços aparecem em um mas não aparecem em outro.

Por exemplo: Mendeley aparece nos resultados individuais mas não aparece na lista de serviços do resultado total (link "Compartilhar" -> Outras redes).

**Comment by alexxxmendonca** [comment]
Considerar trocar o serviço do sharethis pelo AddThis - http://www.addthis.com/

**Comment by deandr** [comment]
Compatibilizado opções do menu superior de compartilhamento com o menu dos artigos. Quando possível favor avaliar.

**Comment by alexxxmendonca** [comment]
O envio por e-mail (ícone do envelope) ainda está puxando o ShareThis. É isso mesmo? Já limpei meu cache.

**Comment by deandr** [comment]
Sim, foi feito a compatibilização das opções de compartilhamento mas o serviço permanece o ShareThis.

Alterar para outro serviço demandaria várias alterações no código, e se não houver nenhuma vantagem entre um e outro não acredito que se justifique.

**Comment by alexxxmendonca** [comment]
Ok, por ora deixemos como está e se houver a necessidade, reavaliaremos a troca de serviço.

Teria como incluir o "outras redes" de volta? Caso o usuário queira compartilhar para outra rede social além dessas que aparecem.

**Comment by deandr** [comment]
Ajuste realizado e aplicado no ambiente de homologação. 

Para poder adicionar o item "outras redes" tanto na opção de compartilhar a página quanto nas opções de compartilhar do artigo foi preciso realizar a chamada do serviço nestas duas opções, neste caso não é possível eliminar o pequeno ícone verde que retorna junto. Só era possível antes pois só estava na opção de compartilhar a página inteira.

**Comment by alexxxmendonca** [comment]
Atualmente há um problema na área sensível ao clique. Apenas no texto "outras redes" e no ícone verde o link está funcionando. Há como deixar sensível a área toda do botão?

**Comment by deandr** [comment]
@alexxxmendonca 

Ajuste realizado. Quando possível favor validar.

[]s

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
