### ISSUE TITLE
Link para "Citado em SciELO"

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#281]
Nos resultados de busca, "Citado em SciELO" deve ter um link que abre um modal com os artigos citantes contento:

- Título
- Autor
- Periódico
- Link

Os dados podem ser obtidos em http://citedby.scielo.org/api/v1/pid/?q=S0100-15742003000100008

~~onde S0100-15742003000100008 é o sufixo do DOI do artigo.~~

**Comment by fabiobatalha** [comment]
@deandr 

O valor de q deve ser o PID SciELO, não o sufixo do DOI.

**Comment by alexxxmendonca** [comment]
oops!

**Comment by fabiobatalha** [comment]
@alexxxmendonca 

Tranquilo, vc não precisa saber de tudo, rsrsrs.

**Comment by alexxxmendonca** [comment]
1) Trocar o texto em português para "Citado em SciELO"
2) A caixa modal abre mas só fica carregando. É normal isso?

**Comment by deandr** [comment]
OK para o item 1. 

Para o item 2, não conheço o serviço mas acredito que seja o comportamento normal, visto que ao pesquisar por documentos que possuem citação ele retorna a lista. Por exemplo ao buscar pelo título exato (com aspas) "Educação ambiental, cidadania e sustentabilidade" que é o exemplo citado na descrição deste ticket ele retorna uma lista de documentos.

**Comment by fabiobatalha** [comment]
@alexxxmendonca 

A resposta deste serviço é lenta mesmo. Estamos trabalhando para melhorar a performance, mas é uma query processada em tempo real.

Algumas respondem mais rápido pois tem uma camada de cache. Para as que já foram consultadas a resposta será mais rápida até que o cache expire.

**Comment by alexxxmendonca** [comment]
@deandr ok, deu certo pesquisando pelo artigo mencionado.

Vou fechar o ticket quando o "Citado em SciELO" for corrigido.

**Comment by deandr** [comment]
@alexxxmendonca 

Rótulo corrigido e atualizado no ambiente de homologação.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
