### ISSUE TITLE
Busca sem resultados deve retornar 

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#282]
Ao fazer uma busca que não retorne resultado algum, deve ser exibido uma mensagem na própria tela onde apareceriam os resultados -- ao invés de uma caixa de diálogo. A mensagem pode ser igual à mensagem utilizada hoje na caixa de diálogo:

> Não foram encontrados documentos para sua pesquisa

Em "Resultados:", deve aparecer "Resultados: 0".

Essa busca deve ficar armazenada no "Histórico de Buscas".

**Comment by deandr** [comment]
@alexxxmendonca,

Preciso da sua ajuda para entender melhor este ticket. 

Em um primeiro entendimento me parece que este ticket retorna ao funcionamento original da interface de busca para resultados nulo, que pode ser observado na interface da pesquisa do SciELO Books:

http://search.livros.scielo.org/search/?q=microcefalia

Entendi corretamente?  Note que se for isso todo o trabalho implementado no #140 será revertido, e ao mostrar uma página com a mensagem o sistema não irá mais apresentar as opções de filtro que o usuário fez que resultaram em um resultado nulo.

Obrigado.

**Comment by alexxxmendonca** [comment]
@deandr ao meu ver, os filtros devem ser mantidos, para que o usuário possa saber o motivo pelo qual sua busca não retornou resultados.

Isso é possível?

@fabiobatalha poderia confirmar essa minha visão?

**Comment by deandr** [comment]
@alexxxmendonca 

Posso verificar se é possível, mas você confirma que a caixa de diálogo presente desde o protótipo e que foi ajustada no ticket #140 deverá ser eliminado?

[]s

**Comment by alexxxmendonca** [comment]
Sim, isso eu confirmo.

**Comment by alexxxmendonca** [comment]
Quando a busca não retorna resultados, o número da busca é incrementado mas não atualizado na interface. O número só é atualizado quando a busca retorna resultados.

Creio que o número deva ser atualizado mesmo quando a busca não retorne resultados.

**Comment by deandr** [comment]
Ajuste realizado e disponível em homologação.

**Comment by alexxxmendonca** [comment]
Acho que o comportamento ainda não está correto.

Ao fazer uma busca que não possui resultados, o contador aumenta. Até aí ok, tudo certo.
Ao fazer em seguida uma busca que possui resultados, o contador não aumenta.
Somente ao fazer uma terceira busca é que o contador aumenta. Em alguns casos, o contador volta um número.

**Comment by deandr** [comment]
Estou com dificuldades de reproduzir o problema no meu computador. Utilizei o Chrome e o Firefox nos testes e não consegui identificar o comportamento descrito.

Você poderia realizar o teste com outros navegadores, limpando o cache, para verificar se o problema ocorre em todos?

Obrigado

**Comment by alexxxmendonca** [comment]
1 - Faça uma busca sem critérios
2 - Faça uma busca que retorne 0 resultados propositalmente
3 - Apague o campo de busca e clique em buscar

Note que o contador não muda.

4 - Faça uma outra busca qualquer.

Note que agora o contador muda.

Fiz o teste no IE que é um browser que nunca utilizo.

**Comment by deandr** [comment]
OK, veja o que esta acontecendo neste exemplo:

1. A busca sem critérios na realidade é uma busca por "*" e foi armazenada no histórico de buscas na posição (1).
2. A segunda busca por uma estratégia sem resultados adiciona um no histórico e é armazenada e o valor passa para (2) no total de histórico
3. Ao apagar o campo de busca na realidade você esta repetindo a busca do item 1, ou seja "*", buscas iguais não são adicionadas no histórico pois elas já foram realizadas na sessão do usuário. Mesmo comportamento pode ser observado no PubMed e outros buscadores.
4. Ao fazer uma outra busca o contador muda para (3) e não para 4 uma vez que o item 3 já constava no histórico.

Veja que este comportamento não é usualmente o que o usuário normalmente irá realizar portanto este "comportamento" não deve ser observado na maioria dos casos de uso.

**Comment by alexxxmendonca** [comment]
Ok, entendido. Nesse caso então está tudo certo.
