### ISSUE TITLE
Busca sem resultados em "Histórico de Busca" não executa a ação

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#283]
Em "Histórico de Busca", ao fazer uma busca que não retorne resultado algum, a aplicação não executa a ação e nada ocorre.

**Comment by deandr** [comment]
@alexxxmendonca 

Agora ao realizar uma busca que não retorna resultado é apresentado mensagem na própria tela do "Histórico de Busca", este é o comportamento desejado?

**Comment by alexxxmendonca** [comment]
@deandr 

Sim.

**Comment by alexxxmendonca** [comment]
O comportamento deve ser o mesmo do #282

**Comment by deandr** [comment]
OK. Ajuste realizado, a pesquisa sem resultados retorna para a mesma tela com a mensagem e também com o novo item adicionado no histórico. Quando possível favor verificar no homolog.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
