### ISSUE TITLE
Incluir opção de filtro "Todos" nos clusters

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#284]
Quando o cluster possui muitas opções, e quando todas as opções são selecionadas para realizar um filtro, a lista de filtros selecionados fica muito grande:

![image](https://cloud.githubusercontent.com/assets/4059679/17445017/4705657e-5b19-11e6-85e8-22b92aa4fb27.png)

Para melhorar a visualização, poderia haver um botão "Todos" no topo da lista de todos os clusters que, quando marcado, serviria para filtrar todas opções daquele cluster.

Se o usuário selecionar primeiro a opção "Todos" e depois marcar qualquer outra opção do mesmo cluster, a opção "Todos" deverá ser automaticamente desmarcada.

O comportamento deve ser semelhante ao "Todos" utilizado no filtro do Excel.

**Comment by alexxxmendonca** [comment]
Há um problema quando o cluster "Todos" é selecionado e filtrado: não é possível remover o filtro da opção "Filtros selecionados".

Creio também que a opção "Todos" deva aparecer na janela modal, também. E o mesmo comportamento deve se repetir: se o usuário selecionar primeiro a opção "Todos" e depois marcar qualquer outra opção do mesmo cluster, a opção "Todos" deverá ser automaticamente desmarcada.

**Comment by deandr** [comment]
@alexxxmendonca 

Estou verificando o problema com a remoção do filtro "Todos".

Relacionado ao tema de adicionar o "Todos" na janela modal, poderiamos substituir a opção "Selecionar Todos" por "Todos" e aplicar o mesmo comportamento do filtro na página de resultados?  Caso contrário teriamos duas opções na janela modal para o mesmo efeito.

[]s

**Comment by alexxxmendonca** [comment]
@deandr sim, bem lembrado! Pode fazer isso sim, mas deixe ela já habilitada quando o usuário fizer a seleção prévia.

**Comment by deandr** [comment]
Atualizado em homologação. Quando possível realizar nova verificação.

**Comment by alexxxmendonca** [comment]
Apenas uma correção: na janela modal, quando o "Todos" já estiver selecionado, se o usuário clicar em alguma outra opção, o "Todos" deve ser desmarcado.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
