### ISSUE TITLE
Manter o idioma selecionado durante o uso

### ISSUE THREAD

**Issue by ednilson** [scieloorg/search-journals#285]
Ao selecionar o idioma da interface o sistema sempre retorna ao idioma Português após realizar uma busca qualquer.

Passos da verificação:
1. acessar o formulário inicial;
2. selecionar o idioma da interface (Español ou English);
3. realizar uma busca qualquer;
4. note que a interface volta para Português (não há parâmetro "&lang= " na URL).

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
