### ISSUE TITLE
Código HTML nos resumos

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#290]
Certos resumos estão apresentando codificação HTML:

![image](https://cloud.githubusercontent.com/assets/4059679/18202833/0ebd93e0-70e9-11e6-892d-936140fdda6f.png)

http://homolog.search.scielo.org/?q=arquivos&lang=pt&count=15&from=1&output=site&sort=&format=summary&fb=&page=1&filter%5Byear_cluster%5D%5B%5D=2002

**Comment by deandr** [comment]
Ajuste realizado. Quando possível favor verificar.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
