### ISSUE TITLE
Adequações visando protótipo original

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#293]
O documento anexo foi elaborado pelo designer e lista as alterações necessárias para que layout siga o protótipo original.
[Avaliacao-iAHx-Homolog.pptx](https://github.com/scieloorg/search-journals/files/457388/Avaliacao-iAHx-Homolog.pptx)

**Comment by deandr** [comment]
@alexxxmendonca 

Dei uma olhada rápida no documento, mas ele precisa ser quebrado em tickets separados para cada alteração proposta, pois várias desta alterações estão em desacordo com outros tickets já implementados e solicitados na reunião com o Abel. 

Sugiro que este documento seja utilizado como referência por vocês em reunião da interface, e após análise sejam criados os respectivos tickets.

**Comment by alexxxmendonca** [comment]
Foram criados tickets individuais.

**Comment by deandr** [comment]
OK. Obrigado :+1:
