### ISSUE TITLE
Alinhar caixa de busca - Histórico de buscas

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#294]
Alinhar caixa de busca, na página Histórico de Buscas, como o protótipo original:

![image](https://cloud.githubusercontent.com/assets/4059679/18285336/45ece01a-7444-11e6-9d3a-5bd5a54904fd.png)

**Comment by alexxxmendonca** [comment]
Aqui, o alinhamento deve seguir o rodapé. Veja no protótipo: http://scielohomolog.parati.ag/iAHx-Colecao/historico.html

**Comment by deandr** [comment]
Note que não consigo mais alinhar com o rodopé, uma vez que no protótipo só era considerado uma única linha de busca mas no nosso caso foi solicitado a alteração para incluir o botão que adiciona novas linhas ao formulário.

Desta forma ao clicar em adicionar uma nova linha aparece a primeira coluna a esquerda que contém o "X" para remover a linha que ocupa a posição onde deveria ser o alinhamento.

**Comment by caramez** [comment]
Pessoal, acho que vamos ficar assim mesmo. Eu só consideraria 2 coisas:
- Arrumar o estilo do campo quando está com foco
- Retirar o texto de ajuda "Para combinar suas buscas, utilize os conectores "AND", "OR" e "AND NOT"." Porque não faz mais sentido, uma vez que dá para adicionar campos.

![image](https://cloud.githubusercontent.com/assets/22373640/18753169/e95ea828-80ba-11e6-803a-73a3b67e4994.png)

**Comment by deandr** [comment]
@alexxxmendonca 

Últimos ajustes propostos pelo designer foram aplicados no ambiente de homologação. Quando possível favor validar.

[]s

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
