### ISSUE TITLE
Índice "Área temática"

### ISSUE THREAD

**Issue by deandr** [scieloorg/search-journals#301]
Este ticket é referente a disponibilização do seguinte índice:

--- área temática (grande área, área WoS e seção sumário) – por palavras e frases

Relacionado ao ticket #207

**Comment by deandr** [comment]
@alexxxmendonca 

Atualmente os elementos área temática da SciELO e WoS só estão disponíveis no idioma inglês nos XML's que são indexados e são traduzidos no momento de mostrar ao usuário na coluna de filtros.

A criação de um índice de busca para estes campos permitirá a busca somente pelos termos em inglês, por favor confirmar se devemos prosseguir mesmo assim ou se seria melhor deixar este índice somente como um filtro como esta disponível hoje.

[]s

**Comment by alexxxmendonca** [comment]
@deandr 

Pode confirmar se esse índice está incluso no índice "Todos os índices" da busca?

**Comment by deandr** [comment]
@alexxxmendonca

Não, somente os índices contidos na lista que é apresentada no formulário da interface estão disponíveis no índice "Todos os índices".

**Comment by alexxxmendonca** [comment]
Será resolvido no #325
