### ISSUE TITLE
Índice "idioma"

### ISSUE THREAD

**Issue by deandr** [scieloorg/search-journals#302]
Este ticket é referente a disponibilização do seguinte índice:

--- idioma

Relacionado ao ticket #207

**Comment by deandr** [comment]
@alexxxmendonca 

O elemento disponível nos XML's que são indexados somente contém a sigla do idioma do artigo (pt, es, en, fr, ...). 

A criação de um índice para este elemento somente irá permitir que o usuário busque usando estas siglas. Por favor validar se devemos prosseguir com a criação deste índice com esta limitação ou deixamos somente como uma opção de filtro, onde na interface é possível realizar a tradução dos termos.

[]s

**Comment by alexxxmendonca** [comment]
@deandr 

Pode confirmar se esse índice está incluso no índice "Todos os índices" da busca?

**Comment by deandr** [comment]
@alexxxmendonca

Não, somente os índices contidos na lista que é apresentada no formulário da interface estão disponíveis no índice "Todos os índices".

**Comment by alexxxmendonca** [comment]
Será resolvido no #325
