### ISSUE TITLE
Índice "País de afiliação do autor"

### ISSUE THREAD

**Issue by deandr** [scieloorg/search-journals#303]
Referente ao índice:

--- país – afiliação do autor

Relacionado ao ticket #207

**Comment by deandr** [comment]
@fabiobatalha 

Estou em dúvida sobre o conteúdo que é gerado nos XML's de indexação para o elemento "aff_country" pois ao realizar uma busca por "Brasil" neste índice só recupero um artigo conforme pode ser observado no ambiente de homologação:

http://homolog.search.scielo.org/?q=aff_country%3ABrasil&lang=pt&page=1

Poderia confirmar quais são os conteúdos que estão sendo indexados neste campo, nome do país completo (em qual idioma), sigla do país, outro?

Obrigado

**Comment by fabiobatalha** [comment]
@viniciusandrade 

Esse campo esta com código ISO do país. Tem que ser traduzido. Esse campo também tem falhas de normalização.

**Comment by fabiobatalha** [comment]
@deandr 

Corrigindo, ele esta com o nome do país de acordo com a norma ISO 3166, quando é possível identificar o código do país, caso contrário, o valor apresentado é o valor do campo.

**Comment by deandr** [comment]
@fabiobatalha 

OK, obrigado pela verificação.

@alexxxmendonca 

Um índice de pesquisa que somente permite a busca pelos códigos dos paises não é muito interessante do ponto de vista do usuário. 
Favor confirmar se mesmo assim deve-ser implementado na lista de índices ou deve-ser implementado somente na lista de filtros  conforme solicitado no ticket #214.

[]s

**Comment by fabiobatalha** [comment]
@deandr 

Não é somente pelo código de país eu retifiquei minha mensagem logo após o envío.

O índice esta com o país de forma descritiva, entretanto não é um campo normalizado, podem existir erros. As tentativas de normalização utilizam a norma ISO-3166, os nomes de países estão preferencialmente em inglês.

Esse é o resultado de busca pelo campo aff_country no índice de homologação.

aff_country:Brasil
![screen shot 2016-10-03 at 2 47 10 pm](https://cloud.githubusercontent.com/assets/504142/19047665/33993fa4-8979-11e6-89e4-ad72a3be567a.png)

aff_country:Brazil
![screen shot 2016-10-03 at 2 47 01 pm](https://cloud.githubusercontent.com/assets/504142/19047688/4e4a304c-8979-11e6-91d9-0c5d06a1a198.png)

**Comment by deandr** [comment]
@fabiobatalha 

OK. Entendido. De qualquer forma fica a dúvida em colocar este índice não normalizado, pois ao buscar por "Brasil" o resultado foi de **24858** e ao buscar por "Brazil" foi de **263376**. 

Agora, uma dúvida: o resultado por "Brazil" estaria contemplando todos os registros de "Brasil", que pelos números é um conjunto bem menor ?

**Comment by fabiobatalha** [comment]
@deandr 

Não pois esse dado esta no campo de país de afiliação dos autores, podem existir autores brasileiros publicando em revistas extrangeiras. Neste caso é uma má ideia vincular o número de resultados de documentos por país de afiliação com número de documentos em revistas brasileiras.

**Comment by deandr** [comment]
@fabiobatalha 

OK. 

Mas acredito que sem uma normalização será complicado disponibilizar este campo como índice ou filtro. Fiz a seguinte busca:

aff_country:"Brasil" AND NOT aff_country:"Brazil"

E obtive como resultado 12.036 registros -- ou seja são de autores cujo pais de afiliação é o Brasil mas não estão normalizados como "Brazil" no elemento.

[]s

**Comment by fabiobatalha** [comment]
@deandr 

Pois é podem existir versões diferentes de brasil em um mesmo documento.

Estados Unidos é um exemplo bom. Pode estar EUA, Estados Unidos, Estados Unidos da América, United States, USA .......

**Comment by alexxxmendonca** [comment]
@deandr 

Pode confirmar se esse índice está incluso no índice "Todos os índices" da busca?

**Comment by deandr** [comment]
@alexxxmendonca 

Não, somente os índices contidos na lista que é apresentada no formulário da interface estão disponíveis no índice "Todos os índices".

**Comment by alexxxmendonca** [comment]
Será resolvido no #325
