### ISSUE TITLE
Habilitar "Citado em SciELO"

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#304]
Esse recurso precisa ser ocultado quando não há registros de citações, porém isso requer desenvolvimento e, para não ir ao ar com essa debilidade, por ora esse recurso deve ser desativado.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em produção.

**Comment by fabiobatalha** [comment]
Dados de citações foram carregados no índice.

Ocultar link quanto total_received for igual a 0.

O comportamento deve mudar, remetendo o usuário para a página do analytics.

http://analytics.scielo.org/w/bibliometrics/document/list/received_citations?document=S1413-70542011000600001&collection=scl

**Comment by fabiobatalha** [comment]
O link não abre. Ao clicar no link um modal é carregado.

Esse modal deve ser excluído o link deve abrir uma nova janela.

**Comment by deandr** [comment]
@fabiobatalha,

Não consegui reproduzir o problema acessando o homolog do meu computador, no meu caso aparece "Citado x vezes em SciELO" com link abrindo nova aba apontando para o analytics.

Poderia verificar se não é algum tipo de cache local? Obrigado.

**Comment by fabiobatalha** [comment]
@deandr 

É verdade, era cache.

**Comment by deandr** [comment]
:+1:
