### ISSUE TITLE
"Todos" deve selecionar todos os itens do cluster

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#306]
Ao selecionar o item "Todos" nos clusters, o comportamento deve ser marcar/selecionar todos os itens.

Justificativa: caso o usuário queira filtrar por todos os itens menos um.

**Comment by deandr** [comment]
Infelizmente não é possível aplicar este ajuste. 

Lembrando que já foi mencionado que se a opção "Todos" no filtro marcar as opções, não será garantido a busca por todos os filtros, uma vez que por limitação não é possível carregar todas as opções no filtro na página de resultados.

Também teriamos efeitos colaterais na caixa de seleção de filtros, pois ao marcar todos os itens a busca poderia ficaria muito grande (principalmente no filtro de periódicos) e causar lentidão ou não resposta do servidor.

**Comment by alexxxmendonca** [comment]
E quanto a aplicar apenas na caixa modal?

Se não for possível, haveria outra sugestão para o caso de querer selecionar todos menos um?

**Comment by alexxxmendonca** [comment]
@deandr é possível ter esse comportamento na janela modal?

**Comment by alexxxmendonca** [comment]
Testado e aprovado em homologação.
