### ISSUE TITLE
Tooltip para itens de clusters longos

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#315]
Se o cluster possuir um ou mais itens muito longos (truncados por reticências), aplicar um tooltip com o nome completo do item para todos os itens daquele cluster, mesmo aqueles que não são truncados.

**Comment by alexxxmendonca** [comment]
Esse ticket resolve o #229

**Comment by deandr** [comment]
@alexxxmendonca 

Só foi possível aplicar o tooltip para aqueles itens que são longos (truncados por reticências), para os itens que não estão truncados o tooltip não é apresentado.

A outra alternativa seria aplicar o tooltip para todos os itens idenpendentes do filtro possuir ou não itens trucandos.

**Comment by alexxxmendonca** [comment]
Particularmente eu prefiro assim (mostrar apenas para os itens truncados).

Vamos deixar assim por ora e aguardar aprovação.

**Comment by alexxxmendonca** [comment]
Ainda não consigo testar.

**Comment by deandr** [comment]
Para mim esta aparecendo quando eu passo o mouse por cima de um item truncado: 

![tooltip-filtro](https://cloud.githubusercontent.com/assets/5338655/19560041/85dcee10-96b1-11e6-8dac-95ae59fa7610.png)

Poderia verificar se é algo relacionado com o navegador?

Obrigado

**Comment by alexxxmendonca** [comment]
Apareceu como se fosse um atributo Alt:

![image](https://cloud.githubusercontent.com/assets/4059679/19560252/745644b0-96b2-11e6-8cf5-a8c0c987ac65.png)

Seria isso?

Eu estava imaginando algo como o tooltip das redes sociais:

![image](https://cloud.githubusercontent.com/assets/4059679/19560286/9b1414f6-96b2-11e6-99d1-feb0185d1ec4.png)

Estamos usando esse tooltip ao longo do site. Talvez precisaremos do envolvimento do @caramez para isso.

**Comment by deandr** [comment]
Entendi. Vou tentar replicar o código do tooltip usado pelo designer neste ponto. 

Caso eu não consiga eu informo e deixamos para o ajuste final dele.

**Comment by deandr** [comment]
@alexxxmendonca 

Alterado para utilizar a mesma classde de tooltip utilizado pelo designer. Favor verificar.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/ (ficou ótimo!)
