### ISSUE TITLE
Título do cluster não aparece

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#317]
Em momentos aleatórios, talvez dependendo da combinação de filtros, alguns títulos de clusters não aparecem:
![untitled-2](https://cloud.githubusercontent.com/assets/4059679/19074981/44eb72f4-8a19-11e6-981e-bbde9def1079.png)
http://homolog.search.scielo.org/?fb=&q=*&lang=pt&count=15&from=1&output=site&sort=&format=summary&page=1&where=

**Comment by deandr** [comment]
@fabiobatalha 

Favor atualizar o arquivo de configuração **solrconfig.xml** com a última versão disponível no repositório de código e reiniciar o serviço do solr para a correção deste problema.

[]s

**Comment by jamilatta** [comment]
Item ajustado, por favor verificar em produção.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em produção.

**Comment by alexxxmendonca** [comment]
Parece que esse problema voltou a ocorrer:

![image](https://cloud.githubusercontent.com/assets/4059679/19559419/84e322ca-96ae-11e6-8820-4d30b15e828b.png)

http://homolog.search.scielo.org/?q=*&lang=en&page=1

**Comment by deandr** [comment]
O problema só ocorre em homologação.

@fabiobatalha 

Este é mais um caso onde pode-se notar que os arquivos de configuração do índice de homologação estão desatualizados em relação ao repositório.

**Comment by deandr** [comment]
@alexxxmendonca 

Ambiente de homologação agora esta com a última versão dos arquivos de configuração, favor validar.

[]s

**Comment by alexxxmendonca** [comment]
Tudo certo agora!
