### ISSUE TITLE
Anos inexistentes no cluster de "Ano"

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#321]
No cluster de ano aparecem dois anos inexistentes: 0015 e 0016:

![image](https://cloud.githubusercontent.com/assets/4059679/19201248/495489f2-8ca3-11e6-8fbc-68e78f527b63.png)

Todos os resultados retornam erro 404 not found.

**Comment by deandr** [comment]
@alexxxmendonca 

Tudo indica que seja problema com os metadados dos documentos. É possível listar os artigos usando o link abaixo e verificar que na referência bibliográfia o dado do ano já se encontra errado:

http://search.scielo.org/?q=year_cluster%3A%28%220015%22+OR+%220016%22%29

[]s

**Comment by alexxxmendonca** [comment]
Solicitação de correção encaminhada para a equipe de Produção SciELO.

**Comment by alexxxmendonca** [comment]
Analisando melhor, os artigos são do SciELO Espanha. Precisaremos definir como lidar quando o dado incorreto vier de outros países da Rede SciELO.

**Comment by alexxxmendonca** [comment]
Por ora esse ticket foi resolvido. Aparentemente os dados foram corrigidos pela equipe do SciELO Espanha.
