### ISSUE TITLE
Cluster "Citáveis e não citáveis" desaparece

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#322]
Chrome >> search.scielo.org>> buscar (650 997 regs) >> filter: Brasil >> 2015 >> o filtro citáveis / não citáveis desaparece.

**Comment by fabiobatalha** [comment]
Problema no reprocessamento do índice, o mesmo foi interrompido. Estamos processando novamente.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em produção.
