### ISSUE TITLE
Reclassificação de áreas temáticas

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#326]
1. as grandes áreas temáticas no SciELO constituem uma categoria chave na avaliação dos periódicos;
2. as grandes áreas temáticas do SciELO, derivadas da classificação da CAPES são em número de 9 categorias, como segue:

```
1 agricultural sciences
2 applied social sciences
3 biological sciences
4 engineering
5 exact and earth sciences
6 health sciences
7 human sciences
8 linguistics, letters and arts
9 multidisciplinary

```
​3. a categoria multidisciplinary corresponde aos periódicos que estão classificados em três ou mais áreas.
4. nas tabelas do analytics há uma coluna para cada categoria com valores 1 ou 0 que corresponde a pertencer à área ou não, respectivamente.
5. a categoria multidisciplinary estava calculada erradamente. 
6. um periódico pode pertencer a mais de uma categoria.
7. as tabulações por áreas temáticas de periódicos em mais de uma categoria são contabilizadas individualmente somente quando o periódicos pertence a duas áreas. No caso de três ou mais áreas (multidisciplinar) conta-se somente uma vez como multidisciplinar.
8. com base no item anterior os periódicos multidisciplinares (hoje em número de 6) devem ser excluídos das contagens das áreas temáticas.
9. a razão principal da contagem única dos periódicos em três ou mais categorias é evitar que alguns periódicos como o Anais da Academia Brasileira de Ciência e Acta Amazônica alterem as estatísticas de categorias como humanas e sociais aplicadas em cujas áreas este periódicos quase nada publicam. Ao ser incluídos em todas as áreas poluem as estatísticas de humanas e sociais aplicadas

O índice do Search deve ser alterado para atender a essa nova classificação.

**Comment by fabiobatalha** [comment]
@deandr 

O termo deverá ser traduzido nas telas onde ele aparecerá.

**Comment by alexxxmendonca** [comment]
PT - Multidisciplinar
EN - Multidisciplinary
ES - Multidisciplinaria

**Comment by deandr** [comment]
@alexxxmendonca,

OK. Ajuste de tradução realizado na interface.  Quando possível favor validar.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
