### ISSUE TITLE
Compatibilizar layout

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#327]
Compatibilizar HTML e CCS da produção com o protótipo proposto pelo designer, visando um fluxo de trabalho sustentável entre desenvolvimento e design.

Após a conclusão dessa tarefa, todas as alterações de design deverão passar primeiro pelo designer, evitando incompatibilidade entre as versões do designer e produção.

**Comment by caramez** [comment]
Pessoal, finalizamos a compatibilização porém há ainda pequenos problemas. Relacionados à janela dos clusters (que já que vamos alterar, vamos fechar depois).

**Comment by jamilatta** [comment]
👍

**Comment by alexxxmendonca** [comment]
Testado e aprovado!
