### ISSUE TITLE
Criar botão "limpar filtros"

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#328]
Necessidade surge quando há muitos filtros aplicados.

![image](https://cloud.githubusercontent.com/assets/4059679/19559742/0a379b4e-96b0-11e6-8c7a-8b0ba9d5e218.png)

**Comment by caramez** [comment]
Pessoal, finalizamos a implantação deste item, criamos um botão junto aos títulos das listas com a opção.

![image](https://cloud.githubusercontent.com/assets/22373640/20560528/fbc6ac46-b160-11e6-862c-59c54363f0d3.png)

**Comment by alexxxmendonca** [comment]
:+1:

**Comment by alexxxmendonca** [comment]
Precisamos agora que o botão execute sua função de limpar os filtros.

@deandr, pode fazer isso?

**Comment by deandr** [comment]
Sim, favor criar um ticket relacionado a este para o desenvolvimento da função para poder fechar este relativo ao design.

[]s

**Comment by alexxxmendonca** [comment]
Design testado e aprovado em homologação.
