### ISSUE TITLE
Renderizar HTML nos resumos

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#330]
Muitos resumos possuem códigos HTML que precisam ser renderizados.

![image](https://cloud.githubusercontent.com/assets/4059679/19572356/bdbc1886-96e0-11e6-8d3a-a3b8cdbd8609.png)

Esse símbolo na verdade deveria ser <= (menor ou igual). 

http://homolog.search.scielo.org/?q=A+import%C3%A2ncia+da+an%C3%A1lise+de+especia%C3%A7%C3%A3o+do+chumbo+em+plasma+para+a+avalia%C3%A7%C3%A3o+dos+riscos+%C3%A0+sa%C3%BAde&lang=pt&page=1

Link do artigo original: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0100-40422004000200015&lang=pt

**Comment by deandr** [comment]
Estou marcando este ticket como processamento para verificação dos metadados que estão sendo enviados para o índice pois ao consultar o XML deste documento o elemento **ab_en** já esta vindo somente com o sinal de "<".

http://homolog.search.scielo.org/?q=10.1590/S0100-40422004000200015&lang=pt&page=1&output=xml

**Comment by gustavofonseca** [comment]
O dado está errado no XML, conforme é possível visualizar no fragmento abaixo:

![Screen Shot 2021-05-27 at 16 23 36](https://user-images.githubusercontent.com/161335/119885311-0e919e80-bf08-11eb-8389-9866d1177f75.png)

**Comment by alexxxmendonca** [comment]
Este problema tem origem anterior no fluxo de dados. Os dados recebidos para indexação no Search SciELO já vem desformatados.

O problema já está reportado no projeto que lhe compete.

Este ticket está fora do escopo deste projeto e portanto será fechado.
