### ISSUE TITLE
Novas traduções

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/search-journals#339]
Novos rótulos que demandam traduções foram incorporados nos PR's #325 #328

**Comment by alexxxmendonca** [comment]
Em Português está Ok mas em Inglês e Espanhol está estranho:

![image](https://cloud.githubusercontent.com/assets/4059679/22751676/8cc4ff16-ee1c-11e6-813f-846c92705b3c.png)

![image](https://cloud.githubusercontent.com/assets/4059679/22751686/9613bf58-ee1c-11e6-8f26-6787843c09cd.png)

**Comment by caramez** [comment]
@alexxxmendonca o Eduardo subiu a correção e avisou ao @fabiobatalha ontem.
Ficamos no aguardo para visualizar a correção em homolog

**Comment by alexxxmendonca** [comment]
Testado e aprovado!
