### ISSUE TITLE
Criar cluster "Periódicos - Status"

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#343]
Criar um cluster/filtro de nome "Periódicos - Status" que permite filtrar pelo status do periódico na Coleção:

Todos
Títulos correntes
Títulos não-correntes

Por padrão, os resultados de busca devem trazer todos.

@deandr se for necessário envolver o designer nessa atividade, favor designá-lo a esse ticket.

**Comment by deandr** [comment]
@alexxxmendonca,

Para um novo cluster/filtro basicamente é necessário os seguintes passos antes de publicar na interface:

- Agregar o novo elemento ao XML de indexação dos artigos (processamento)
- Configurar no serviço de busca (Solr) o novo filtro
- Realizar a tradução dos rótulos do filtro para apresentação na interface

Estou direcionando para o processamento avaliar e posteriormente posso dar continuidade.

[]s

**Comment by alexxxmendonca** [comment]
Duplicado: #465
