### ISSUE TITLE
Incluir lógica AND/OR para clusters de idioma e áreas temáticas

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#344]
Os clusters "Idioma" e "Áreas temáticas" devem possuir botões de lógica AND / OR acima das opções de filtro.

**Comment by paratiuid** [comment]
[mockup-ajuste-scielo-and-or v2.pdf](https://github.com/scieloorg/search-journals/files/1540304/mockup-ajuste-scielo-and-or.v2.pdf)

Segue no pdf em anexo a ideia dos passos e aplicação das condições AND ou OR:

Tela 01 - tela da busca

tela 02 - selecionado um idioma

tela 03 - ao selecionar o segundo idioma, abre o modal

tela 04 - modal aberto com opção de incluir mais idiomas

tela 05 - filtro aplicado e exibido na lista de filtros


Aguardo aprovação.

**Comment by alexxxmendonca** [comment]
Me parece bom! Podem fazer os protótipos.

**Comment by paratiuid** [comment]
Feito e disponibilizado na develop.
@alexxxmendonca vou lhe chamar no hangout para lhe apresentar o resultado.

**Comment by gustavofonseca** [comment]
Existe código referente a esta atividade no pull-request https://github.com/scieloorg/search-journals/pull/390

**Comment by joffilyfe** [comment]
@alexxxmendonca foi enviada uma nova versão para a instância de homologação que complementa o código feito pela Parati (#408). Você poderia dar o seu parecer? Estamos no aguardo.

**Comment by alexxxmendonca** [comment]
@joffilyfe testado e aprovado em homologação

**Comment by cesarbruschetta** [comment]
@alexxxmendonca A gente atualizou o ambiente de produção do http://search.scielo.org, vc consegue verificar se esta tudo ok?

**Comment by alexxxmendonca** [comment]
@cesarbruschetta tudo certo! testado e aprovado em produção!
