### ISSUE TITLE
Número do resultado trunca com ícone de OA

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#351]
Quando o número do resultado é muito alto, o layout trunca com o ícone de Acesso Aberto:

![image](https://cloud.githubusercontent.com/assets/4059679/22881501/ec98307a-f1cd-11e6-8f92-68e14b3578e8.png)

**Comment by paratiuid** [comment]
@alexxxmendonca 
o que ocorre é que o número está na mesma coluna em que se encontra o checkbox. Esta, tem uma largura fixa.

Minha sugestão é reposicionar o número na coluna ao lado, antes do ícone de acesso aberto.
Segue a sugestão:
![image](https://user-images.githubusercontent.com/22373640/33335296-c65cb818-d453-11e7-8120-70e5a525f8e2.png)

![image](https://user-images.githubusercontent.com/22373640/33335306-cbebf366-d453-11e7-8a3f-46cd4d44045b.png)

**Comment by alexxxmendonca** [comment]
De acordo com a sugestão.

**Comment by paratiuid** [comment]
Corrigido e disponibilizado na develop do search

**Comment by jamilatta** [comment]
@alexxxmendonca 

Poderia validar essa atividade no endereço: http://192.168.1.111:60509/

**Comment by alexxxmendonca** [comment]
Testado e aprovado 👍

**Comment by alexxxmendonca** [comment]
@jamilatta isso já está em produção?

**Comment by alexxxmendonca** [comment]
@paratiuid agora os números estão aparecendo duplicados?

![image](https://user-images.githubusercontent.com/4059679/50018242-ba9fd300-ffb5-11e8-9e2c-6156a2e6b040.png)

**Comment by gustavofonseca** [comment]
@alexxxmendonca, poderia, por gentileza, verificar em https://homolog.search.scielo.org?

**Comment by alexxxmendonca** [comment]
Testado e aprovado em homologação.
