### ISSUE TITLE
Resultados truncados?

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#352]
Por motivo do qual desconheço, alguns resultados apareceram truncados:

![image](https://cloud.githubusercontent.com/assets/4059679/22881543/31d7e8ce-f1ce-11e6-9bc3-71268e7a628a.png)

http://homolog.search.scielo.org/?q=*&lang=pt&count=15&from=160501&output=site&sort=CITED_DESC&format=summary&fb=&page=10701

Pode estar relacionado com os registros de número alto. Não sei dizer se é uma questão de design ou desenvolvimento.

@caramez e @deandr, poderiam investigar?

**Comment by caramez** [comment]
@alexxxmendonca e @deandr dei uma analisada na estrutura de código aqui e percebi que os abstracts, podem possuir caracteres especiais (por exemplo < e >), estes caras estão sendo entendidos como tags HTML abertas. No caso deste especificamente tem este trecho aqui: "<1035.70 ± 36.65 kg <NPLb." isto está sendo interpretado como uma tag aberta.

Reparem até que na interpretação do código o Chrome se confunde.
![image](https://cloud.githubusercontent.com/assets/22373640/22883412/4f2ac122-f1d7-11e6-96df-c302e23fd28c.png)

**Comment by alexxxmendonca** [comment]
Haveria alguma relação com o ticket #330 ?

**Comment by deandr** [comment]
Realizei ajuste no código para realizar o "escape" destes caracteres na hora de apresentar a página. Favor aguardar a aplicação na homologação para nova verificação.

Quanto ao ticket #330 acredito que não pois naquele caso o elemento que esta registradado no XML é diferente do que esta no artigo original.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
