### ISSUE TITLE
Tradução de filtros faltando em inglês e espanhol

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/search-journals#353]
A tradução de indicação dos filtros esta sumindo em inglês e espanhol.

Em português:

<img width="313" alt="screen shot 2017-02-13 at 09 40 19" src="https://cloud.githubusercontent.com/assets/504142/22882096/afc07600-f1d0-11e6-8cb4-9fc142869261.png">

Em inglês e espanhol:

<img width="263" alt="screen shot 2017-02-13 at 09 41 49" src="https://cloud.githubusercontent.com/assets/504142/22882099/b2943542-f1d0-11e6-9bf1-419434ac7bbf.png">

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
