### ISSUE TITLE
Mostrar licença completa no mouse over do ícone do OA

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#356]
Ao passar o mouse em cima do ícone do Acesso Aberto, mostrar a licença completa:

Por ex:

"CC-BY/4.0" no lugar de "BY/4.0".

Talvez trocar o comportamento também. Ao invés de usar o "alt", utilizar tooltip.

**Comment by deandr** [comment]
Este issue possui duas partes: design (tooltip vs alt) e código da licença que faz parte dos metadados do artigo. Abaixo escrevo sobre o código.

O dado da licença vem do atributo **use_licence** do processamento. Caso seja simplesmente adicionar o prefixo **CC-** antes de mostrar o o atributo pode ser feito pela programação. Caso o código da licença completa tenha outras variações precisa ser direcionado ao processamento para ajuste.

**Comment by alexxxmendonca** [comment]
Acho que não temos outra variação. É sempre "CC-" o começo.

**Comment by deandr** [comment]
@alexxxmendonca, OK.

@fabiobatalha, concorda que eu adicione esta informação fixa no template ou prefere adicionar na geração do campo em  processamento?

[]s

**Comment by scielo** [comment]
@deandr

Pode colocar o CC na interface.

*Fabio Batalha C. Santos*
Lider de Tecnologia
www.scielo.org
FAPESP - CNPq - BIREME - FapUNIFESP

**Comment by deandr** [comment]
@alexxxmendonca,

Adicionei o prefixo e aproveitei que a alteração era mínima e adicionei a classe que define que o elemento deve ser mostrado como tooltip. Favor verificar na homologação quando disponível para testes.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
