### ISSUE TITLE
Setas na classificação da janela modal

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#358]
Ao optar por classificar os itens por ordem alfabética, a seta dos resultados continua aparecendo:

![image](https://cloud.githubusercontent.com/assets/4059679/22891658/3b6a5c72-f1f7-11e6-8384-19a6613235e1.png)

A seta deve aparecer apenas na classificação que estiver ativa.

**Comment by paratiuid** [comment]
Corrigido e disponibilizado na develop do projeto search

**Comment by jamilatta** [comment]
@alexxxmendonca

Poderia validar esse PR no endereço: http://192.168.1.111:60509/

**Comment by alexxxmendonca** [comment]
Já aplicado em produção. Fechando o ticket.
