### ISSUE TITLE
Inconsistências no link "Mostrar mais" das janelas dos periódicos

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#362]
As janelas modais que aparecem ao clicar no título do periódico estão apresentando comportamentos inconsistentes.

1) Quando o periódico não é da Coleção SciELO Brasil, ao clicar no link "Mostrar Mais", está caindo na home da Coleção ao invés de cair na home do periódico. O parâmetro ISSN é informado na URL então deve abrir o periódico.

2) Ao clicar no título de um periódico não-Brasil e depois em um periódico Brasil, a janela mostra menos dados do que deveria. Ao fechar e clicar novamente no título do periódico Brasil, a janela volta a mostrar a quantidade certa de dados.

**Comment by alexxxmendonca** [comment]
O problema 2 foi corrigido, mas o problema 1 persiste no primeiro clique.

Quando o periódico não é da Coleção SciELO Brasil, ao clicar no link "Mostrar Mais", está caindo na home da Coleção ao invés de cair na home do periódico.

**Comment by deandr** [comment]
@alexxxmendonca 

Não estou mais conseguindo reproduzir o erro acessando o ambiente de homologação. Provei com diferentes navegadores e ao clicar o no link "Mostrar mais" esta redirecionando corretamente para a home do periódico.

Poderia tentar limpar completamente o cache do navegador e também verificar usando outros navegadores?

Obrigado

**Comment by alexxxmendonca** [comment]
Testei em uma guia anônima e em outro navegador e deu certo.

Testei em outras duas máquinas diferentes e também deu certo.

Acho que era cache da minha máquina mesmo.

**Comment by deandr** [comment]
:+1:
