### ISSUE TITLE
"Selecionar essa página" não funciona

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#365]
Não está mais marcando todos os ítens da página.

![image](https://cloud.githubusercontent.com/assets/4059679/22938504/145a80b8-f2c3-11e6-8e0c-a6b491a92ae1.png)

**Comment by deandr** [comment]
@roblesedu 

Poderia verificar se este problema esta relacionado as últimas alterações realizadas no javascript da página?

Em específico encontrei alteração no código na linha do seletor relacionado a opção de "Selecionar esta página" em  https://github.com/scieloorg/search-journals/commit/542e4990800a0bcdbbe86fae97395b7c5aa5605c#diff-32b8b0cdccee34ae8d59fef28aa6ac19L424

Obrigado

**Comment by alexxxmendonca** [comment]
Testado e aprovado em homologação.
