### ISSUE TITLE
Links para SciELO Bolivia estão quebrados.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/search-journals#368]
Todos os links de artigos do SciELO Bolivia estão quebrados, aparentemente falta definir o domínio do SciELO Bolivia na ferramenta.

**Comment by deandr** [comment]
Favor adicionar uma nova entrada para a coleção dentro do elemento **scielo_urls** do arquivo de configuração **config.xml** disponível abaixo do diretório config/ da interface.

```
<scielo_urls>
   ...
   <bol>URL do site</bol>
</scielo_urls>
```
