### ISSUE TITLE
Falha na exportação de resultados de busca por e-mail

### ISSUE THREAD

**Issue by almeida-fabio** [scieloorg/search-journals#371]
Uma usuária entrou em contato conosco referente a um erro no Search. Ela nos informou que tentou enviar por e-mail os resultados de uma busca, mas não recebeu o e-mail.

Segue mensagem original da usuária:

Fábio, boa tarde!

Conforme conversamos ao telefone, envio 3 prints da tela referentes à inconsistência com a funcionalidade ENVIAR RESULTADO POR E-MAIL, na base SCIELO.

1) Resultado da busca;
2) Enviando resultado da busca SCIELO por e-mail
3) E-mail enviado

![resultado busca scielo](https://cloud.githubusercontent.com/assets/8592848/26560848/f0dfdf24-448f-11e7-8a53-25b9683cee8f.png)

![enviando resultado da busca scielo por e-mail](https://cloud.githubusercontent.com/assets/8592848/26560853/f6c80b28-448f-11e7-80d4-56cd06456071.png)

![e-mail enviado](https://cloud.githubusercontent.com/assets/8592848/26560856/f9f5ca88-448f-11e7-9a1f-287a0b5f5f22.png)

Após os procedimentos citados acima, verifica-se que o e-mail não chega ao destinatário.

Agradeço sua atenção e aguardo retorno,

Atenciosamente,

Sônia Paolinelli

**Comment by alexxxmendonca** [comment]
@deandr podemos resolver esse bug independente dos demais issues que estão parados?

**Comment by deandr** [comment]
@fabiobatalha 

Poderia nos auxiliar verificando se teve alguma alteração de infra relacionado ao servidor de email? 

Tivemos este problema no passado registrado em #39 e era relacionado a infra.

Verifiquei no histórico de alterações no sistema e não encontrei, a principio, alterações nesta funcionalidade.  

Obrigado

**Comment by fabiobatalha** [comment]
@rondinelisaad @deandr 

Avaliamos as configurações de e-mails e não houve nenhuma mudança.

**Comment by deandr** [comment]
@fabiobatalha 

Obrigado. 

Só para eu entender melhor, neste caso foi verificado os parâmetros do arquivo "config-mail.php" da interface em ambientes de homolog e produção e também a possibilidade de conexão via terminal ao servidor de email a partir do servidor da aplicação?

Grato.

**Comment by rondinelisaad** [comment]
@deandr <https://github.com/deandr>
Bom dia, o arquivo de configuração "config-mail.php" foi verificado e
fizemos testes de envio usando a configuração que está no arquivo.
Att,





* Rondineli SaadNetwork Administrator SciELO - Scientific Electronic
Library Online FAPESP - CNPq - BIREME - FapUNIFESP*
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639
<http://www.scielo.br>www.scielo.org | www.scielo.br


2017-08-23 11:26 GMT-03:00 deandr <notifications@github.com>:

**Comment by deandr** [comment]
@rondinelisaad 

Obrigado por confirmar. 

Poderia me enviar por email o arquivo  "error.log" da instância homolog.search.scielo.org e search.scielo.org da data de hoje?

Grato

**Comment by rondinelisaad** [comment]
@deandr <https://github.com/deandr>
segue em anexo os arquivos de log de erro.





* Rondineli SaadNetwork Administrator SciELO - Scientific Electronic
Library Online FAPESP - CNPq - BIREME - FapUNIFESP*
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639
<http://www.scielo.br>www.scielo.org | www.scielo.br


2017-08-23 12:15 GMT-03:00 deandr <notifications@github.com>:

**Comment by deandr** [comment]
@alexxxmendonca 

Revisado arquivo de configuração para o envio de emails. Favor validar no ambiente de homologação.

Obrigado

**Comment by alexxxmendonca** [comment]
@almeida-fabio você pode testar, por favor?

**Comment by almeida-fabio** [comment]
Testado e aprovado em:

https://homolog.search.scielo.org/
