### ISSUE TITLE
Limitar COUNT.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/search-journals#372]
O parâmetro count não tem limit máximo de registros, permitindo o usuário incluir qualquer valor na url e realizar a requisição para a aplicação.

valores superiores a 100 devem ser automaticamente redefinidos para o limite máximo de 100 documentos por página.

http://search.scielo.org/?q=*&lang=pt&**count=100**&from=-14&output=site&sort=&format=summary&fb=&page=0

**Comment by deandr** [comment]
@fabiobatalha 

Disponível no ambiente de homologação para validação. Quando possível favor validar.

Obrigado

**Comment by fabiobatalha** [comment]
@deandr testado OK.
