### ISSUE TITLE
Erro no botão de busca dentro da página do periódico

### ISSUE THREAD

**Issue by aline-cristina** [scieloorg/search-journals#373]
Ao clicar em "Buscar" dentro da página de um periódico é pesquisado automaticamente o caractere "*" o que dá erro em algumas pesquisas - Já aparece logo de cara que não foi encontrado nenhum resultado, ou aparece algum resultado especificamente para aquele caractere.

![errobusca](https://user-images.githubusercontent.com/26901197/27339931-88d3d0bc-55af-11e7-87aa-c818f3849e9b.png)

**Comment by deandr** [comment]
@fabiobatalha 

Seria possível liberar meu acesso ao ambiente citado neste ticket para que eu possa verificar como esta sendo feito a chamada ao form de pesquisa? Acredito que seja o ambiente de OPAC.

Obrigado

**Comment by fabiobatalha** [comment]
@jamilatta você pode verificar com @aline-cristina este problema, e indicar para o @deandr como reproduzir o problema no search.scielo.org.

**Comment by fabiobatalha** [comment]
@deandr @alexxxmendonca 

Testamos com diversas revistas do SciELO SP e não conseguimos reproduzir o erro. Vamos fechar por hora esse ticket.
