### ISSUE TITLE
Erro ao baixar lista de periódicos em CSV

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#376]
Quando selecionamos todos os periódicos na janela modal e escolhemos fazer o download em formato CSV, dá o seguinte erro:

**414 Request-URI Too Large**

![image](https://user-images.githubusercontent.com/4059679/27805849-6ebc7d9c-600d-11e7-825a-6cf4e5ae7a15.png)

**Comment by deandr** [comment]
@alexxxmendonca 

Ajuste disponível no ambiente de homologação para validação. Favor realizar refresh das páginas no browser devido a cache antes de testar.

Obrigado.

**Comment by alexxxmendonca** [comment]
A exportação deu certo 👍 

É possível alterar o nome do arquivo para algo mais descritivo, ao invés de "export_cluster"?

Além disso, é possível alterar as células do cabeçalho para "Journal title" e "Records" ao invés de "Label" e "Value".

Não sei se "Records" é um bom nome, se tiver outra sugestão é bem-vinda.

**Comment by deandr** [comment]
OK, obrigado pela validação.

Quanto as dúvidas acredito que seja possível sim, mas eu teria que ajustar no código do core do IAHX  para incorporar estas melhorias.

Como não se trata de um ajuste somente de configuração você poderia criar 2 issues separados para estas questões?

Obrigado.

**Comment by alexxxmendonca** [comment]
Ok! Vou fechar esse ticket então.
