### ISSUE TITLE
Restaurar foco para campo de busca após clicar no botão "limpar"

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#377]
Ao clicar no botão de "limpar", o foco sai do campo de busca, fazendo com que o usuário tenha que clicar no campo novamente para poder digitar a nova busca:

![image](https://user-images.githubusercontent.com/4059679/28177580-a2f0893e-67d1-11e7-8b93-249050c7bfe2.png)

Manter o foco no campo de busca, mesmo após clicar no botão de "limpar".

**Comment by cesarbruschetta** [comment]
@alexxxmendonca essa funcionalidade ja se encontra no ambiente de homologaçao https://homolog.search.scielo.org/

vc pode validar?

**Comment by alexxxmendonca** [comment]
@cesarbruschetta testado e aprovado em homologação.
