### ISSUE TITLE
Ajustar extensão de arquivo de RIS

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/search-journals#378]
Renomear arquivo de exportação de referências sob formato RIS de export.txt para export.ris.

Não existe nenhum problema na extensão .txt entretanto para melhorar a interface com o usuário, e para evitar problemas de entendimento sobre as características do arquivo e o seu objetivo, recomendamos que a extensão seja ajustada para .ris.

Nada deve ser mudado na estrutura do conteúdo do arquivo.

Listar o Gestor de Referências (CITAVI) na lista de gestores compatíveis.

**Comment by deandr** [comment]
@alexxxmendonca 

Este ajuste foi realizado e esta disponível no ambiente de homologação para validação. Favor, quando possível avaliar.

Grato.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em https://homolog.search.scielo.org
