### ISSUE TITLE
Adicionar a capacidade utilizamos https

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#379]
Devemos ter a capacidade do sistema rodar em https. 

Verificando o código acredito que seja uma alteração com arquivo de ambiente:  https://github.com/bireme/iahx-opac/blob/2.0/environment.php#L25.

**Comment by jamilatta** [comment]
Solicitado para a infraestrutura um ambiente com https em homologação para testes. :-)

**Comment by jamilatta** [comment]
@deandr 

Adicionamos https na aplicação de homologação.

**Comment by deandr** [comment]
Foi adicionado parâmetro no iahx-core para configurar o uso do protocolo https. 

Favor, quando possível, atualizar o iahx-core (git pull) no ambiente de homologação e adicionar o seguinte elemento no arquivo **config.xml**:
```
<use_https>true</use_https>
```
Obrigado.

**Comment by deandr** [comment]
@fabiobatalha 

Ajuste aplicado no ambiente de homologação. Quando possível favor validar para fechamento desta issue.

Obrigado

**Comment by fabiobatalha** [comment]
Testado OK @deandr
