### ISSUE TITLE
Erro na codificação dos termos de buscas realizados à partir de www.scielo.org

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/search-journals#388]
1. Acesse o site www.scielo.org 
2. No campo de pesquisa, entre com o termo _contextualização do saber_
3. Clique no botão _pesquisar_; a navegação será redirecionada para `https://search.scielo.org/?q=contextualiza%E7%E3o%20do%20saber&where=ORG`

Repare que a querystring foi codificada com o que parece ser codepoints Unicode: `U+00E7` e `U+00E3`, para `ç` e `ã` respectivamente, enquanto o padrão é que sejam utilizadas as representações hexadecimais do conjunto UTF-8, i.e., `https://search.scielo.org/?q=contextualiza%C3%A7%C3%A3o%20do%20saber&where=ORG`.

https://en.wikipedia.org/wiki/Percent-encoding

**Comment by gitnnolabs** [comment]
Suspeito que esse tíquete não seja mais válido. 

@alexxxmendonca poderia verificar, pelo que vi isso não acontece na nova versão do: www.scielo.org

**Comment by alexxxmendonca** [comment]
@gitnnolabs também não consegui reproduzir o problema. Estou fechando o ticket por este motivo.

**Comment by gitnnolabs** [comment]
👍
