### ISSUE TITLE
Não recupera artigo pelo título

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#410]
https://search.scielo.org/

Ao buscar por "Malaria on the Guiana Shield: a review of the situation in French Guiana" (título completo do artigo), a busca não traz nenhum resultado.

O artigo existe: https://new.scielo.br/article/mioc/2014.v109n5/525-533/#

**Comment by jamilatta** [comment]
Hum... nesse caso é necessário informar para o motor de busca que existe um caracter especial o **:**.

Esse atividades é conosco.

**Comment by alexxxmendonca** [comment]
Problema resolvido.
