### ISSUE TITLE
Direção do dropdown de métricas

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#413]
O menu dropdown de métricas nos resultados de busca, quando aberto enquanto a interface está no liminar do navegador, o menu abre para baixo, sendo necessário rolar a tela para baixo para ver o menu na íntegra:

![image](https://user-images.githubusercontent.com/4059679/49023297-1547cb00-f17e-11e8-962c-98a42efac7b0.png)

Pede-se um comportamento onde: quando a interface estiver no liminar do navegador -- tanto para cima, quanto para baixo -- abrir o menu dropdown na direção oposta (para cima ou para baixo), de modo a fazer com que o menu esteja sempre visível na íntegra.

**Comment by jamilatta** [comment]
@paratiuid 

Poderia por gentileza verificar esse ajuste!

**Comment by joffilyfe** [comment]
@alexxxmendonca você poderia verificar no ambiente de homologação se a solução implementada satisfaz os requisitos?

**Comment by alexxxmendonca** [comment]
Testado e aprovado em homologação.

**Comment by jamilatta** [comment]
@alexxxmendonca 

Iremos atualizar o ambiente de produção no dia 18/02/2019
