### ISSUE TITLE
Métricas a nível do periódico

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#414]
Atualmente ao clicar no título do periódico nos resultados de busca, abre-se um modal com o ISSN e link para SciELO Analytics.

![image](https://user-images.githubusercontent.com/4059679/49025783-850c8480-f183-11e8-826c-b4c349182453.png)

Esse comportamento deve ser alterado. Ao clicar no título, abre-se um menu dropdown com o mesmo comportamento do botão de métricas do artigo. Esse menu deve conter: 

- Sobre o periódico (conteúdo a definir, porém por ora, abrir a janela modal em uso atualmente); About the journal; Acerca de la revista 
- SciELO Analytics
- ScienceOpen
- PlumX
- ...
- (Outros índices)

**Comment by paratiuid** [comment]
@alexxxmendonca 
seria algo nessa linha?

![ajuste - scielo - opac - 414](https://user-images.githubusercontent.com/22373640/50787068-7e058580-129c-11e9-90ce-5eaccd7be026.jpg)

**Comment by alexxxmendonca** [comment]
@paratiuid isso mesmo, mas teria como incluir os ícones? Salvo o primeiro (sobre o periódico), todos têm ícones.

**Comment by paratiuid** [comment]
![icones-menuzinho](https://user-images.githubusercontent.com/22373640/50846316-fc722e00-1355-11e9-99b1-d50b2caac5a6.jpg)

assim?

**Comment by alexxxmendonca** [comment]
@paratiuid sim, isso mesmo!

**Comment by paratiuid** [comment]
@alexxxmendonca 

estou com dúvidas nessa atividade.

Tentei colocar as méticas Dimension e PlumX a nível de periódico, porém não possuo o parâmetro "doi", necessário para renderizar a métrica.

Consultei a @patymori a respeito dessa dúvida e ela comentou que esse parâmetro "doi" existe somente a nível de artigo.

Sendo assim, lhe questiono:

Devo mesmo manter essas estatísticas Dimension e PlunX a nível de periódico?
Se sim, como deve ser feito? Quais parâmetros usar? Pois os templates que temos ativos no sistema exigem este parâmetro.

Aguardo.

**Comment by alexxxmendonca** [comment]
@paratiuid Entendo.

Eu vou ter que pesquisar sobre como lidaremos nesse caso.

Deixe esse ticket de lado por ora, ok?

**Comment by paratiuid** [comment]
@alexxxmendonca Ok.

**Comment by paratiuid** [comment]
@alexxxmendonca 
conforme conversamos, vou enviar o ajuste sem estes dois itens. Apenas com o Analytics que funciona pois utiliza outros parâmetros, já existente na tela.

**Comment by alexxxmendonca** [comment]
de acordo!

**Comment by cesarbruschetta** [comment]
@alexxxmendonca , vc pode validar as alterações na Homologação
https://homolog.search.scielo.org/

**Comment by alexxxmendonca** [comment]
@cesarbruschetta ao clicar no link "SciELO Analytics", não parece levar para a página do periódico, mas sim uma página "genérica" do Analytics.

O ISSN do periódico até aparece na URL mas o conteúdo é sempre igual, não importa o ISSN.

**Comment by cesarbruschetta** [comment]
@alexxxmendonca , vc pode verificar o link para a pagina do "SciELO Analytics" na Homologação
https://homolog.search.scielo.org/

**Comment by cesarbruschetta** [comment]
> @cesarbruschetta ao clicar no link "SciELO Analytics", não parece levar para a página do periódico, mas sim uma página "genérica" do Analytics.
> 
> O ISSN do periódico até aparece na URL mas o conteúdo é sempre igual, não importa o ISSN.

@alexxxmendonca , vc pode verificar o link para a pagina do "SciELO Analytics" na Homologação
https://homolog.search.scielo.org/

**Comment by alexxxmendonca** [comment]
@cesarbruschetta agora sim! Testado e aprovado em homologação.

**Comment by cesarbruschetta** [comment]
@jamilatta @alexxxmendonca 
Iremos atualizar o ambiente de produção no dia 18/02/2019, junto com o ticket #413

**Comment by cesarbruschetta** [comment]
@alexxxmendonca A gente atualizou o ambiente de produção do http://search.scielo.org, vc consegue verificar se esta tudo ok?

**Comment by alexxxmendonca** [comment]
@cesarbruschetta tudo certo! testado e aprovado em produção.
