### ISSUE TITLE
Fascículos de 2018 v51 n[10, 11, 12] BJMBR não estão indexados.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#415]
É necessário avaliar a atualização dos metadados no (https://search.scielo.org).

**Comment by jamilatta** [comment]
Realizei o cadastro de todos os artigos do periódico em outro índice para verificar se o article meta esta retornando todos os artigos.

http://api-search.scielo.org/iahx-controller/?site=solr%2Fscielo-test&count=15&output=site&lang=pt&sort=da+desc&op=search&q=%2A&start=315&fq=journal_title%3A%28%22Brazilian+Journal+of+Medical+and+Biological+Research%22%29

**Comment by jamilatta** [comment]
@ednilson 

Poderia gerar uma lista de **PID** para o periódico: **0100-879X**

**Comment by ednilson** [comment]
@jamilatta 

Anexo a lista solicitada.
[pids_0100-879X.txt](https://github.com/scieloorg/search-journals/files/2648432/pids_0100-879X.txt)

Gerei a lista com o comando abaixo:

> mx artigo "HR=S0100-879X$" "pft=v880/" now > pids_0100-879X.txt

Resultou em 4131 registros.

**Comment by jamilatta** [comment]
Show @ednilson 

Muito obrigado.

**Comment by jamilatta** [comment]
O AM está retornando **4073** registros.

Estou avaliando o motivo!

**Comment by jamilatta** [comment]
Sobre os artigos do fascículo 2018 V51 N1, todos os artigos foram cadastrados.

**Comment by jamilatta** [comment]
Agora precisamos avaliar o fascículo **2018 V51 N11** e **2018 V51 N12**.

**Comment by jamilatta** [comment]
Dados cadastrado.

BJMBR: **4 135**
