### ISSUE TITLE
Ausência de Sponsors no dados indexados.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#416]
O registro do documento de PID S1677-04202005000100013 [1] no Solr[2] não possui conteúdo no índice sponsor, embora o registro no articlemeta possua o conteúdo no campo v58[3]. 

[1]http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1677-04202005000100013
[2]http://api-search.scielo.org/solr/scielo-articles/select?q=pid%3AS1677-04202005000100013&wt=json&indent=true
[3]http://articlemeta.scielo.org/api/v1/article/?collection=scl&code=S1677-04202005000100013

**Comment by jamilatta** [comment]
@gustavofonseca 

Lembro que foi você que me notificou sobre a ausência dos financiadores! 

Aonde deveria aparece os financiadores na interface de pesquisa? 

Veja o primeiro artigo, no indexador o dado de sponsor está presente, porém não sei onde deveria aparecer:

<img width="1258" alt="screenshot 2018-12-14 09 52 58" src="https://user-images.githubusercontent.com/373745/50002234-8eb92900-ff86-11e8-9d93-120b3c3b0a17.png">

Se for como cluster não adicionarmos por não ser uma dados normalizado.

**Comment by gustavofonseca** [comment]
O nome do financiador não deve aparecer na interface, mas apenas deve ser pesquisável por meio do índice _sponsor_

**Comment by jamilatta** [comment]
@gustavofonseca 

Acredito que possamos fechar esse ticket considerando que o artigo está sendo retornado quando pesquisamos por **fapesp** no campo sponsor.

Repare: 

https://search.scielo.org/?q=%28sponsor%3A%28fapesp%29%29&lang=pt&count=15&from=0&output=site&sort=&format=summary&fb=&page=1&q=%28sponsor%3A%28fapesp%29%29+AND+Metabolism+and+root+exudation+of+organic+acid+anions+under+aluminium+stress&lang=pt&page=1

* Adicionei um **AND** somente para irmos direto ao artigo.

**Comment by gustavofonseca** [comment]
valeu @jamilatta
