### ISSUE TITLE
Botão de filtro deve acompanhar rolagem da página

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#427]
O botão "Filtrar", que aparece junto aos clusters, deve acompanhar a rolagem da página, para que o usuário não tenha que voltar ao topo da tela para aplicar os novos filtros.

**Comment by gustavofonseca** [comment]
Resolvido em 9b3e3e9

**Comment by gustavofonseca** [comment]
Reabrindo por ter esquecido de pedir que o desenvolvimento seja homologado.

**Comment by gustavofonseca** [comment]
@alexxxmendonca, poderia, por gentileza, verificar em https://homolog.search.scielo.org?

**Comment by alexxxmendonca** [comment]
Testado e aprovado em homologação.
