### ISSUE TITLE
Mal funcionamento do recurso "Itens selecionados" 

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#428]
O recurso "Itens selecionados" não está funcionando corretamente e precisa ser revisto.

Ver: https://drive.google.com/file/d/1R8y4IiMg46shJSIayV4NodJmRSgGkvwF/view

**Comment by paratiuid** [comment]
@alexxxmendonca 

Segue o video com o teste do ajuste funcionando:
https://drive.google.com/open?id=1e99XY8CPAt1dgFFNXqZV2X9cWmqYScXP

**Comment by alexxxmendonca** [comment]
@paratiuid preciso de permissão para acessar o arquivo. Fiz um pedido.

**Comment by paratiuid** [comment]
@alexxxmendonca acabei de lhe dar a permissão. Caso volte a ter problemas pode me chamar direto no hangout e resolvemos na hora.

**Comment by alexxxmendonca** [comment]
@paratiuid me parece ok! Pode enviar o PR?

**Comment by paratiuid** [comment]
@alexxxmendonca já foi enviado.

**Comment by cesarbruschetta** [comment]
Devido a um problema encontrado no DNS Interno da Scielo, não eh possível testar a busca do [homolog.search.scielo.org](http://homolog.search.scielo.org), assim que o problema for solucionado sera continuar a tarefa

**Comment by cesarbruschetta** [comment]
@alexxxmendonca , por favor, vc pode validar esse ticket em homolog https://homolog.search.scielo.org/

**Comment by alexxxmendonca** [comment]
@paratiuid ainda há inconsistências, veja:

https://drive.google.com/file/d/1wXE-SshKJZhWBS5fQEBLbJfTAUEAlgO8/view

**Comment by paratiuid** [comment]
@alexxxmendonca @cesarbruschetta 

Pessoal, 
testei a homolog do search e realmente vi que o problema persiste.

Ao testar diretamente na branch que foi efetuado o ajuste, o problema não ocorre.

Teríamos como comparar os arquivos da branch com os arquivos que estão na homologação?

Será que o problema de DNS pode estar afetando esses arquivos?

Aguardo.

**Comment by paratiuid** [comment]
@alexxxmendonca @cesarbruschetta 

Fiz outro teste aqui.

Abri lado a lado o arquivo main.js da homologação com o main.js da branch e encontrei diferenças.

Vejam a imagem abaixo:
![Screen Shot 2019-06-12 at 2 46 05 PM](https://user-images.githubusercontent.com/22373640/59373934-122eb980-8d21-11e9-9b1f-e9079196f3d5.png)

**Comment by cesarbruschetta** [comment]
@alexxxmendonca @paratiuid , de fato o ambiente de homologação não estava totalmente atualizado, 
Agora sim, peço que o Alex valide. https://homolog.search.scielo.org/, :grin:

**Comment by alexxxmendonca** [comment]
@cesarbruschetta testado e aprovado em homologação.
