### ISSUE TITLE
Alterar modo de apresentação dos links de acesso ao documento

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#429]
Alterar modo de apresentação dos links de acesso ao documento de modo que a referência passe a ser o tipo de documento e não o idioma:

![image](https://user-images.githubusercontent.com/4059679/55476066-f35acb00-55eb-11e9-9628-016daadca7e6.png)

Exemplo:

**Resumo:** Português | Inglês | Espanhol      **Texto:** Português | Inglês | Espanhol     **PDF:** Português | Inglês | Espanhol    **ePDF:** Português | Inglês | Espanhol

Lembrando que o Resumo deve-se manter o mesmo comportamento atual, ou seja, colapsar e expandir na mesma página.

**Comment by paratiuid** [comment]
@alexxxmendonca 

Segue o link do invision, com o protótipo clicável.
https://invis.io/G6NEJUZ73MH#/358251474_resumo_01

No protótipo, apenas a opção Rasumo > Inglês está funcionando.

Veja se é suficiente para entender a interação.

**Comment by alexxxmendonca** [comment]
@paratiuid Mostrei para o Abel e ele informou que esse comportamento do drop-down deve acontecer somente quando houver mais de um idioma.

Se o documento está disponível somente em um idioma, esse link deve aparecer direto na interface, economizando um clique.

**Comment by paratiuid** [comment]
@alexxxmendonca 

Abaixo coloquei uma imagem da listagem no search e das ações, Resumo, Texto e PDF.
Cada item da listagem representa um estado.

![itens-lista-search](https://user-images.githubusercontent.com/22373640/56305744-31410e80-6117-11e9-8150-49b07383aefb.jpg)


O primeiro e último itens, representam como é hoje.
Vemos claramente que no caso de haver mais de um idioma disponível, o bloco de informação é repetido na tela, antecedido de uma legenda que indica o idioma.

Nesse exemplo, posso citar algumas leis (do design) para defender minha opinião:

1 - Lei de Hick: O tempo que leva para se tomar uma decisão aumenta com o número de decisões que precisam ser tomadas e suas complexidades.

Ao ver mais de uma vez o link resumo, eu demoro a saber qual se trata de cada idioma.
Se houvesse somente uma opção, eu clicaria mais rapidamente.

2 - Princípio de pareto ou regra dos 80/20: Em qualquer grande sistema, uma alta percentagem de efeitos é causada por uma baixa porcentagem de variáveis.

Primeiramente, vemos a opção que desejamos na tela. Clicamos, e os detalhes dela se revelam. Não preciso dos detalhes se não houver interesse pela opção.


Após uma conversa com o Alex, tive o retorno que dizia que somente em caso de haver mais de um idioma, deve aparecer o dropdown na tela.

Isso acarretaria em termos duas formas diferentes de mostrar a mesma informação.

Observe:

Caso haja somente um idioma, a interface exibe:
a)legenda do idioma em questão
b)link para a ação

Caso haja mais de um idioma:
a) link para a ação
b) dropdown com as variantes da ação.


Duas ou mais formas de exibir o mesmo dado, no design de interfaces, chamamos de inconsistência. E isso não é algo desejável.
Eu proponho manter a interface uniforme e genérica no que diz respeito a forma de exibição das informações.
Veja imagem abaixo:

![item-proposto-novo](https://user-images.githubusercontent.com/22373640/56305483-c5f73c80-6116-11e9-99f9-beccb67bf066.jpg)


Nesse modelo sempre teremos a interface sendo exibida da mesma forma:

Sempre haverá o link para a ação com o dropdown que exibe a quantidade de idiomas disponíveis.
Perceba que o detalhe da ação só fica visível quando há o interesse.
Com isso tiramos um elemento visual da tela e reduzimos o esforço cognitivo da decisão de clique.


Acredito ter entendido o ponto do Sr. Abel ao pedir que os idiomas venham abertos na tela.
Imagino que esse pode ser um fator de eliminação ao selecionar o artigo.


Em conversa interna aqui na empresa, chegamos a um consenso de que um acadêmico, mestrando, doutorando, deva ter um nível maior de entendimento de outros idiomas. Sendo assim, o idioma acaba não sendo impeditivo, na escolha do artigo.
Esta é a nossa forma de entender o público acadêmico. Vocês, como especialistas, com certeza tem uma opinião também.

O que pretendemos aqui é pegar o melhor dos dois mundos e criar uma interface com o melhor do design e totalmente de acordo com o público acadêmico.


Caso optemos por exibir todas as opções em tela, penso que estas, devam ter um lugar específico no layout.
Da maneira como está hoje, as informações estão sempre aglutinadas. Não existe uma padronização de colunagem. A leitura ainda é onerosa.

Outro ponto importante que podemos pensar é em utilizar tags de controle de eventos do google analytics. Com isso saberemos se esses links são muito ou pouco utilizados.

**Comment by alexxxmendonca** [comment]
@paratiuid apesar da justificativa e embasamento teórico, a proposta não foi aprovada.

Peço que façam duas propostas:

a) usando bandeiras dos idiomas (Brasil para PT e Reino Unido para EN)
b) usando o código ISO dos idiomas.

**Comment by paratiuid** [comment]
@alexxxmendonca 
seguem os prototipos solicitados:


Bandeiras:
![search-lista-bandeiras](https://user-images.githubusercontent.com/22373640/56529432-1b708680-6527-11e9-8e97-768d22863f8b.jpg)



ISO:
![search-lista-ISO](https://user-images.githubusercontent.com/22373640/56529464-262b1b80-6527-11e9-8f1b-ab7734c94957.jpg)


Em ambas as versões:

Na primeira linha, todos estão ativos.
Na segunda, apenas inglês inativo.
Na terceira, apenas português inativo.

**Comment by alexxxmendonca** [comment]
@paratiuid por favor, atualize os mockups para uma versão que não tenha os links acinzentados.

Os idiomas dos nossos documentos não são somente PT, EN e ES. Temos documentos em Italiano, Alemão, idiomas africanos etc

Colocar sempre os 3 pode dar a entender que são somente esses 3 e que os cinzas estão "faltando" ou fora do ar.

Por gentileza então, refaça deixando somente os links ativos.

**Comment by paratiuid** [comment]
@alexxxmendonca 

Seguem os ajustes:

![search-lista-bandeiras-2](https://user-images.githubusercontent.com/22373640/56591586-60e09280-65bf-11e9-9324-9f388d3b6ebe.jpg)


![search-lista-ISO-2](https://user-images.githubusercontent.com/22373640/56591626-705fdb80-65bf-11e9-9eba-df79f6c2d796.jpg)

**Comment by alexxxmendonca** [comment]
A versão ISO foi aprovada com uma ressalva: mostrar o idioma por extenso via tooltip de acordo com a interface, quando houver comportamento de mouse over.

Essas mudanças serão aplicadas no sumário do site da Coleção também. Tenham isso em mente.

**Comment by cesarbruschetta** [comment]
Ja esta no ambiente de homologação https://homolog.search.scielo.org

**Comment by cesarbruschetta** [comment]
> Ja esta no ambiente de homologação https://homolog.search.scielo.org

@carolinatanigushi, vc consegue validar esse ticket no ambiente de homologação

**Comment by carolinatanigushi** [comment]
@cesarbruschetta Percebi que quando o artigo não tem resumo, o resumo ainda aparece listado mas, ao clicar, não aparece nada. Deveria aparecer o resumo na listagem nesses casos?

![csp](https://user-images.githubusercontent.com/12699183/61740739-c599bd80-ad65-11e9-8d7f-19e9c20c605d.png)

**Comment by cesarbruschetta** [comment]
@carolinatanigushi o Problema é que esse artigo especifico nao tem resumo, acredito que isso eh um novo bug, por favor pode abrir um ticket sobre isso

**Comment by carolinatanigushi** [comment]
@cesarbruschetta foi aberto o ticket #443 para tratar do problema do resumo. Fora isso, está tudo certo.
