### ISSUE TITLE
Falha ao buscar por título do artigo

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#434]
Ao buscar pelo título do artigo "Dengue em criança: aspectos clínicos e epidemiológicos, Manaus, Estado do Amazonas, no período de 2006 e 2007", não retorna nenhum resultado.

Entretanto, esse artigo está indexado:

![image](https://user-images.githubusercontent.com/4059679/57639044-6e1ceb80-7585-11e9-82dc-30f0b60df2d4.png)

https://search.scielo.org/?q=%28ta%3A%28Revista+da+Sociedade+Brasileira+de+Medicina+Tropical%29%29&lang=pt&count=15&from=136&output=site&sort=&format=summary&fb=&page=10&filter%5Byear_cluster%5D%5B%5D=2009

**Comment by jamilatta** [comment]
@alexxxmendonca 

Acredito que agora o artigo esteja funcionando, veja: 

https://search.scielo.org/?q=%28ta%3A%28Revista+da+Sociedade+Brasileira+de+Medicina+Tropical%29%29&lang=pt&count=15&from=1&output=site&sort=&format=summary&fb=&page=1&q=Dengue+em+crian%C3%A7a%5C%3A+aspectos+cl%C3%ADnicos+e+epidemiol%C3%B3gicos%2C+Manaus%2C+Estado+do+Amazonas%2C+no+per%C3%ADodo+de+2006+e+2007&lang=pt&page=1

**Comment by alexxxmendonca** [comment]
@jamilatta acho que o problema persiste.

Copie e cole o título do artigo e faça a busca.

**Comment by jamilatta** [comment]
@alexxxmendonca 

hum....

Nesse caso estamos com um problema diferente....

Estamos com um problema nos temos que estamos realizando a pesquisa no indexador, note que nessa sequência de termos que estamos utilizando, temos a presença do operador "**:**" o que indica algo diferente para o indexador (**:** para o indexador é uma caracter especial, veja: https://lucene.apache.org/solr/guide/6_6/the-standard-query-parser.html). 

Sequência de temos que estamos utilizando para realizar a pesquisa: 

_Dengue em criança\: aspectos clínicos e epidemiológicos, Manaus, Estado do Amazonas, no período de 2006 e 2007_

Isso implica no resultado vazio que estamos recebendo. 

Estou pesquisando uma forma de resolver isso!

Verifiquei que o gmail resolve isso, ao pesquisar na caixa de pesquisa do gmail uma sequência termos que contenha  **:** os registro que satisfazem a pesquisa são retornado.

**Comment by jamilatta** [comment]
@alexxxmendonca 

Realizamos os ajustes poderia verificar no ambiente de homologação: https://homolog.search.scielo.org/

A sequência de termos iniciais que produziram esse ajuste: **Dengue em criança: aspectos clínicos e epidemiológicos, Manaus, Estado do Amazonas, no período de 2006 e 2007**

**Comment by alexxxmendonca** [comment]
Testado e aprovado https://homolog.search.scielo.org/

**Comment by jamilatta** [comment]
Registrando a solução desse caso, segue: 

As configurações padrão do indexador utilizava uma avaliação dos termos chamado **[Standard Query Parser](https://lucene.apache.org/solr/guide/6_6/the-standard-query-parser.html)**

Com esse "Parser" é necessário que o usuário/aplicação tenha a capacidade de identifica os caracteres [especiais](https://lucene.apache.org/solr/guide/6_6/the-standard-query-parser.html#TheStandardQueryParser-EscapingSpecialCharacters), para considera-lós ou não na pesquisa.

Portanto para que possamos pesquisa por: `(1+1):2` é necessário digitarmos, algo como: `\(1\+1\)\:2`.

A visão geral da documentação indica as várias forma de interpretar os termos e parâmetros das pesquisas, veja: https://lucene.apache.org/solr/guide/6_6/overview-of-searching-in-solr.html 

O Standard Query Parser permite um grande precisão nas pesquisas, o que resulta no nosso problema.

Para deixar a pesquisa mais tolerante passamos a utilizar o [eDisMax - Extensible Maximum Disjunction](https://lucene.apache.org/solr/guide/6_6/the-extended-dismax-query-parser.html#the-extended-dismax-query-parser).

Para entender melhor sobre Maximum Disjunction, ver: https://lucene.apache.org/solr/guide/6_6/the-dismax-query-parser.html#the-dismax-query-parser

**Comment by jamilatta** [comment]
@alexxxmendonca 

Este item está em ambiente de produção poderia validar novamente nesse ambiente para que possamos fechar o ticket!

**Comment by alexxxmendonca** [comment]
Testado e aprovado em produção!

Estou fechando o ticket.
