### ISSUE TITLE
Histórico de busca - Retorna registros aleatórios.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#435]
No dia 13/05/2019 um usuário reportou um comportamento inesperado da interface de pesquisa do SciELO: https://search.scielo.org. 

Mais precisamente no histórico de busca. 

<img width="475" alt="Screenshot 2019-05-14 10 36 31" src="https://user-images.githubusercontent.com/373745/57702298-299c5900-7634-11e9-87c2-df10122638b7.png">

A cada clique no link "Histórico de busca" a lista retorna itens distintos.

**Comment by jamilatta** [comment]
Suspeito que pelo fato de estarmos utilizando vários **containers** para responder pela aplicação, estamos retornando sessão distintas de servidores diferentes.

Proponho que devemos armazenar as sessões de forma única para evitarmos tal consequência.

Para isso existe algumas opções: 

- Armazenar no disco
- Armazenar em um banco de dados

**Comment by jamilatta** [comment]
Baixamos para 1 a quantidade de containers e evitamos o problema. 

De qualquer forma essa melhoria impedi que a aplicação seja escalada.

**Comment by alexxxmendonca** [comment]
@jamilatta esse problema foi resolvido?

Em caso positivo, poderia documentar a solução?

**Comment by jamilatta** [comment]
@alexxxmendonca 

A solução para esse problema esta descrito do comentário acima, porém a infra-estrutura utilizou de outro recursos que também não tenho conhecimento.

**Comment by alexxxmendonca** [comment]
@jamilatta Ok.

A julgar que você foi quem abriu o ticket, você acha que pode fechá-lo?

**Comment by jamilatta** [comment]
Sim sim podemos fechar!

**Comment by elton557** [comment]
Bom dia,
A solução foi configurar um stickenes no Rancher com metodo de insert, o arquivo está versionado no git lab no seguinte link: https://gitlab.scielo.org/devops/devops-deploys/blob/master/RANCHER/PRODUCAO-SCIELO/Search-SciELO/rancher-compose.yml, Segue o print da mudança.

![image](https://user-images.githubusercontent.com/52458645/69816381-02c00180-11d7-11ea-8d0d-954013d36041.png)
