### ISSUE TITLE
Compatibilizar logo SciELO

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#437]
Compatibilizar o logo SciELO (imagem e texto/legenda) com os demais sites SciELO (Portal SciELO.org e SciELO Brasil).

Ticket relacionado: https://github.com/scieloorg/scielo.org/issues/75

**Comment by paratiuid** [comment]
@alexxxmendonca 

segue o comparativo entre o antigo e o novo:

Antigo Home:
![Screen Shot 2019-06-17 at 5 17 05 PM](https://user-images.githubusercontent.com/22373640/59633940-03cb0e00-9124-11e9-8331-d2e532848055.png)

Novo Home:
![Screen Shot 2019-06-17 at 5 17 19 PM](https://user-images.githubusercontent.com/22373640/59633996-23facd00-9124-11e9-9703-44cb78d520e6.png)


Antigo Lista:
![Screen Shot 2019-06-17 at 5 17 30 PM](https://user-images.githubusercontent.com/22373640/59634031-337a1600-9124-11e9-82b0-5eb110cdd48e.png)

Novo Lista:
![Screen Shot 2019-06-17 at 5 17 38 PM](https://user-images.githubusercontent.com/22373640/59634048-3e34ab00-9124-11e9-9197-b9062273f0c1.png)

Aguardo aprovação

**Comment by alexxxmendonca** [comment]
@paratiuid aprovado.

**Comment by cesarbruschetta** [comment]
@alexxxmendonca , vc poderia testar no https://homolog.search.scielo.org/

**Comment by alexxxmendonca** [comment]
@cesarbruschetta testado e aprovado em homologação.

**Comment by alexxxmendonca** [comment]
@cesarbruschetta testado e aprovado em homologação.
