### ISSUE TITLE
Retirar/desabilitar a integração com Readcube

### ISSUE THREAD

**Issue by patymori** [scieloorg/search-journals#442]
O serviço de ePDF, integração com a _Readcube_, não deve mais aparecer nos resultados das buscas.

![Screen Shot 2019-07-16 at 09 22 20](https://user-images.githubusercontent.com/18053487/61294302-e41f1800-a7ab-11e9-8f08-4aea3629e073.png)

**Comment by alexxxmendonca** [comment]
Testado e aprovado em homologação.

**Comment by alexxxmendonca** [comment]
Aplicado em produção.
