### ISSUE TITLE
Desacoplar o Bootstrap do projeto Search-journals

### ISSUE THREAD

**Issue by paratiuid** [scieloorg/search-journals#451]
Da mesma forma que foi feito no projeto Opac, o projeto Search Journals deve ser desvinculado do bootstrap.

O bootstrap deve ser carregado via NPM.

**Comment by jamilatta** [comment]
@alexxxmendonca 

Poderia validar esse ajuste no ambiente de homologação: https://homolog.search.scielo.org

**Comment by alexxxmendonca** [comment]
@jamilatta eu não tenho como avaliar sob o aspecto técnico uma vez que me falta o conhecimento necessário para tal.

Verifiquei apenas superficialmente sob a perspectiva de um usuário comum e aparentemente está tudo certo.

O ideal seria uma pessoa que entendesse do assunto validar esse ticket sob o aspecto técnico.

**Comment by jamilatta** [comment]
@alexxxmendonca 

Sim sobre o aspecto técnico já esta aprovado por nos da TI.

Grato!
