### ISSUE TITLE
Tornar o Search SciELO Responsivo

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#452]
Tornar o site Search SciELO responsivo para as diversas interfaces de diferentes dispositivos.

### Descrição da nova funcionalidade
Eu, como **usuário de smartphone ou dispositivo mobile**, gostaria que **a interface do site Search SciELO se adequasse ao meu dispositivo para uma melhor navegabillidade**, então **a interface do Search SciELO deve ser responsiva**.

### Critérios de aceitação

- Responsivo nos principais navegadores e sistemas operacionais de dispositivos móveis.
- Responsivo em navegadores desktop ao redimencionar o tamanho da janela.

### Anexos
N/A

### Referências
N/A

**Comment by robertatakenaka** [comment]
@alexxxmendonca conseguiria completar este ticket?

**Comment by paratiuid** [comment]
@gustavofonseca @jamilatta 

este ticket está parado pois depende do andamento deste outro:
https://github.com/scieloorg/search-journals/issues/455

**Comment by alexxxmendonca** [comment]
@robertatakenaka completado.

**Comment by robertatakenaka** [comment]
@alexxxmendonca nós sentimos falta de como ficaria isso visualmente. Pergunto isso porque abri em meu celular e digamos que superficialmente já está responsivo.
Então, as questões são:

- quais são os elementos que devem aparecer no celular?
- como eles devem aparecer?
- há algum problema já identificado em algum Sistema Operacional?
- etc

**Comment by alexxxmendonca** [comment]
@robertatakenaka não tenho ideia em como responder esses pontos.

O ticket foi feito para solicitar uma proposta à Parati. O SciELO como cliente aguarda uma proposta da empresa de soluções de design, Parati.

**Comment by robertatakenaka** [comment]
@alexxxmendonca você quer dizer uma proposta de layout? Proposta de como ficaria as telas?

**Comment by alexxxmendonca** [comment]
@robertatakenaka sim.

**Comment by robertatakenaka** [comment]
@paratiuid entregar um Wireframe da lista dos resultados

**Comment by paratiuid** [comment]
Pessoal, 
conforme falamos hoje cedo na daily, segue o pdf contendo os wireframes do search mobile.

Nele, incluí 3 versões distintas para a tela de resultados da busca.
Aguardo os comentários de vcs.

[search-journals-mobile-wireframe-v2.pdf](https://github.com/scieloorg/search-journals/files/3988481/search-journals-mobile-wireframe-v2.pdf)

**Comment by alexxxmendonca** [comment]
@paratiuid vou analisar com calma na volta do recesso.

Por ora, você saberia indicar se alguma função ou recurso não está disponível na versão responsiva? Ou é seguro afirmar que todas as funções e recursos da versão desktop são, de uma maneira ou de outra, reproduzidas na versão responsiva?

**Comment by paratiuid** [comment]
> @paratiuid vou analisar com calma na volta do recesso.
> 
> Por ora, você saberia indicar se alguma função ou recurso não está disponível na versão responsiva? Ou é seguro afirmar que todas as funções e recursos da versão desktop são, de uma maneira ou de outra, reproduzidas na versão responsiva?

Acredito ter conseguido manter todas as funcionalidades contidas na versão desktop, nessa proposta para o mobile.

**Comment by paratiuid** [comment]
Pessoal, 
@alexxxmendonca @gustavofonseca 

segue o novo pdf com as telas ajustadas conforme solicitado na apresentação dos wireframes:
[search-journals-mobile-wireframe-aprovados.pdf](https://github.com/scieloorg/search-journals/files/4031125/search-journals-mobile-wireframe-aprovados.pdf)

**Comment by alexxxmendonca** [comment]
@paratiuid para mim está ok, mas uma coisa que pensei agora: não teria como a janela de filtros ocupar 3/4 da tela, ao invés da tela toda?

@gustavofonseca por favor dê o seu parecer assim que possível.

**Comment by paratiuid** [comment]
> @paratiuid para mim está ok, mas uma coisa que pensei agora: não teria como a janela de filtros ocupar 3/4 da tela, ao invés da tela toda?
> 
> @gustavofonseca por favor dê o seu parecer assim que possível.

Oi @alexxxmendonca 

eu não vejo sentido em deixar a janela de filtros menor do que a tela, sendo que temos muitos filtros.
Verifiquei a referência que você havia citado, o app do Quinto andar. Ali, pelo que vi os filtros aparecem inicialmente exibindo apenas duas opções, no caso Valor de aluguel e número de quartos. Para o ramo imobiliário, acredito que possa fazer sentido exibir esses dois campos como principais e mais utilizados.
Na sua opinião existem campos nos filtros do search que seriam os principais e justificariam aparecer primeiro do que os outros?

**Comment by alexxxmendonca** [comment]
@paratiuid não sei se me expressei bem, eu quis dizer 3/4 da tela na horizontal. Verticalmente pegaria a tela toda. Seria só para o usuário ter uma noção de "barra lateral", semelhante até ao desktop. Como está atualmente ocupa a tela toda. Até mesmo se o usuário quiser "deslizar o dedo para a esquerda" a barra de filtros poderia sumir.

O exemplo do Quinto Andar foi só mesmo um exemplo, Não acho que vem ao caso escolhermos filtros principais.

**Comment by paratiuid** [comment]
@alexxxmendonca 
acho que entendi seu ponto. Mas discordo.

A tela do celular já é bem pequena, e "afinar", "deixar mais estreita" a interface não sei se ajudaria em algum sentido.

Podemos analisar referências, ver casos existentes ...

Pessoalmente, penso em seguir o simples.

**Comment by alexxxmendonca** [comment]
![be5bdb9a-6121-4f0b-bd2b-c352120167a9](https://user-images.githubusercontent.com/4059679/71986228-de5e3880-320a-11ea-8dca-ed0a8c535855.jpg)

No exemplo acima, o usuário pode sair da tela de filtro clicando na área fora, por exemplo.

Quais as opções de "sair" do filtro na proposta de vocês?

**Comment by paratiuid** [comment]
![tela-filtros](https://user-images.githubusercontent.com/22373640/71987073-45302180-320c-11ea-9df7-b61a9b630fc8.png)

No modelo proposto temos a opção 1, em verde, na imagem. Que aplica o filtro e retorna a listagem de resultados filtrados.

E temos a opção 2, em vermelho, na imagem. Que retorna para a tela anterior sem aplicar filtro algum.

Algo semelhante a essa tela abaixo:
![filtro-olx](https://user-images.githubusercontent.com/22373640/71987441-f33bcb80-320c-11ea-8617-43786e86ff5e.png)

**Comment by alexxxmendonca** [comment]
@paratiuid ok, então a opção de voltar é fixa no scrolling?

**Comment by paratiuid** [comment]
> @paratiuid ok, então a opção de voltar é fixa no scrolling?

Ela é fixa no topo. Toda a página rola, mas ela fica sempre visível.
O mesmo ocorre com o botão Filtrar. Enquanto houver rolagem, ele aparece flutuante, fixo na parte inferior da tela.
Ao rolar a tela até o fim, o botão filtrar passa a ocupar 100% da largura da tela.

Veja exemplos abaixo:

Tela 01: Nesse caso existe rolagem. Verifique que o botão filtrar está sobre alguns filtros. Portanto ele é flutuante e não ocupa toda a largura da tela. E o botão voltar está fixo no topo.
![filtro-olx-flutuante](https://user-images.githubusercontent.com/22373640/71988421-a527c780-320e-11ea-81d4-990b7434bccb.png)

Tela 02: Nesse caso, a pagina foi "scrollada" até o fim. O botão filtrar não está mais sobre nenhum filtro. O botão filtrar passa a ocupar 100% da largura da tela. E o botão voltar permanece fixo e visível no topo.
![filtro-olx](https://user-images.githubusercontent.com/22373640/71988530-d902ed00-320e-11ea-90a4-bd1199e783fb.png)

**Comment by alexxxmendonca** [comment]
@paratiuid de acordo.

**Comment by gustavofonseca** [comment]
Estou de acordo também (eu acho) =]

**Comment by paratiuid** [comment]
@gustavofonseca @alexxxmendonca 

Pessoal ,

conforme falamos hoje em nossa daily, precisei fazer uma alteração no wireframe da home do search mobile.

Seguem as imagens abaixo.

O primeiro modelo colocado por mim foi esse. Percebam que ele não contempla a escolha de tipo de índice para a busca:
![Screen Shot 2020-01-21 at 11 35 37 AM](https://user-images.githubusercontent.com/22373640/72813682-87ad2180-3c42-11ea-8d1d-75161dd12c3e.png)

Atualizei para esse:
![Screen Shot 2020-01-21 at 11 36 09 AM](https://user-images.githubusercontent.com/22373640/72813775-b3300c00-3c42-11ea-95e2-a25b068f5d17.png)

**Comment by gustavofonseca** [comment]
Excelente, @paratiuid. Grato por informar =]

**Comment by paratiuid** [comment]
@alexxxmendonca @gustavofonseca 

Pessoal, conforme comentado hoje na daily, segui os trabalhos na documentação do layout no figma.

Segue o link:
https://www.figma.com/proto/M44HZAppE9A5Mc5yXymj5X/Search-Journals-Mobile?node-id=1%3A2&viewport=634%2C472%2C1&scaling=scale-down

**Comment by gustavofonseca** [comment]
É possível apenas fazer scroll, é isso mesmo?

**Comment by paratiuid** [comment]
> É possível apenas fazer scroll, é isso mesmo?

Sim. Nessa primeira versão, sim.

**Comment by alexxxmendonca** [comment]
@paratiuid Ok. No aguardo das demais telas (além da home).

**Comment by paratiuid** [comment]
@alexxxmendonca @gustavofonseca 

Segue uma atualização do protótipo.

https://www.figma.com/proto/M44HZAppE9A5Mc5yXymj5X/Search-Journals-Mobile?node-id=1%3A2&viewport=1919%2C-559%2C1&scaling=scale-down

Novas funcionalidades disponíveis:
- aviso sobre política de cookies fixado no footer
- abrir menu
- inserir novo campo de busca
- ver histórico de busca
- incluir item na busca
- editar expressão
- limpar lista

**Comment by alexxxmendonca** [comment]
@paratiuid está ficando bom

Achei o tamanho da fonte da página de "Histórico de busca" um pouco pequena. Pensei que pudesse ser por que estava vendo no desktop, mas abri em meu smartphone e também tive a mesma impressão.

Consegue aumentar um pouco?

**Comment by paratiuid** [comment]
> @paratiuid está ficando bom
> 
> Achei o tamanho da fonte da página de "Histórico de busca" um pouco pequena. Pensei que pudesse ser por que estava vendo no desktop, mas abri em meu smartphone e também tive a mesma impressão.
> 
> Consegue aumentar um pouco?

@alexxxmendonca 

segue a correção:
https://www.figma.com/proto/M44HZAppE9A5Mc5yXymj5X/Search-Journals-Mobile?node-id=43%3A20&viewport=928%2C-43%2C0.5&scaling=scale-down

**Comment by alexxxmendonca** [comment]
Ficou melhor!

**Comment by paratiuid** [comment]
@alexxxmendonca 

segue a evolução do protótipo:

https://www.figma.com/proto/M44HZAppE9A5Mc5yXymj5X/Search-Journals-Mobile?node-id=1%3A2&viewport=461%2C394%2C0.5&scaling=scale-down

- foi feito conforme o wireframe.
- não me agradou o link do documento aparecer somente no detalhe.
- aumentei o espaço de toque do menu principal

**Comment by alexxxmendonca** [comment]
@paratiuid conforme conversamos, por favor faça uma versão com a área toda do resultado sensível ao toque, eliminando a seta, atendendo a esta observação:

_não me agradou o link do documento aparecer somente no detalhe._

**Comment by paratiuid** [comment]
> @paratiuid conforme conversamos, por favor faça uma versão com a área toda do resultado sensível ao toque, eliminando a seta, atendendo a esta observação:
> 
> _não me agradou o link do documento aparecer somente no detalhe._

Veja @alexxxmendonca 
https://www.figma.com/proto/M44HZAppE9A5Mc5yXymj5X/Search-Journals-Mobile?node-id=134%3A31&viewport=-1491%2C-1645%2C1&scaling=scale-down

**Comment by paratiuid** [comment]
@alexxxmendonca 

conforme conversamos, seguem as imagens que explicam de forma visual a interação com o resultado da busca.

![search-mobile-comportamento-v1](https://user-images.githubusercontent.com/22373640/74039943-864d5a00-49a1-11ea-9c13-0f10521290f8.jpg)

![search-mobile-comportamento-v2](https://user-images.githubusercontent.com/22373640/74039969-906f5880-49a1-11ea-80c9-3f404a934981.jpg)

**Comment by alexxxmendonca** [comment]
@paratiuid estou de acordo com a solução proposta com base nas justificativas apresentadas.

Aproveito para solicitar alteração na forma de exibição do DOI.

De acordo com as orientações mais recentes do Crossref:

> Display Crossref DOI as a full link
> Crossref DOIs should always be displayed as a full URL link in the form
> https://doi.org/10.xxxx/xxxxx
> and should not be preceded by doi: or DOI:.
> Example: https://doi.org/10.5468/ogs.2016.59.1.1

Fonte: https://www.crossref.org/display-guidelines/

Essa prática está sendo alterada em todas as instâncias onde o DOI é exibido em todos os sites SciELO.

**Comment by paratiuid** [comment]
@alexxxmendonca @gustavofonseca 

Seguem atualizações no protótipo:
https://www.figma.com/proto/M44HZAppE9A5Mc5yXymj5X/Search-Journals-Mobile?node-id=1%3A2&viewport=-379%2C-588%2C0.5&scaling=scale-down

Incluído:
- filtros
- resumo
- lista com filtros

**Comment by alexxxmendonca** [comment]
@paratiuid está ficando bom!

Uma dúvida: os clusters são da cor azul na interface desktop e aqui são brancos. Algum motivo específico para isso?

**Comment by paratiuid** [comment]
> @paratiuid está ficando bom!
> 
> Uma dúvida: os clusters são da cor azul na interface desktop e aqui são brancos. Algum motivo específico para isso?

Oi @alexxxmendonca 

a idéia foi manter o padrão utilizado também no scielo.org, onde os accordions compoem a interface mobile.

Fundo branco, com setas cinzas. Veja a imagem abaixo:
<img width="372" alt="Screen Shot 2020-02-11 at 9 57 58 AM" src="https://user-images.githubusercontent.com/22373640/74239637-01bb4e00-4cb7-11ea-8421-89f96719d3eb.png">

**Comment by alexxxmendonca** [comment]
@paratiuid ok, de acordo!

Com isso, podemos seguir para a fase de codificação.

**Comment by paratiuid** [comment]
@alexxxmendonca @gustavofonseca @jamilatta 

Pessoal, 
conforme conversado agora na daily, verifiquei ontem que não foi desenhada a interação de seleção de um item de busca.

Vou retornar a essa fase do protótipo apenas para ter tudo desenhado e acordado.
Assim que finalizado, colo o link para acesso aqui.

**Comment by paratiuid** [comment]
@alexxxmendonca  @gustavofonseca  @jamilatta 

Conforme comentado anteriormente, foi feita a tela que ilustra a interação com os itens da busca.

Agora é possível selecionar todos os itens, ou selecionar um item individual. 
Ao fazer, é exibida uma barra flutuante que contém os componentes que possibilitam efetuar ações com os ítens selecionados.

https://www.figma.com/proto/M44HZAppE9A5Mc5yXymj5X/Search-Journals-Mobile?node-id=134%3A31&viewport=-3295%2C-7130%2C2&scaling=scale-down

**Comment by gustavofonseca** [comment]
@alexxxmendonca, este ticket também é difícil de mensurar e avaliar o avanço. Podemos fechá-lo e quem sabe conduzir esta atividade em outro ticket/quadro?

**Comment by paratiuid** [comment]
@gustavofonseca realmente esta atividade é praticamente um projeto. Não dá para seguir o mesmo fluxo e SLA de um ticket normal. (PS: É o Caramez)

**Comment by gustavofonseca** [comment]
> @gustavofonseca realmente esta atividade é praticamente um projeto. Não dá para seguir o mesmo fluxo e SLA de um ticket normal. (PS: É o Caramez)

Perfeito, @paratiuid. Criei um [quadro de kanban (privado)](https://github.com/orgs/scieloorg/projects/9) exclusivamente para este projeto e inclui seu usuário como colaborador.
