### ISSUE TITLE
Discutir as funcionalidades do search em relação ao projeto cited-references

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/search-journals#460]
### Descrição da tarefa
Definir as funcionalidades do search em relação ao projeto cited-references

(o ponto de partida será na data 18/11, quando ocorrerá uma reunião com a equipe do cited-references)

**Comment by jamilatta** [comment]
@gustavofonseca 

Pelo que entendi, essas definições já foram realizadas ou pelo menos conversadas, poderia de alguma forma documentar, para que possamos fechar esse ticket.

**Comment by gustavofonseca** [comment]
@alexxxmendonca e eu produzimos uma lista de estórias de usuários que deverá servir como base para a implementação da primeira versão da funcionalidade. Com estas estórias a expectativa é que a equipe da @paratiuid possa esboçar propostas de interfaces.

https://docs.google.com/document/d/1eoVRYVWdF_suukUQ2UJQauGhLlrhEm7wZuRF1c8M3-8/edit?usp=sharing

**Comment by paratiuid** [comment]
Pessoal, 
@gustavofonseca @alexxxmendonca 

com base no documento Estórias de usuários para MVP-0 e pelo histórico da atividade, criei alguns wireframes que ilustram o que imagino para a tela inicial.

Nessa tela, existe a opção entre buscar por artigos e conteúdos da rede SciELO, como é hoje e uma segundo opção para buscar por referências.

Ao optar por buscar por referências, criei um seletor de tipo de resultado esperado, para que assim, ao inputar os dados correspondentes, o resultado seja exibido da melhor maneira.

Segue o PDF contendo as telas e aguardo os comentários de vocês.
[referencias v1.pdf](https://github.com/scieloorg/search-journals/files/4037135/referencias.v1.pdf)

**Comment by alexxxmendonca** [comment]
@paratiuid o que havíamos alinhado com Caramez era uma aba dentro da interface com os resultados.

Veja com o Caramez, por favor.

Essa é a expectativa do Abel, também (abas na interface dos resultados).

**Comment by paratiuid** [comment]
Ok @alexxxmendonca 

Vou rever aqui e volto apostar quando estiver de acordo com o combinado.

**Comment by paratiuid** [comment]
Oi @alexxxmendonca 

fiz um novo modelo depois de nossa conversa.

Veja essa nova versão:
[referencias - v2.pdf](https://github.com/scieloorg/search-journals/files/4042400/referencias.-.v2.pdf)

**Comment by alexxxmendonca** [comment]
Oi @paratiuid 

1) Renomear as abas para "Documentos" e "Referências" (remover o "pesquisar").

2) Os clusters devem ser aqueles especificados no ticket #436

**Comment by paratiuid** [comment]
Oi pessoal,  

@alexxxmendonca @gustavofonseca 

Segue um novo modelo de wireframe.
O pdf abaixo visa solucionar o seguinte caso de uso:

1 - Como pesquisador, eu quero ser capaz de buscar pelo nome ou sobrenome de um autor para que sejam recuperados todos os documentos da Rede SciELO que citam os seus trabalhos.
inclusive os meus próprios

[referencias - v5.pdf](https://github.com/scieloorg/search-journals/files/4098872/referencias.-.v5.pdf)

**Pontos de atenção sobre o wireframe:**

1 - Os clusters (todos, na aba referências) passam a se referir a dois casos:
  a) citado
  b) citante (quem faz a citação)

2 - Os nomes dos autores nos clusters serão exibidos de forma abreviada?

**Comment by gustavofonseca** [comment]
@paratiuid, penso estarmos no caminho certo. Tenho uma provocação: como seria se não houvesse a separação _Documentos / Referências_? Digo, uma listagem única incluindo os 2 tipos de objetos?

**Comment by alexxxmendonca** [comment]
@paratiuid penso que está correto, também. Não seria o caso de solicitarmos avaliação da Solange (que não está neste repositório)?

**Comment by paratiuid** [comment]
> @paratiuid, penso estarmos no caminho certo. Tenho uma provocação: como seria se não houvesse a separação _Documentos / Referências_? Digo, uma listagem única incluindo os 2 tipos de objetos?

@gustavofonseca @alexxxmendonca 
Segue uma alternativa que pensamos para o caso onde não existam as abas.
Peço que leiam os comentários contidos nos cards amarelos, dentro do wireframe.

[referencias - v6 - sem abas.pdf](https://github.com/scieloorg/search-journals/files/4119405/referencias.-.v6.-.sem.abas.pdf)

**Comment by gustavofonseca** [comment]
Eu não sei se entendi. Só vejo resultado de busca por documento, mas nenhum para referência bibliográfica. É isso mesmo?

**Comment by paratiuid** [comment]
> Eu não sei se entendi. Só vejo resultado de busca por documento, mas nenhum para referência bibliográfica. É isso mesmo?

O que diferencia um resultado de busca por documento e um resultado de busca por citação?
Não consigo visualizar um resultado de busca por documento aparecendo junto com um resultado de busca por citação.
O que faria um ou outro aparecer primeiro na lista?

No meu ponto de vista:
Um resultado de busca por documento deve exibir o documento que contenha os termos buscados.
Um resultado de busca por referências deve exibir a referência que contenha os termos buscados.

Acredito ainda que o resultado de busca por documento possa exibir a quantidade de referências citadas.
Da mesma forma, o resultado de busca por referências pode exibir a quantidade de documentos que o citou.

Pensando dessa forma, a divisão de contexto com abas, me parece a mais acertada.


Você tem alguma outra sugestão?
Podemos e devemos estressar bastante essa questão para acharmos possíveis alternativas.

Imaginei também uma terceira coluna (coluna 1 = clusters, coluna 2 = resultados de de busca por documentos, coluna 3 = resultado de busca por referências.) mas não me pareceu intuitivo.
Imaginei essa interface responsiva. No celular, acredito que as formas de separação das colunas seria ou por abas ou por accordion.
Caí novamente na idéias das abas.


O que você acha?

**Comment by gustavofonseca** [comment]
Me parece que estamos pensando em níveis de abstração diferentes, e isso dificulta a comunicação. Eu estou em algo mais conceitual e vc no concreto. 

Estou pensando no seguinte: ao pesquisar pelo autor "Abel Packer" num campo de busca, 
eu receberia como resultado documentos indexados na Rede SciELO em que 
"Abel Packer" é um autor[1][2], mais as referências bibliográficas em que 
"Abel Packer" é autor. Estas referências bibliográficas foram extraídas dos 
documentos indexados na Rede SciELO[1] e reificadas[3][4]. 
Algumas referências bibliográficas podem estar associadas à documentos da Rede,
referenciando-o, como é o caso de[4]. Outras podem não se referir a documentos 
da Rede, como é o caso de[3] que referencia um documento publicado na EMBO.


1. http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0102-79722015000600066&lang=pt
2. http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1517-97022014000200002&lng=pt&tlng=pt
3. Meneghini, R., & Packer, A. (2007). Is there science beyond English? Initiatives to increase the quality and visibility of non-English publications might help to break down language barriers in scientific communication. EMBO Reports, 8(2), 112-116. doi:10.1038/sj.embor.7400906.
4. Packer, A.L. (2014). The emergence of journals of Brazil and scenarios for their future. Educação e Pesquisa, 40(2), 301-323. doi:10.1590/S1517-97022014061860.


_O que diferencia um resultado de busca por documento e um resultado de busca por 
citação?_ Este é o tipo de pergunta que me atrai, e a resposta na minha
visão é: muito pouco. Pense que o Search já não exibe documentos, mas 
apenas referências para os documentos publicados na Rede. De fato, ele é um índice referencial. As referências
bibliográficas também são referências para documentos publicados e não publicados
na Rede. Se pensarmos desta forma mais abstrata é possível encontrarmos um denominador
comum.

A graça do exercício de eliminar as abas é de provocarmos um design 
mais abstrato e, espero, mais simples do ponto de vista de uso. 

Espero ter conseguido me fazer entender ;)

**Comment by paratiuid** [comment]
@gustavofonseca 

criei um modelo tomando como base seu último comentário, citando o caso do autor Abel Packer.

Veja se está de acordo com o que você imaginava ou se faltou algum detalhe.

[referencias - v7 - referencias e documentos misturados no resultado da busca.pdf](https://github.com/scieloorg/search-journals/files/4130014/referencias.-.v7.-.referencias.e.documentos.misturados.no.resultado.da.busca.pdf)

**Comment by gustavofonseca** [comment]
Ok. Seria razoável alguém querer aplicar um filtro por "Documentos da Rede SciELO" ou "Referências bibliográficas". 

Você chegou a exercitar as estórias de usuário dentro deste contexto?

**Comment by alexxxmendonca** [comment]
Vou deixar registrado aqui as impressões que a Solange teve analisando os wireframes.

> Alex,
> 
> Conforme falamos segue minha impressão sobre a implementação do “Referências Citadas”
> 
> Aparentemente trata-se de apenas mais um tipo de busca, desse modo, as expectativas a serem atendidas são de um buscador. Minhas expectativas podem ser bem diferentes se vocês estivermos tentando oferecer um reference manager.
> 
> Se é um buscador em distintos tipos de índices não vejo necessidade do “Buscar Literaturas”
> 
> Na aba documentos eu gostaria de poder buscar por meu nome, encontrar trabalhos meus publicados no SciELO e nessa mesma tela poder “expandir” a referência de cada trabalho recuperado para saber “quantos” e “quais” são os artigos citantes do meu trabalho (isso está disponível na aba referencias eu só posso ter acesso a essa funcionalidade na outra aba?)
> A diferença entre a busca na aba “documentos”: se referindo aos artigos publicados na base SciELO não é tão óbvia. Não fica claro de partida que nessa aba vou buscar na base somente artigos publicados em SciELO (que é uma funcionalidade que já existe hoje com plus de ver quem está citando) e que na aba “referências” são os trabalhos citados pelos artigos publicados no SciELO. Não percebi logo de cara essa diferença.
> 
> Posso baixar os resultados em qualquer das abas ou somente em referências?
> Bem, acho que essas foram minhas primeira impressões.
> 
> Abraços,
> Solange Santos
> SciELO - Scientific Electronic Library Online
> FAPESP - CAPES - CNPq - BIREME - FapUNIFESP

**Comment by paratiuid** [comment]
[referencias - v8 - referencias e documentos nos casos de uso.pdf](https://github.com/scieloorg/search-journals/files/4136485/referencias.-.v8.-.referencias.e.documentos.nos.casos.de.uso.pdf)


Pessoal, segue uma nova versão do wireframe.
Este modelo é uma evolução do anterior. Aqui, tento resolver os casos de uso contidos no link:
https://docs.google.com/document/d/1eoVRYVWdF_suukUQ2UJQauGhLlrhEm7wZuRF1c8M3-8/edit?pli=1

Pontos de atenção:
- Novo filtro "Tipo de resultado" adicionado. A idéia é filtrar o tipo de conteúdo, sejam documentos, referências bibliográficas ou todos.
- É possível rastrear os autores que foram citados em uma referência?
Dúvida ilustrada no card vermelho, dentro do wireframe.


Comentários sobre cada caso de uso:

1 - O wireframe v8 atende.

2 - O wireframe v8 atende. Basta remover o filtro de autor. Mantendo o filtro autor citado.

3 - Exibir resultados onde a citação contenha os termos buscados:
    --> Incluir índice Título citado.

4 - O wireframe atende. Pois exibe o número de citações e é possível acessar via link cada artigo citado.

5 - Bastaria selecionar os itens desejados e incluir uma nova opção no select "itens selecionados". Essa nova opção poderia ser baixar itens selecionados em CSV, ou em formato adequado.

6 - Idem anterior.

7 - Bastaria seguir os seguintes passos:
    -> selecionar o índice "Periódico"
    -> preencher o campo com o título do periódico
    -> efetuar a busca
    -> selecionaro no novo cluster "tipo de resultado" a opção "Referências Bibliográficas"
    -> uma lista contendo somente as citações do periódico será exibida.
    -> a analise pode ser feita diretamente na tela, ou via exportação de dados em CSV ou formato adequado, já citado no item 5.

8 - Bastaria seguir os seguintes passos:
    -> digitar o termo "fake news"
    -> manter o indice "todos os índices selecionados" 
    -> utilizar os clusters de "Periódico" e "Áreas temáticas" para filtrar.

9 - Penso que um novo índice "Autor citado" seja necessário.
    Usando os padrões atuais, penso que existe a seguinte maneira:
    -> digitar o assunto desejado com o indice "todos os índices"
    -> após aparecer todos os resultados com o termo buscado, vá no cluster "Autor citado" (novo)
    -> um modal com uma lista de todos os autores citados deve aparecer. Na lista, dentro do modal, temos geralmente na primeira coluna o nome do autor, e na segunda coluna o número de resultados encontrados. Nesse caso, esse número de resultados seria o número de citações recebidas por ele. 
    É possivel ordenar a lista dentro do modal por nome, clicando no label "Autor" ou por Número de indices encontrados, nesse caso representado pelo label "Resultados".
    Nesse wirefram existem modais, que ilustram o formato contendo duas colunas, onde uma delas mostra exatamente o número de registros encontrados por autor.

**Comment by gustavofonseca** [comment]
> É possível rastrear os autores que foram citados em uma referência?
> Dúvida ilustrada no card vermelho, dentro do wireframe.

Não entendi a pergunta. O que quer dizer com _rastrear_?

----

Não entendi a proposta dos filtros de Autor citante e citado, aquele popup e tal. Poderia descrever um pouco sobre a ideia?

----

Os textos _N citações_ e _citado em N documentos_ são ligeiramente ambíguos, pois o termo _citação_ por si só não deixa claro se foi recebida ou concedida. Penso que poderiam ser trocados, tanto para documentos quanto para referências, por _Citado N vezes_ ou _N citações recebidas_. 

----
Penso que esta proposta está bastante consistente e atende às estórias de usuário, com exceção das estórias 7 e 9 que penso estarem pouco maduras.

**Comment by paratiuid** [comment]
> > É possível rastrear os autores que foram citados em uma referência?
> > Dúvida ilustrada no card vermelho, dentro do wireframe.
> 
> Não entendi a pergunta. O que quer dizer com _rastrear_?
> 
> Não entendi a proposta dos filtros de Autor citante e citado, aquele popup e tal. Poderia descrever um pouco sobre a ideia?
> 
> Os textos _N citações_ e _citado em N documentos_ são ligeiramente ambíguos, pois o termo _citação_ por si só não deixa claro se foi recebida ou concedida. Penso que poderiam ser trocados, tanto para documentos quanto para referências, por _Citado N vezes_ ou _N citações recebidas_.
> 
> Penso que esta proposta está bastante consistente e atende às estórias de usuário, com exceção das estórias 7 e 9 que penso estarem pouco maduras.



**Sobre suas dúvidas:**

Pergunta 1:
Não entendi a pergunta. O que quer dizer com rastrear?

Resposta 1:

Caso haja no sistema a seguinte citação de referência:
Packer, A.L. (2014). The emergence of journals of Brazil and scenarios for their future. Educação e Pesquisa, 40(2), 301-323. doi:10.1590/S1517-97022014061860.

a) tenho como saber quais foram os autores citados nesse documento?

---

Pergunta 2:
Não entendi a proposta dos filtros de Autor citante e citado, aquele popup e tal. Poderia descrever um pouco sobre a ideia?

Resposta2:

Autor citante é quem faz a citação. O autor de um documento, cita outro documento.

Autor citado é quem recebe a citação. É o autor do documento que serviu de referência.

No wireframe v8, temos um caso de auto citação.

O modal (popup) de autor citante traz uma lista dos autores que casam com a busca feita no campo de busca que tem como índice o autor.

![Screen Shot 2020-02-04 at 4 07 25 PM](https://user-images.githubusercontent.com/22373640/73777813-e4dbc380-4768-11ea-8d58-5c0febd66290.png)

Concordo que aqui, no lugar de apenas "autor", o indice deveria exibir "autor citante". Não podemos ter labels diferentes para o mesmo tipo de campo. Erro meu.

![Screen Shot 2020-02-04 at 4 07 50 PM](https://user-images.githubusercontent.com/22373640/73777802-e0170f80-4768-11ea-9de2-d4a9184cbd02.png)

Os componentes que compoem o modal são:
- um accordion
  -> para o caso de haver mais de uma busca sobre autor citante.

- uma lista de nomes de autores que casem com a busca realizada pelo índice de autor (citante).

Caso a busca contenha mais um campo com o índice de autor (citante), o accordion exibe com mais uma linha, e dentro dela a lista com os nomes correspondentes.

![Screen Shot 2020-02-04 at 4 15 28 PM](https://user-images.githubusercontent.com/22373640/73778237-9f6bc600-4769-11ea-9f81-5aa3db75b464.png)

![Screen Shot 2020-02-04 at 4 14 58 PM](https://user-images.githubusercontent.com/22373640/73778247-a397e380-4769-11ea-82ff-86c317feacdc.png)

---

Pergunta 3:
Os textos N citações e citado em N documentos são ligeiramente ambíguos, pois o termo citação por si só não deixa claro se foi recebida ou concedida. Penso que poderiam ser trocados, tanto para documentos quanto para referências, por Citado N vezes ou N citações recebidas.

Resposta 3:

Concordo. Fiz o ajuste. Veja imagem abaixo

![Screen Shot 2020-02-04 at 4 19 16 PM](https://user-images.githubusercontent.com/22373640/73778570-346ebf00-476a-11ea-9272-effcdc493810.png)

![Screen Shot 2020-02-04 at 4 19 40 PM](https://user-images.githubusercontent.com/22373640/73778610-3fc1ea80-476a-11ea-909b-36d5bd6f59fe.png)

---

Pergunta 4:
Penso que esta proposta está bastante consistente e atende às estórias de usuário, com exceção das estórias 7 e 9 que penso estarem pouco maduras.


Resposta 4:

Uma alternativa para o caso de uso 7:
Da mesma forma que o cluster de autor passa a ter "autor citante" (quem faz a citação) e "autor citado" (quem recebeu a citação), penso que os demais clusters devem também ter essa ramificação para possibilitar referenciar quem cita e quem é citado.

Então, havendo um cluster de periódico citado, os passos devem ser os seguintes:

1 - selecionar o índice "periódico citado"
2 - digitar o nome do periódico a ser pesquisado nas referencias
3 - abrir o cluster de "periódicos citados" e verificar as opções que são exibidas dentro da lista de periódicos que condizem com a busca. Nessa lista, devem aparecer todas as variações do nome do periódico buscado.

--

Sobre o caso de uso 9:

Entendido o conceito dos clusters "citante (quem cita)" e "citado (quem foi citado)", acredito que o que foi dito anteriormente atende ao caso de uso.
Hoje, os clusters exibem uma lista e cada item dessa lista contém o número de registros.
Veja como exemplo o caso abaixo:

Coleções com mais resultados:

<img width="624" alt="Screen Shot 2020-02-04 at 3 58 06 PM" src="https://user-images.githubusercontent.com/22373640/73778719-68e27b00-476a-11ea-8c88-166bd5de0047.png">

No cluster acima, vemos que a coleção "Brasil" é a que tem mais itens.

**Comment by gustavofonseca** [comment]
@paratiuid, grato pelas explicações. Bom, não estou confortável com estes modais de _autor citante_ e _autor citado_ e, como não são parte das estórias de usuário para o MVP, sugiro que sejam removidos. 

Também não estou confortável com o índice _autor citante_. Em uma primeira versão penso que um índice genérico para _autor_ seja suficiente. 

O que acha @alexxxmendonca?

**Comment by alexxxmendonca** [comment]
@gustavofonseca de acordo em entregarmos algo genérico e mais abrangente no início e irmos afunilando de acordo com as demandas e casos de uso.

**Comment by paratiuid** [comment]
@alexxxmendonca @gustavofonseca 

Segue o modelo mais genérico conforme solicitado.

[referencias - v9 - modelo mais generico.pdf](https://github.com/scieloorg/search-journals/files/4187011/referencias.-.v9.-.modelo.mais.generico.pdf)

**Comment by alexxxmendonca** [comment]
@paratiuid de acordo.

Está é a versão "consolidada" que o Gustavo solicitou.

Poderia indicar o link da versão mais recente da proposta original, aquela com as 2 abas?

**Comment by paratiuid** [comment]
> @paratiuid de acordo.
> 
> Está é a versão "consolidada" que o Gustavo solicitou.
> 
> Poderia indicar o link da versão mais recente da proposta original, aquela com as 2 abas?

Oi @alexxxmendonca 

acredito que vc esteja se referindo a essa versão já postada anteriormente no comentário:
https://github.com/scieloorg/search-journals/issues/460#issuecomment-577301076

seria a v5.

**Comment by alexxxmendonca** [comment]
@paratiuid sim, para mostrarmos para o Abel as versões mais recentes das duas propostas.

**Comment by gustavofonseca** [comment]
> @alexxxmendonca @gustavofonseca
> 
> Segue o modelo mais genérico conforme solicitado.
> 
> [referencias - v9 - modelo mais generico.pdf](https://github.com/scieloorg/search-journals/files/4187011/referencias.-.v9.-.modelo.mais.generico.pdf)

@paratiuid, só para informar que esta versão ainda conta com modal de autores que solicitamos que fossem removidos.

**Comment by paratiuid** [comment]
> > @alexxxmendonca @gustavofonseca
> > Segue o modelo mais genérico conforme solicitado.
> > [referencias - v9 - modelo mais generico.pdf](https://github.com/scieloorg/search-journals/files/4187011/referencias.-.v9.-.modelo.mais.generico.pdf)
> 
> @paratiuid, só para informar que esta versão ainda conta com modal de autores que solicitamos que fossem removidos.


@gustavofonseca 

retornando seu comentário, segue novo modelo sem o cluster de autores.

[referencias - v10 - modelo mais generico sem cluster autores.pdf](https://github.com/scieloorg/search-journals/files/4194405/referencias.-.v10.-.modelo.mais.generico.sem.cluster.autores.pdf)

**Comment by gustavofonseca** [comment]
@alexxxmendonca, este ticket é muito difícil de medir e avaliar o avanço. Acha que já pode ser fechado?

**Comment by alexxxmendonca** [comment]
@gustavofonseca de acordo.
