### ISSUE TITLE
Incluir aviso de uso de cookies

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#462]
### Descrição da nova funcionalidade
Eu, como **usuário cidadão europeu, mas não limitando-se a**, gostaria que **o site fosse compatível com a lei GDPR**, então **além de outras coisas, o site deve exibir um aviso sobre o uso de cookies e a política de privacidade do site**.

### Critérios de aceitação

- Utilizar a mesma solução adotada pelos demais sites SciELO (javascript comum a todos). 
Exemplos:

https://www.scielo.org
https://blog.scielo.org

### Anexos
Usar o código:

```
<!--SciELO - Script para exibir aviso de uso de Cookies e Política de Privacidade -->

<script src="https://static.scielo.org/js/cookiePolicy.min.js"></script>
```

### Referências
N/A

**Comment by jamilatta** [comment]
@paratiuid 

Poderia verificar esse ticket?

**Comment by alexxxmendonca** [comment]
@jamilatta eu deixei para entrar no planning da próxima semana.

**Comment by jamilatta** [comment]
@alexxxmendonca 

Poderia validar?

**Comment by alexxxmendonca** [comment]
Testado e aprovado em homolog.search.scielo.org
