### ISSUE TITLE
A formação dos links no resultado está errado. 

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#487]
### Descrição do problema
A formação dos links no resultado está errado. 

### Passos para reproduzir o problema
1. Acessar o search 
2. Clicar nos links que remetem para o texto completo 
3. Verificar que existe URL que remetem para links do artigos com idiomas inexistente.

### Comportamento esperado

Abrir somente URL para texto com idiomas presente.

**Comment by gustavofonseca** [comment]
Não foi possível reproduzir o problema.
