### ISSUE TITLE
Ajuste no resultado de pesquisa dos Preprints

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#493]
### Descrição da nova funcionalidade

Realizar ajuste pontuais para que o resultado de pesquisa para os artigos em fase de preprint.

### Critérios de aceitação

Que o resultado de pesquisa seja próoximo dos de artigo mais que contenha um indicação de que é um **preprint**.

**Comment by jamilatta** [comment]
@alexxxmendonca reprocessei os PrePrint caso queira dá uma olhada em homolog: https://homolog.search.scielo.org/?q=*&lang=pt&count=15&from=1&output=site&sort=&format=summary&page=1&where=&filter%5Bin%5D%5B%5D=preprint

**Comment by jamilatta** [comment]
@alexxxmendonca poderia validar o retorno do resultado de pesquisa dos preprints, veja: https://homolog.search.scielo.org/?q=*&lang=pt&count=15&from=0&output=site&sort=&format=summary&fb=&page=1&q=in%3Apreprint&lang=pt&page=1

**Comment by jamilatta** [comment]
Imagem: 

<img width="1129" alt="Screenshot 2020-04-09 20 09 32" src="https://user-images.githubusercontent.com/373745/78948271-1c832680-7a9e-11ea-9fc0-223835189dec.png">

**Comment by alexxxmendonca** [comment]
@jamilatta aprovado. Com a ressalva que isso poderá ser alterado futuramente.
