### ISSUE TITLE
Adiciona as referência na pesquisa integrado do search.scielo.org

### ISSUE THREAD

**Issue by rafaelpezzuto** [scieloorg/search-journals#499]
### Descrição da nova funcionalidade
Implementa a busca por referências citadas. Deve atender às estórias descritas neste [documento base](https://docs.google.com/document/d/1eoVRYVWdF_suukUQ2UJQauGhLlrhEm7wZuRF1c8M3-8).
Trata-se de permitir buscar pelos campos de autor, periódico (ou livro ou capítulo de livro), entre outros, existentes na lista de referências de cada documento da rede SciELO. A maior mudança é no contexto de busca, que passa a enxergar 22 milhões de registros Solr. Esses registros se dividem em artigos e citações.

### Anexos
N/A

### Referências
[Documento base](https://docs.google.com/document/d/1eoVRYVWdF_suukUQ2UJQauGhLlrhEm7wZuRF1c8M3-8)

**Comment by gustavofonseca** [comment]
Este ticket corresponde praticamente a todo um projeto. O que vocês acham de o fecharmos e seguirmos apenas com outros menores e mais pontuais?

**Comment by rafaelpezzuto** [comment]
Eu concordo. Foram muitas atividades realizadas e esse ticket não reflete todo o esforço realizado pelos envolvidos (tarefas de infra, planejamento, implementação, testes, etc).
