### ISSUE TITLE
Alterar título da Coleção "Preprint" para "SciELO Preprints"

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#500]
### Descrição da tarefa
O nome da coleção deve ser alterado de "Preprint" para "SciELO Preprints"

**Comment by alexxxmendonca** [comment]
Não foi possível validar este ticket.

O nome da coleção continua como "Preprint":

![image](https://user-images.githubusercontent.com/4059679/147956861-20605307-d9fb-46be-a2dc-0d97cbe11154.png)

**Comment by gitnnolabs** [comment]
@alexxxmendonca irei verificar.

**Comment by gitnnolabs** [comment]
Acredito que realizei somente a alteração no resultado da pesquisa, veja: 
![Captura de Tela 2022-01-03 às 13 51 00](https://user-images.githubusercontent.com/86991526/147957260-5610e28b-436a-4213-9461-35aa0f0110d8.png)

**Comment by alexxxmendonca** [comment]
@gitnnolabs Entendi! Nesse caso basta alterar também no cluster.

**Comment by gitnnolabs** [comment]
👍

**Comment by gitnnolabs** [comment]
Atualizado em homolog: http://homolog-search.scielo.org

**Comment by alexxxmendonca** [comment]
Testado e aprovado em homologação.

**Comment by alexxxmendonca** [comment]
Aplicado em produção.
