### ISSUE TITLE
Operador lógico AND é alterado para OR ao navegar pelas páginas de resultados

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/search-journals#503]
Operador lógico AND é alterado para OR ao navegar pelas páginas de resultados.

### Passos para reproduzir o problema
1. Acesse a página search.scielo.org
2. Busque por um termo qualquer, por exemplo _Memória_
3. Na caixa de filtros do lado esquerdo, aplique o filtro _SciELO Áreas Temáticas_, selecionando _Ciências Humanas_ **AND** _Ciências da Saúde_
4. Role até o final da página de resultados e mude para a próxima página
5. Observe, no canto superior da caixa de filtros, que a expressão mudou de `memória AND subject_area:("Human Sciences" AND "Health Sciences")` para `memória AND subject_area:("Human Sciences" OR "Health Sciences")`

### Comportamento esperado
A expressão de busca não deve ser alterada durante a navegação pelas páginas de resultados.

### Ambiente utilizado
O problema se manifestou tanto no Chrome quanto no Firefox.

- Navegador Mozilla Firefox 76.0b7 (64-bit), Google Chrome 81.0.4044.113 (Official Build) (64-bit)
- MacOS 10.15.4

**Comment by alexxxmendonca** [comment]
@gustavofonseca por acaso esse problema refere-se a este e-mail que recebemos?

_Acontece que quando precisei visualizar esses trabalhos à princípio por título e depois pelo resumo para saber quais de fato seriam interessantes para minha pesquisa, quando mudava de página ,pois apresenta 15 trabalhos por página, o total alcançado mudava para 1665 e os filtros continuavam os mesmos._

**Comment by gustavofonseca** [comment]
> @gustavofonseca por acaso esse problema refere-se a este e-mail que recebemos?
> 
> _Acontece que quando precisei visualizar esses trabalhos à princípio por título e depois pelo resumo para saber quais de fato seriam interessantes para minha pesquisa, quando mudava de página ,pois apresenta 15 trabalhos por página, o total alcançado mudava para 1665 e os filtros continuavam os mesmos._

@alexxxmendonca, sim.

**Comment by alexxxmendonca** [comment]
@gustavofonseca ok! Vou dar uma resposta à usuária então.
