### ISSUE TITLE
Remover a pesquisa prêvia para verificar a existência de registros.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#514]
### Descrição do problema

Atualmente na interface de pesquisa  realiza uma requisição para verificar se existe retorno de resultados para o termo. 

### Passos para reproduzir o problema
1. Acessar o ambiente http://search.scielo.org 
2. Clicar no botão de pesquisa
3. Verifique na ferramenta do desenvolvedor do browser que existe um requisição prêvia para verificar se existe retorno de resultados.

### Ambiente utilizado

Quando aplicável, forneça detalhes sobre o ambiente utilizado, ex:

- Navegador Chrome 83.0.4103.106

**Comment by gitnnolabs** [comment]
Item realizado no PR: https://github.com/scieloorg/search-journals/pull/552
