### ISSUE TITLE
Widget do PlumX não está sendo carregado

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/search-journals#523]
A URL de onde o código do widget do PlumX é carregado mudou de `<script type="text/javascript" src="//d39af2mgp1pqhg.cloudfront.net/widget-popup.js"></script>` para `<script type="text/javascript" src="//cdn.plu.mx/widget-popup.js"></script>`, e desde então o widget parou de funcionar corretamente. 

### Passos para reproduzir o problema
1. Acesse a página search.scielo.org
2. Clique no link em buscar
3. Em qualquer resultado de busca, clique no ícone para exibir as métricas
4. Observe que o widget do PlumX não é exibido corretamente.

### Screenshots ou vídeos
![Screen Shot 2020-07-29 at 16 46 47](https://user-images.githubusercontent.com/161335/88845992-59913700-d1bb-11ea-8fa8-16966950f6a6.png)

**Comment by alexxxmendonca** [comment]
Estaria relacionado ao #420 ?

**Comment by jamilatta** [comment]
Parece que sim @alexxxmendonca estamos apontando para o link do script antigo, veja: 

![Captura de Tela 2020-07-29 às 17 00 12](https://user-images.githubusercontent.com/373745/88847136-fd2f1700-d1bc-11ea-8b97-b29991eff916.png)

**Comment by gustavofonseca** [comment]
> Estaria relacionado ao #420 ?

Sim, eu não vi o #420. Vou marcar este aqui como duplicado. Valeu!
