### ISSUE TITLE
Possibilita cadastrar as Áreas de interesse para DSI (Disseminação Seletiva da Informação) e visualizar as novas aquisições relacionadas com as áreas cadastradas.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#524]
### Descrição da nova funcionalidade
Eu, como usuário, gostaria que exista a possibilidade de selecionar áreas de interesse e/ou periódicos de interesse, para que a minha pesquisas seja mais seletiva.

### Critérios de aceitação

Permitir e persistir a capacidade de configurar as áreas de interesse com componentes visuais na interface.
Manter esse dados sem a necessidade de contas de usuários assim como é utilizado uma estratégia no histórico de pesquisa.

**Comment by gustavofonseca** [comment]
@alexxxmendonca e eu não entendemos de onde surgiu essa demanda, quais problemas ela resolve e como ela melhora o produto. Estou fechando o ticket, mas ele pode ser reaberto a qualquer momento desde que sejam fornecidos mais detalhes.
