### ISSUE TITLE
IBJU v46suppl1 não aparece nos resultados

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#542]
### Descrição do problema
O suplemento do volume 46 não aparece nos resultados de busca. 

### Passos para reproduzir o problema
1. Acesse a página https://search.scielo.org/?q=&lang=pt&count=50&from=1&output=site&sort=&format=summary&fb=&page=1&filter%5Bjournal_title%5D%5B%5D=International+braz+j+urol&filter%5Byear_cluster%5D%5B%5D=2020
2. Verificar que o suplemento não está incluso (os resultados mais recentes são do v46n6)

### Comportamento esperado
Exibir os documentos do v46suppl1 nos resultados.

Ao que tudo indica, o problema ocorre quando na expressão de busca há o caracter hífen.

**Comment by gitnnolabs** [comment]
@scieloorg/scielo-ps-developers 

Pessoal pelo que entendi o nosso problema é esse: https://stackoverflow.com/questions/18277609/search-in-solr-with-special-characters

Vou realizar essa atividade localmente e funcionando atualizo homologação para teste!

**Comment by gitnnolabs** [comment]
@alexxxmendonca 

Criei um PR para essa atividade, em paralelo estou ajustando o ambiente de homologação para testes e validações.

**Comment by gitnnolabs** [comment]
@alexxxmendonca 

Fiz as alterações necessárias no ambiente de homologação e re-indexei todas a coleção SciELO Brasil, poderia verificar no endereço: https://homolog-search.scielo.org/ 


Exemplos de termos que não estavam funcionando: 

- SARS-COVID-19 transformed the world and urological practice
- The Social, Economic and Sanitary Impact of COVID-19 Pandemic
- The SARS-CoV-2 Coronavirus and the COVID-19 Outbreak

**Comment by alexxxmendonca** [comment]
@gitnnolabs Ainda não consigo ver o suplemento... onde está?
https://homolog-search.scielo.org/?fb=&where=&filter%5Bin%5D%5B%5D=scl&filter%5Bjournal_title%5D%5B%5D=International+braz+j+urol&from=1&page=1

**Comment by gitnnolabs** [comment]
@alexxxmendonca 

Pelo que entendi não está apresentado a informação que é **suplemento**, mas isso, ao meu ver, é outro problema. 

Veja: https://homolog-search.scielo.org/?fb=&q=*&lang=pt&count=15&from=91&output=site&sort=&format=summary&page=7&where=&filter%5Bin%5D%5B%5D=scl&filter%5Bjournal_title%5D%5B%5D=International+braz+j+urol&filter%5Byear_cluster%5D%5B%5D=2020

Veja que a página retorna registros no suplemento: 
![Captura de Tela 2021-08-06 às 11 48 23](https://user-images.githubusercontent.com/86991526/128528908-2bfb5694-59f8-4b1e-bab8-ea7ea069588e.png)

**Repare que o número não aparece, na imagem!**

**Comment by alexxxmendonca** [comment]
@gitnnolabs neste caso vou fechar este ticket pois o problema foi resolvido, mas vou abrir outro para reportar este outro problema.

**Comment by gitnnolabs** [comment]
Por gentileza!

Vou, dá procedimento na atualização em produção, ok?

Dessa forma a questão da pesquisa por termos con "-", fica resolvida.

**Comment by gitnnolabs** [comment]
@alexxxmendonca o ambiente de produção foi atualizado com  esse ajuste, portanto agora é possível pesquisar pelos títulos: 

- SARS-COVID-19 transformed the world and urological practice
- The Social, Economic and Sanitary Impact of COVID-19 Pandemic
- The SARS-CoV-2 Coronavirus and the COVID-19 Outbreak

Qualquer dúvida estou a disposição!
