### ISSUE TITLE
Informação de suplemento não aparece na legenda bibliográfica

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#545]
### Descrição do problema
Nos casos de suplemento de volume, a informação de suplemento não está aparecendo na legenda bibliográfica:

![image](https://user-images.githubusercontent.com/4059679/129035371-327c602f-4be5-4870-923a-520015a51d15.png)

O documento acima faz parte do suplemento 1 do volume 46 do periódico International braz j urol, mas esta informação não aparece na legenda bibliográfica. 

### Passos para reproduzir o problema
1. Acesse a página https://search.scielo.org/?where=&filter%5Bin%5D%5B%5D=scl&filter%5Bjournal_title%5D%5B%5D=International+braz+j+urol&from=271&page=19
2. Procurar por documentos que pertençam ao volume 46 suplemento 1 (https://www.scielo.br/j/ibju/i/2020.v46suppl1/)
3. Observe que não aparece a informação de suplemento 1 na legenda bibliográfica.

### Comportamento esperado
A legenda bibliográfica deveria constar:

_International braz j urol Ago 2020, Volume 46 **Supl.** 1 Páginas X - Y_ (Português)
_International braz j urol Ago 2020, Volume 46 **Supl.** 1 Páginas X - Y_ (Espanhol)
_International braz j urol Ago 2020, Volume 46 **Suppl.** 1 Páginas X - Y_ (Inglês)

**Comment by gitnnolabs** [comment]
@alexxxmendonca poderia confirmar, mas me parece que esse tíquete já está resolvido.

**Comment by alexxxmendonca** [comment]
@gitnnolabs sim. Estou fechando-o pois de fato já está resolvido.
