### ISSUE TITLE
Alterar endereço físico do SciELO

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/search-journals#547]
### Descrição da tarefa
Alterar o endereço físico do SciELO que aparece no rodapé.

De:

Av. Onze de Junho, 269 - Vila Clementino 04041-050 São Paulo SP - Brasil

Para:

Rua Dr. Diogo de Faria, 1087 – 9º andar – Vila Clementino 04037-003 São Paulo/SP - Brasil

**Comment by gitnnolabs** [comment]
Tíquete já havia sido realizado.
