### ISSUE TITLE
Adicionar capacidade de enviar e-mail no processamento

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#56]
Atualmente o script de processamento do sistema de busca não notifica os interessados sobre o processamento o que obriga um acesso ao servidor para verificar o processamento.

Devemos adicionar a capacidade de envio de e-mail com um resumo do processamento para um lista disponível no config.ini.

**Comment by fabiobatalha** [comment]
Jamil, Como isso será disparado em cron. Veja com o Rondineli como configurar o envio de email direto pelo cron.
