### ISSUE TITLE
O link para o search não lista apenas os documentos do autor contido no link ...

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/search-journals#569]
### Descrição do problema
O link para o search não lista apenas os documentos do autor contido no link, tampouco retorna o artigo publicado em https://www.scielo.cl/scielo.php?script=sci_arttext&pid=S0718-50492021000100225&lng=es&nrm=iso&tlng=pt

O link original está publicado no Lattes da seguinte forma:

`http://www.scielo.br/cgi-bin/wxis.exe/iah/?IsisScript=iah/iah.xis&amp;base=article^dlibrary&amp;fmt=iso.pft&amp;lang=i&amp;nextAction=lnk&amp;indexSearch=AU&amp;exprSearch=MOTTA,+LUIZ+EDUARDO
`
e é redirecionado para 

`https://search.scielo.org/?lang=en&q=au:MOTTA,+LUIZ+EDUARDO`
pela aplicação do site novo (opac)

<img width="382" alt="Captura de Tela 2022-11-04 às 10 18 39" src="https://user-images.githubusercontent.com/505143/199982130-10214351-45d1-4c21-9fc9-0c25620f444a.png">

**Comment by gitnnolabs** [comment]
Verificado que o artigo não está no índice. 

Realizado o reprocessamento completo da coleção chile utilizando o comando: `update_search -c chl`

**Comment by gitnnolabs** [comment]
Agora o artigo está pesquisavel: https://search.scielo.org/?q=&lang=pt&count=15&from=0&output=site&sort=&format=summary&fb=&page=1&q=au%3A%22Motta%2C+Luiz+Eduardo%22&lang=pt&page=1

**Comment by gitnnolabs** [comment]
Item indexado: 

![Captura de Tela 2022-11-14 às 14 31 42](https://user-images.githubusercontent.com/86991526/201727059-02ff1d22-2354-4bcb-8f59-bafc411119a8.png)
