### ISSUE TITLE
Adicionar a capacidade de realizar busca pelo SciELO ID (PID)

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#70]
Atualmente não é possível realizar a pesquisa de forma simples pelo **PID** no http://search.scielo.org. 

O ideal seria colocarmos o **PID** na pesquisa livre e obtermos o artigo relacionado.

**Comment by deandr** [comment]
@jamilatta 

Atualmente temos no XML o elemento id (ex.: "art-S0256-95742008001100012-sza") que contem o prefixo **art-** e o sufixo da coleção **sza** na pesquisa o que deveria ser possível pesquisar seria somente a parte central do id  ("S0256-95742008001100012") este seria o **PID** correto?

**Comment by jamilatta** [comment]
@deandr

sim, somente pelo ID que seria: S0256-95742008001100012

2015-01-28 17:44 GMT-02:00 deandr <notifications@github.com>:

> @jamilatta <https://github.com/jamilatta>
>
> Atualmente temos no XML o elemento id (ex.:
> "art-S0256-95742008001100012-sza") que contem o prefixo *art-* e o sufixo
> da coleção *sza* na pesquisa o que deveria ser possível pesquisar seria
> somente a parte central do id ("S0256-95742008001100012") este seria o
> *PID* correto?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/search-journals/issues/70#issuecomment-71901690>
> .
>



-- 
Atenciosamente,

Jamil Atta Junior

**Comment by fabiobatalha** [comment]
@jamilatta só para entender, isso é uma demanda interna para validar algum tipo de atividade, correto?

Pq a busca por PID para o usuário final não faz sentido.

**Comment by jamilatta** [comment]
Sim.

2015-01-29 9:44 GMT-02:00 Fabio Batalha <notifications@github.com>:

> @jamilatta <https://github.com/jamilatta> só para entender, isso é uma
> demanda interna para validar algum tipo de atividade, correto?
>
> Pq a busca por PID para o usuário final não faz sentido.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/search-journals/issues/70#issuecomment-72011474>
> .
>



-- 
Atenciosamente,

Jamil Atta Junior
