### ISSUE TITLE
Adicionar OpenSearch

### ISSUE THREAD

**Issue by jfunez** [scieloorg/search-journals#74]
Para que o usuário consiga fazer buscas no sites scielo, desde o campo de busca do browser.
Tem que incluir um arquivo "OSDD" (OpenSearch Description Documents) que é um arquivo xml semelhante com o seguinte 
(i.e. ``scielo_opensearch.xml``):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<OpenSearchDescription
  xmlns="http://a9.com/-/spec/opensearch/1.1/"
  xmlns:moz="http://www.mozilla.org/2006/browser/search/">
  <ShortName>SciELO.org search</ShortName>
  <Description>Search SciELO.org  articles</Description>
  <InputEncoding>UTF-8</InputEncoding>
  <Image width="16" height="16" type="image/x-icon">http://scielo.org/favicon.ico</Image>
  <Url type="text/html" method="get" template="http://search.scielo.org/?q={searchTerms}"/>
</OpenSearchDescription>
```
E nas páginas (geralmente a homepage) do site, tem que  adicionar dentro do tag ``<head>`` ... ``</head>`` a seguinte linha para incorporar o arquivo OSDD e o browser reconhecer:
a seguinte linea para informar para o browser que tem uma definição:
```html
<link rel="search" type="application/opensearchdescription+xml" title="Scielo.org" href="scielo_opensearch.xml" />
```
Depois disso, o usuário que visita a página (homepage do site sielo por exemplo) deve notar que pode adicionar um search engine, e se for selecionado, todas as consultas feitas na caixa de busca, serão redirecionadas ao site search.scielo.org como indicado no arquivo OSDD (xml)

Para mais informação:
- http://www.opensearch.org/Specifications/OpenSearch/1.1
- http://www.xml.com/lpt/a/1708

**Comment by deandr** [comment]
Verificando este issue com mais calma acredito que o mesmo precise ser implementado no nível do site principal (http://scielo.org)  para que esteja de acordo com as especificações, correto? Vale a pena implementar somente no dominio da pesquisa (http://search.scielo.org)? 

[]s

**Comment by gustavofonseca** [comment]
@deandr, concordo que deve ser implementado no portal scielo.org. Inclusive penso que também deve ser implementado nos diferentes sites de catálogo (scielo.br <http://scielo.br/>, scielo.ar <http://scielo.ar/>, …).
