### ISSUE TITLE
Aplicação de nova proposta de design

### ISSUE THREAD

**Issue by deandr** [scieloorg/search-journals#75]
Aplicação de  novo layout (html, css e javascript) para interface de pesquisa do portal SciELO.org proposto através de protótipo enviado por email na data de 12/01/2015 por Fabio Batalha.

**Comment by alexxxmendonca** [comment]
O que deve ser validado nesse ticket? Considerando os ajustes pendentes....

**Comment by deandr** [comment]
Este ticket somente indica que todos os elementos do layout do protótipo estão presentes na interface. 

Acredito que todos os componentes visuais tenham sido aplicados.

[]s

**Comment by alexxxmendonca** [comment]
Acredito que falta apenas no rodapé as opções de alterar a quantidade de itens por página e mudar de página:

![image](https://cloud.githubusercontent.com/assets/4059679/8306571/552737ee-198f-11e5-8c3a-9c915b00e73a.png)

**Comment by alexxxmendonca** [comment]
Quantidade de downloads e citação também está ausente. 

Isso será implantado nesse momento?

"Citado 10 vezes no SciELO Citation Index 438 downloads no SciELO Cuba"

**Comment by jamilatta** [comment]
Sim, estamos trabalhando nisso para que possamos inserir isso na interface.

**Comment by alexxxmendonca** [comment]
Ok, aguardo apenas uma posição referente ao rodapé, então (https://github.com/scieloorg/search-journals/issues/75#issuecomment-114493907).

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
