### ISSUE TITLE
Caixa de configuração para os filtros

### ISSUE THREAD

**Issue by deandr** [scieloorg/search-journals#77]
Implementar layout e funcionalidades para caixa de configuração dos filtros de busca:

![filter_config box](https://cloud.githubusercontent.com/assets/5338655/8132040/316454e2-10f5-11e5-9002-8080be4d5bc0.png)

**Comment by alexxxmendonca** [comment]
Na caixa "Selecionar", se você apenas clica no nome do item, ele remove o filtro:

![image](https://cloud.githubusercontent.com/assets/4059679/8305172/db67675a-1982-11e5-9c47-ef85f19eda40.png)

Penso que o comportamento deveria ser: primeiro des-selecionar, depois o usuário deve confirmar a seleção final clicando em "Aplicar filtros". 

Ao clicar no checkbox funciona como deveria, mas penso que o comportamento no nome do item deve ser alterado para marcar/desmarcar o checkbox.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
