### ISSUE TITLE
Criar texto de ajuda nos 3 idiomas (Português, Inglês e Espanhol)

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#80]
Devemos criar o texto nos 3 idiomas para o texto de ajuda que iram na interface nova do sistema de busca da SciELO.

**Comment by deandr** [comment]
@alexxxmendonca 

Já existe uma definição se será disponibilizado o texto de ajuda na interface ou se iremo desabilitar o icone por enquanto?

[]s

**Comment by alexxxmendonca** [comment]
Será desabilitado.

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
