### ISSUE TITLE
Criar a lista de anos de forma dinâmica

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#81]
Precisamos pensar em um jeito bom de criar essa lista de anos, repare que em 2016 não terei a opção de selecionar o ano 2015 nem o próprio 2016.

![screen shot 2015-04-22 at 16 47 59](https://cloud.githubusercontent.com/assets/373745/7283825/9e6e1964-e90f-11e4-9c1b-0fbbd409f5b8.png)

**Comment by alexxxmendonca** [comment]
O campo ano tem alguns valores absurdos do tipo "0", "1" etc.

Penso que o ano mais antigo deve ser o ano da publicação mais antiga na base.

**Comment by deandr** [comment]
Para informar o ano mais antigo que deve ser apresentado na lista é necessário adicionar o seguinte elemento no arquivo config.xml da interface:
```
<publication_year_start>ano-da-publicacao-mais-antiga</publication_year_start>
```
ex:
```
<publication_year_start>1997</publication_year_start>
```

[]s

**Comment by fabiobatalha** [comment]
Incluido.

**Comment by fabiobatalha** [comment]
Os novos anos não estão mais cravados no template?

Quando houver a virada para 2016 a lista será atualizada automaticamente?

**Comment by deandr** [comment]
Exato, não existe mais nada cravado nos templates. 

O template usa a data atual do servidor para definir o ano corrente e o ano informado no config para o ano inicial.
