### ISSUE TITLE
Ação no filtro dos clusters

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#82]
Na interface anterior ao selecionar um item no cluster, automaticamente é realizado a filtragem, nessa nova interface não temos esse comportamento, qual a melhor maneira de fazermos isso? pensando na usabilidade??

**Comment by fabiobatalha** [comment]
O ideal seria disparar a filtragem automaticamente.

**Comment by alexxxmendonca** [comment]
Isso foi aprovado nas iterações entre o designer e o SciELO. O correto é: aplicar os filtros automaticamente.

Pelos meus testes em homologação, isso já está aplicado. Estou fechando esse ticket.
