### ISSUE TITLE
Validar com o internet explorer 8 e 9 

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#84]
Acessa a aplicação com IE 8 e 9 para visualizar o comportamento da interface.

**Comment by jamilatta** [comment]
Testes do browser IE 8 realizados no endereço: http://scielohomolog.parati.ag/iAHx/index.html e aparentemente funcionando perfeitamente, ver: 


![screen shot 2015-05-06 at 11 43 29](https://cloud.githubusercontent.com/assets/373745/7495649/9e957348-f3e5-11e4-90cb-f32e0260d3e5.png)

**Comment by deandr** [comment]
@alexxxmendonca 

Você poderia dar uma olhada neste ticket? 

Obrigado

**Comment by alexxxmendonca** [comment]
Eu não tenho IE 8 ou 9 na minha máquina. Alguma sugestão? Algum site faz emulação?

**Comment by jamilatta** [comment]
Irei solicitar para a infra uma máquina com IE 8 e 9 para que possa testar
e logo te passo.

On Tue, Jun 30, 2015 at 10:36 AM, alexxxmendonca <notifications@github.com>
wrote:

> Eu não tenho IE 8 ou 9 na minha máquina. Alguma sugestão? Algum site faz
> emulação?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/search-journals/issues/84#issuecomment-117187085>
> .
>



-- 

Jamil Atta Junior

**Comment by alexxxmendonca** [comment]
Utilizei um acesso remoto fornecido pelo @jamilatta conectado a antares.scielo.org para fazer os testes.

A busca não executa. Não sai da primeira página. Após clicar em "Search", nada acontece.

Testei no IE 9.

Outro problema que notei foi: ao clicar em "Ano de publicação -> A partir de", fico impossibilitado de clicar em "Todos os anos". O botão de rádio não é mais selecionável.

**Comment by deandr** [comment]
@alexxxmendonca,

Realizei alguns testes usando o ambiente www.browserstack.com na versão Free e não tive grandes problemas de uso com IE 9 e mesmo o 8. 

Quando possível poderia fazer uma avaliação?

Obrigado.

**Comment by alexxxmendonca** [comment]
Testado as versões 8 e 9 do IE através do http://www.browserstack.com/. Consegui fazer a busca, mas os problemas reportados nos tickets #142 e #143 persistem nessas versões.

**Comment by alexxxmendonca** [comment]
Testado as versões 8 e 9 do IE através do http://www.browserstack.com/. 

Os problemas reportados nos tickets #142 e #143 persistem.

**Comment by deandr** [comment]
@alexxxmendonca 

Obrigado pela nova validação. Este é um problema chato de resolver pois vou precisar criar a estrutura de testes em um computador com estas versões antigas do IE para tentar isolar o problema. 

Assim que conseguir avançar neste problema aviso.

[]s

**Comment by alexxxmendonca** [comment]
Ticket #142 resolvido no IE 8 e 9, entretanto, no IE 9 apareceu o valor "null" dentre os resultados:

![image](https://cloud.githubusercontent.com/assets/4059679/8679380/bda9b376-2a30-11e5-959c-b1b4f0e735b9.png)

Ticket #143 resolvido no IE 9, mas no IE 8 dá a seguinte mensagem de erro:

![image](https://cloud.githubusercontent.com/assets/4059679/8679391/d6725b56-2a30-11e5-95d9-1067ea887683.png)

**Comment by deandr** [comment]
@alexxxmendonca 

Não consegui trabalhar neste issue nesta iteração uma vez que o browserstack aparentemente agora não esta mais permitindo o teste com as versões anteriores do IE na conta grátis. Vou ter que encontrar uma alternativa para poder realizar os ajustes.

[]s

**Comment by deandr** [comment]
@alexxxmendonca,

Consegui corrigir a apresentação dos valores no gráfico com valores "null" no IE9.

@fabiobatalha,

Deste issue o único item que não foi possível resolver foi referente ao link de baixar o CSV que não funciona no IE8. Já fiz várias tentativas mas não encontrei o problema. Dado que esta versão do browser já tem 6 anos (o IE8 é de 2009) podemos considerar que devido a incompatibilidade com os navegadores atuais este item não pôde ser resolvido?

[]s

**Comment by scielo** [comment]
Vinícius,

Estou de acordo.

*Fabio Batalha C. Santos*
Colegiado SciELO
www.scielo.org
FAPESP - CNPq - BIREME - FapUNIFESP

2015-08-28 14:52 GMT-03:00 deandr <notifications@github.com>:

**Comment by deandr** [comment]
@alexxxmendonca,

Quando possível favor validar pelo browserstack se o erro dos valores "null" foi resolvido para o IE9. Caso esteja OK favor fechar este issue.

Obrigado.

**Comment by alexxxmendonca** [comment]
Testado e aprovado utilizando o browserstack (IE9).
