### ISSUE TITLE
Testar interface com o ipad

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#85]
A interface da aplicação deve ter a capacidade de adaptar à tela do Ipad.

**Comment by deandr** [comment]
@jamilatta ou @alexxxmendonca,

Como todos os elementos do protótipo já foram aplicados na interface seria possível validar este ticket levando em consideração o mesmo comportamento do protótipo no Ipad.

Obrigado

**Comment by alexxxmendonca** [comment]
Ainda falta o item "Mostrar tudo", eu acho (#88).

Vocês acham que faz sentido validar no iPad agora, tendo em vista que há outros ajustes a serem feitos? Eu penso que seria melhor deixar essa validação mais pra frente, pois a correção de um bug pode desencadear em outro...

**Comment by jamilatta** [comment]
De acordo @alexxxmendonca.

**Comment by alexxxmendonca** [comment]
Os clusters e suas opções funcionam bem, assim como o "Mostrar mais".

Entretanto, não aparece as opções de "Imprimir | Enviar por e-mail | Exportar | Compartilhar" (talvez por uma questão de interface? não sei) e também a paginação, tanto acima quanto abaixo, o que eu considero mais grave:

![img_0067](https://cloud.githubusercontent.com/assets/4059679/8851926/a26b7f28-3128-11e5-8f3c-8554d377589f.PNG)
![img_0068](https://cloud.githubusercontent.com/assets/4059679/8851929/a53e4a82-3128-11e5-882a-92532cf894d6.PNG)

**Comment by alexxxmendonca** [comment]
Acabo de perceber também, pelos prints, que os resumos estão aparecendo. Não deveriam ser links também?

**Comment by deandr** [comment]
@alexxxmendonca 

As opções de "Imprimir | Enviar por e-mail | Exportar | Compartilhar" são realmente escondidas quando se esta na visualização por tablet por implementação do designer, podendo ser verificado usando o endereço do protótipo.

A paginação só irá aparecer na parte de baixo do resultado, já realizei o ajuste para ficar de acordo com o protótipo.

Quanto aos resumos, ainda não consegui localizar como ele ativou o formato alternativo de display.  Por acaso você ao realizar o teste usou algum bookmark já salvo anteriormente no tablet ou digitou no campo de URL o caminho http://homolog.search.scielo.org/? Poderia tentar limpar o cache do navegador do tablet ou mesmo testar na versão do Chrome do tablet para verificar se isso também ocorre?

@jamilatta 

Se puder realizar novo update do ambiente de homologação já será possível validar este problema de display encontrado pelo Alex.

[]s

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/ no iPad
