### ISSUE TITLE
Páginas de help dinâmicas

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#86]
Atualmente no layout novo as páginas de help estão estáticas....isso é bastante ruim. 

Para que possamos atender as necessidade de ajuda para os usuário é imprescindível que tenhamos a página de help dinâmica nos três idiomas, permitindo que a equipe responsável pelo preenchimento e atualização possa atualizar de forma continua e sobre demanda.

**Comment by fabiobatalha** [comment]
As páginas de ajuda, se necessárias, serão criadas sob demanda. O desenvolvimento de uma ferramenta de help dinâmica deve ser considerada em uma nova implementação se julgado futuramente que essa demanda é necessária.
