### ISSUE TITLE
Testar mensagem de manutenção.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#87]
Descobri que a interface tem a capacidade de mostrar uma msg de manutenção, ver: 

```php
 {% if config.maintenance == 'true' %}
        <div class="noResults">
            {{ texts.MAINTENANCE }}
        </div >   
   {% else %}
```

Precisamos testar isso com a nova interface.

**Comment by deandr** [comment]
@fabiobatalha ou @jamilatta 

Quando possível este item já pode ser avaliado.

Para o teste alterar o elemento **maintenance** no config.xml para o valor **true**.  Com isso o sistema passará a apresentar uma mensagem definida no arquivo de tradução com o identificador MAINTENANCE.

[]s

**Comment by jamilatta** [comment]
@deandr 

está funcionando, mas acho que os termos não estão bons... no arquivo de configuração o param é de manutenção e na interface informamos para o usuário que estamos **atualizando dados**...

Qual é a real intenção desse param?  Sugiro que a msg para o usuário seja consistente com o param até para que a equipe infra-estrutura consiga utiliza-lo sem que tenha uma surpresa na msg para os usuários.

Ou melhor seria se fosse possível indicar a app  como indisponível e adicionarmos uma msg para cada situação, se existe essa opção, por gentileza, nos informe.

**Comment by deandr** [comment]
@jamilatta,

A mensagem que é apresentada ao usuário esta presente nos arquivos de tradução locais da interface e podem ser alterado como achar mais adequado.

Este parâmetro pode ser usado quando existe uma falha de inicialização do Solr  ou mesmo quando é necessário o ajuste de configuração do Solr onde o mesmo terá que ser re-iniciado, em ambiente com índices grandes, não é o caso da SciELO, este processo de re-start pode levar de 10 a 20 minutos, onde a mensagem é apresentada ao usuário.

Como a mensagem esta sendo apresentada sugiro ou fechar este issue ou caso seja desejável melhorias marcar como "Melhorias" e remover o milestone de "Escopo de implementação ..."

[]s

**Comment by jamilatta** [comment]
@deandr 

obrigado pela explicação, mas acho que não mudou nada sobre meu comentário... **se a msg é genérica o param também deve ser**.
