### ISSUE TITLE
Testar "Mostrar mais" nos aglomerados (clustes)

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#88]
Lembro que dependendo da quantidade de itens nos aglomerados (clusters) tinhamos problemas, devemos testar esse item com atenção.

**Comment by deandr** [comment]
@alexxxmendonca 

Você poderia dar uma olhada neste ticket? Nos meus testes não consegui identificar o problema.

Obrigado

**Comment by alexxxmendonca** [comment]
Esse link não está aparecendo. 

Seria o "Mostrar tudo"?

![image](https://cloud.githubusercontent.com/assets/4059679/8431925/27aced8e-1f13-11e5-8f0e-e859081685ac.png)

**Comment by deandr** [comment]
Na verdade seria o "Mostrar mais ...." uma vez que a interface só mostra de 10 em 10 itens dos filtros.

A coleção atual da homologação aparentemente não possui nenhum conjunto com mais de 10 itens nos filtros, por isso o link não aparece. No meu ambiente local sim aparece. 

@jamilatta 

Teria como adicionar algumas outras coleções no índice de homologação para que seja possível validar este ticket?

[]s

**Comment by jamilatta** [comment]
Irei adicionar todas as coleção para o teste e logo aviso para vcs.

2015-06-30 10:36 GMT-03:00 deandr <notifications@github.com>:

> Na verdade seria o "Mostrar mais ...." uma vez que a interface só mostra
> de 10 em 10 itens dos filtros.
>
> A coleção atual da homologação aparentemente não possui nenhum conjunto
> com mais de 10 itens nos filtros, por isso o link não aparece. No meu
> ambiente local sim aparece.
>
> @jamilatta <https://github.com/jamilatta>
>
> Teria como adicionar algumas outras coleções no índice de homologação para
> que seja possível validar este ticket?
>
> []s
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/search-journals/issues/88#issuecomment-117187142>
> .
>



-- 

Jamil Atta Junior

**Comment by alexxxmendonca** [comment]
De acordo com o @jamilatta, a base foi atualizada para incluir mais registros. Entretanto os links "Mostar tudo" ainda não aparecem...

**Comment by deandr** [comment]
@jamilatta 

Revisando as configurações da interface verifiquei que o limite de itens dos filtros configurado na interface não esta mais pareado com o limite informado no solrconfig.xml alterado no commit abaixo:

https://github.com/scieloorg/search-journals/commit/b9aa9b9d0e502bcccf03463afe6c15e9dc49072b#diff-d572082f9c0b87219e9e494cfd238ad4L198

Poderia por gentileza alterar o elemento **cluster_items_limit** do arquivo config.xml da interface  para:

```
<cluster_items_limit>5</cluster_items_limit>
```

Obrigado
[]s

**Comment by jamilatta** [comment]
@deandr e @alexxxmendonca realizei o ajuste solicitado, por gentileza verifiquem.

**Comment by alexxxmendonca** [comment]
Percebi que ele mostra mais alguns itens, mas na interface proposta pelo designer, o correto seria mostrar tudo (tanto que o link chama "Mostrar tudo" ao invés de "Mostrar mais..."

Algum motivo para essa mudança de comportamento?

Além disso, algums países aparecem como "Ury" e "Bol" ao invés de "Uruguai" e "Bolívia".

**Comment by jamilatta** [comment]
Outra coisa que percebi é que o **"Mostrar mais..."** não persiste ao realizarmos uma pesquisa, ou seja se clicarmos em "Mostrar mais" em qualquer **"cluster"** e realizamos uma pesquisa os **"clusters"** volta para o estado anterior sem mostrar mais registros com solicitado anteriormente.

**Comment by deandr** [comment]
@alexxxmendonca 

Sim o comportamento da interface é mostrar sempre mais itens (no caso sempre mais 5) e não mostrar tudo como proposto. 

@jamilatta 

Sim este é o comportamento padrão da interface, conforme pode ser observado na versão atual em produção que funciona da mesma forma.

[]s

**Comment by jamilatta** [comment]
@deandr 

devemos seguir a interface proposta e não a atual, além disso acredito que "Mostrar mais..." é uma operação cansativa e chata para o usuário, voto por mantermos o "Mostrar tudo", assim com está na interface fechada entre a SciELO e o designer e entre a SciELO e você.

@alexxxmendonca peço sua opinião...

**Comment by alexxxmendonca** [comment]
Eu concordo com @jamilatta. É ruim ter que ficar clicando várias vezes, o tempo de espera é de cerca de 1 segundo (muito tempo rs)

Se for possível, voto pelo "Mostrar tudo"

**Comment by deandr** [comment]
Concordo com os comentários mais infelizmente esta opção não é possível de se implementar uma vez que o valor do limite que é retornado por filtro é informado através de uma configuração do Solr (solrconfig.xml) e só é lido no momento de start do serviço não sendo passado por parâmetro externo.

Sugiro voltar a configuração para 10 itens por filtro para que não fique tão cansativo para o usuário. 

[]s

**Comment by jamilatta** [comment]
@deandr 

poderia justificar **tecnicamente** por que é impossível de implementarmos a funcionalidade considerando a interface proposta.

**Comment by deandr** [comment]
Os valores de limite de itens por cluster são controlados pelo parâmetro **facet.limit** configurado no arquivo ***solrconfig.xml*** no elemento ```<lst name="invariants">```. Este arquivo de configuração só é lido no momento de inicialização da aplicação Solr. 

No uso padrão da interface de pesquisa configuramos este valor para 10 ou 15 itens e depois é feita a paginação solicitando ao Solr que envie os próximos itens do cluster mas não é possível alterar o valor de itens retornados uma vez que este valor já registrado na inicialização do Solr. 

Existe a possibilidade de configurar este valor para *sem limite* o que causaria ao serviço Solr sempre retornar todas as possíbilidade de itens dos clusters. Esta opção só é recomendada para clusters com poucos itens (idioma, tipo de documento, etc) pois torna a resposta extremamente lenta para clusters com muitos valores (revista, etc).

[]s

**Comment by alexxxmendonca** [comment]
Possível sugestão sugerida pelo Abel:

"Uma solução é avisar o usuário - this may take several minutes. E uma opção de cancelar."

**Comment by fabiobatalha** [comment]
Isso não é uma solução, isso é jogar o problema para o usuário, que óbvio não esperará para carregar uma pagina tão grande e tão lenta, além de ser necessário investimentos em outras frentes tais como capacidade de processamento dos servidores, aumento de memória para otimização de recuperação de conteúdo, etc...

Esse ticket será encerrado. Como explicitado por @deandr, a necessidade de carregar a lista completa de clusters para realizar o sort pela lista completa se torna inviável na arquitetura atual do IAHx devido ao custo de processamento, tempo de carga do site para todas as requisições, etc.

Sugerimos a inclusão desta reformulação complexa da arquitetura do IAHx no core do projeto IAHx.

**Comment by deandr** [comment]
@fabiobatalha,

OK, de acordo. 

@alexxxmendonca,

Sugiro retornarmos os valores anteriores de configuração da quantidade de itens que devem ser mostrados nos clusters. O valor atual é de apenas 5 itens, a interface em produção esta configurado para 10 itens o que acredito seja mais prático para o usuário no momento de avaliar as opções disponíveis e também carregar mais itens. Concorda?

[]s

**Comment by alexxxmendonca** [comment]
Carregar 10 ao invés de 5? Isso provavelmente vai deixar a coluna da esquerda maior do que o conteúdo da página, resultando em uma aparência desproporcional.

**Comment by deandr** [comment]
Correto, de 5 para 10 itens. 

Note que a interface em produção esta configurado para 10 itens por cluster e 20 artigos por página, em homologação a quantidade de artigos foi reduzida para 10 artigos com 5 itens no cluster. Se alterarmos para a mesma configuração da produção acredito que as colunas fiquem proporcionais. Mas vocês decidem o que seria melhor para o usuário.

[]s

**Comment by alexxxmendonca** [comment]
Concordo em alterar de 5 para 10 desde que os resultados sejam alterados de 10 para 20.

**Comment by deandr** [comment]
OK. Caso vocês julguem que não ficou melhor retornamos aos valores anteriores.
