### ISSUE TITLE
Indexar de forma separadas os dados da referência bibliografica

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#89]
Atualmente temos os dados da referência bibliografica indexado de forma a não permitir uma granularidade, segue: 

```json
"fo": [
          "Sci. agric. (Piracicaba, Braz.); 67(2); 0-0; 2010-04"
        ],
```

Devemos alterar isso para itens mais específicos, sugiro:

```json
[
  {"abrev_source": "Sci. agric. (Piracicaba, Braz.)"},
  {"volume": 67},
  {"number": 2},
  {"start_page": 0},
  {"end_page": 0},
  {"publication_date": 2010-04},
]
```
 Ano de publicação devemos utilizar recurso do sistema de template para traduzir para meses de forma literal.

**Comment by deandr** [comment]
OK, os campos serão adicionados no schema.xml mas será necessário o ajuste na article API para retornar estes valores quando informado o parâmetro format=xmliahx.

**Comment by jamilatta** [comment]
:+1:

**Comment by alexxxmendonca** [comment]
O dado do número do fascículo não está aparecendo para nenhum registro.

Exemplo:

<i>Cadernos de Saúde Pública Jan 2012 Volume 28 Nº Páginas 21 - 30</i>

**Comment by jamilatta** [comment]
Item realizado.
