### ISSUE TITLE
Desenvolver uma app para criar o menu de links do SciELO

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#90]
Devemos criar um app para fornecer o menu de links da SciELO, inicialmente esse menu esta sendo incorporado no sistema de busca da SciELO, porém segundo o designer iremos utilizar o mesmo em todas as interfaces: 

Para que tenhamos idéia, ver o menu de links SciELO: 

![screen shot 2015-04-29 at 17 21 25](https://cloud.githubusercontent.com/assets/373745/7400565/36cd63d4-ee94-11e4-8ea9-7b75c42b25b0.png)

Dessa forma garantimos que qualquer alteração nesse menu seja replicado para todas as aplicações. 

Irei especificar melhor essa necessidade.

**Comment by fabiobatalha** [comment]
Esse desenvolvimento faz parte de um novo produto do SciELO e não esta vinculado especificamente a interface de busca.

Por hora a interface de busca não terá essa barra, devendo apenas manter os links para o SciELO ORG e blog em Perspectiva.

Portal do autor deve ser removido pois ainda não existe esse produto.

**Comment by fabiobatalha** [comment]
Manter apenas os seguintes links:

SciELO.org - Rede SciELO
Coleções nacionais e temáticas
Lista alfabética de periódicos
Lista de periódicos por assunto
Métricas
Acesso OAI e RSS
Sobre a rede SciELO

**Comment by deandr** [comment]
@alexxxmendonca 

Quando possível favor avaliar este ajuste nos itens disponíveis no menu superior conforme orientação do Fábio.

Obrigado.

**Comment by alexxxmendonca** [comment]
Estou de acordo. Os links que foram removidos foram "Busca" e "Contatos".

"Busca" é um pouco redundante mesmo, uma vez que você já está no ambiente de busca. E "Contatos" não foi especificado o conteúdo até o momento.

De qualquer forma, penso que deve ser fácil incluir esses 2 itens em uma versão futura, se for necessário.

**Comment by deandr** [comment]
OK. Favor fechar este issue e se necessário re-abrimos se for necesário algum ajuste.
