### ISSUE TITLE
Desenvolver uma app para criar o footer do SciELO

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#91]
Devemos criar um app para fornecer o footer da SciELO, inicialmente esse footer esta sendo incorporado no sistema de busca da SciELO, porém segundo o designer iremos utilizar o mesmo em todas as interfaces:

Para que tenhamos idéia, ver o menu de links SciELO:
![screen shot 2015-04-29 at 17 38 01](https://cloud.githubusercontent.com/assets/373745/7400901/84ab727e-ee96-11e4-9ff5-d76eb10199e0.png)

Dessa forma garantimos que qualquer alteração nesse footer seja replicado para todas as aplicações.

Irei especificar melhor essa necessidade.

**Comment by fabiobatalha** [comment]
Legal jamil. Esse item pode ser discutido internamente e posteriormente planejado para substituir os footers das aplicações SciELO.

Se tivermos algo pronto antes do termino dos desenvolvimentos da interface de pesquisa, podemos agregar como atividade a implantação deste footer.
