### ISSUE TITLE
Melhorar o Label dos aglomerados (clusters)

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#92]
Os títulos do aglomerados são muito ruins... para facilitar a vida de que usa os aglomerado devemos criar um tooltip que permita que o usuário possa visualizar de uma melhor forma. 

Por exemplo no aglomerado de periódico: 
![screen shot 2015-04-29 at 18 06 48](https://cloud.githubusercontent.com/assets/373745/7401457/95b24ada-ee9a-11e4-85fa-a8a819f92a58.png)

Nesse exemplo em específico, podemos ter o nome completo da revista no tooltip.

**Comment by alexxxmendonca** [comment]
#229

**Comment by alexxxmendonca** [comment]
Será tratado no #229
