### ISSUE TITLE
A home page do sistema de busca deve permitir parâmetros de configuração.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#93]
Visando atender as necessidades futuras, repare: http://scielohomolog.parati.ag/Periodico/buscar.html, precisamos garantir que a home page do sistema de busca seja a mesma e permita algumas customizações.

**Comment by fabiobatalha** [comment]
Essa implementação esta relacionada a interface do novo site SciELO. No devido momento podemos avaliar se iremos replicar os HTML's ou se será desenvolvido um serviço específico para ser embutido em qualquer site SciELO.
