### ISSUE TITLE
Desenvolver uma forma de evitar o uso de chaves indexadas no código.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#94]
Esse tipo de código foi incorporado no primeiro PR: https://github.com/scieloorg/search-journals/pull/83, mas ficou acertado que isso será corrido, segue:

Exemplo https://github.com/scieloorg/search-journals/pull/83#discussion-diff-29370897L111

**Comment by deandr** [comment]
O código mencionado não foi incorporado neste PR, conforme pode ser visto o mesmo já esta no branch master e esta em uso desde a primeira versão do interface.

https://github.com/scieloorg/search-journals/blob/master/iahx/templates/custom/result-clusters.html

A verificação com uso de chaves indexadas é necessário para não apresentar dados não normalizados nas coleções, caso eu remova estas verificações será necessário normalizar os dados antes da indexação.
