### ISSUE TITLE
Ajustar o formato das referências bibliográficas para o layout proposto

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#96]
Esse código foi incorporado do primeiro PR: https://github.com/scieloorg/search-journals/pull/83, porém deverá ser ajustado conforme o comentário: https://github.com/scieloorg/search-journals/pull/83#discussion-diff-29374325L3

**Comment by jamilatta** [comment]
O formato ainda não esta de acordo com o entrega realizada pelo designer está faltando o nome da revista nas referências bibliograficas, no ambiente de homologação foi adicionado o título do periódico, repare: 

![screen shot 2015-05-21 at 15 05 40](https://cloud.githubusercontent.com/assets/373745/7755545/4b41d744-ffcb-11e4-9847-7d1ec0c9e7a2.png)

**Comment by deandr** [comment]
O formato esta de acordo com os campos definidos no issue https://github.com/scieloorg/search-journals/issues/89

**Comment by jamilatta** [comment]
OK, irei criar um novo ticket para essa alteração de **chave** assim como acertamos nos comentários do PR: https://github.com/scieloorg/search-journals/pull/112

**Comment by deandr** [comment]
Perfeito. As alterações dos nomes dos atributos (chaves) indexados e usados no display da pesquisa serão consideradas após a conclusão deste projeto de aplicação do novo layout para não impactar nas entregas do projeto.

**Comment by jamilatta** [comment]
OK.

**Comment by alexxxmendonca** [comment]
Está faltando os separadores (vírgula). Está faltando o dado do número.

Como está:
Pesquisa Agropecuária Brasileira Nov 2011 Volume 46 Nº Páginas 1415 - 1423

Como deve ser:
Pesquisa Agropecuária Brasileira, Nov 2011, Volume 46, Nº <b>(DADO FALTANDO)</b>, Páginas 1415 - 1423

**Comment by jamilatta** [comment]
O dado de volume está disponível no índice, ver: 
![screen shot 2015-05-26 at 15 41 20](https://cloud.githubusercontent.com/assets/373745/7820277/cfa2c098-03bd-11e5-920c-024f5977d06d.png)

**Comment by alexxxmendonca** [comment]
Nesse caso, seria o dado do "issue". o Dado "volume" já está aparecendo.

**Comment by fabiobatalha** [comment]
O issue esta logo abaixo.

**Comment by deandr** [comment]
No ticket https://github.com/scieloorg/search-journals/issues/89 esta informado que o campo seria "number", devemos assumir "issue" para esta informação?

**Comment by scielo** [comment]
Na JATS, no SciELO SPS e em outros formatos o número é sempre identificado
como issue.

Acho que não precisamos mudar, a não ser que exista uma justificativa
plausível.



*Fabio Batalha C. Santos*
Colegiado SciELO
www.scielo.org
FAPESP - CNPq - BIREME - FapUNIFESP

**Comment by deandr** [comment]
OK, será ajustado no formato de display.

**Comment by jamilatta** [comment]
@deandr 

por gentileza, considerar os campos no arquivo ``schema.xml``

**Comment by deandr** [comment]
@jamilatta 

Obrigado. Favor notar que ambos os campos **number** e **issue** estão definidos no schema.xml por isso a dúvida. 

Como foi informado **issue** como correto vou ajustar o formato e aproveitar e remover do schema para evitar problemas futuros.

[]s

**Comment by alexxxmendonca** [comment]
A questão do número foi corrigido, mas o dado do mês está incorreto. Está aparecendo "0" ou "-1":

**Comment by deandr** [comment]
@fabiobatalha ou @jamilatta,

Poderiam por gentileza me confirmar o formato da string que é enviada na indexação do elemento "da" do Solr, pois não consigo visualizar por aqui.

Estou seguindo o exemplo descrito no schema.xml  (Ex. 200401) 
https://github.com/scieloorg/search-journals/blob/beta/solr/schema.xml#L106

Mas aparentemente não esta neste formato.

[]s

**Comment by jamilatta** [comment]
Segue: 
![screen shot 2015-06-02 at 10 15 49](https://cloud.githubusercontent.com/assets/373745/7936563/66814726-0910-11e5-93f4-899850c95e7f.png)

**Comment by deandr** [comment]
Obrigado.

Já realizei o ajuste no formato, se for possível realizar novo git pull no homolog deve resolver o display.

[]s

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
