### ISSUE TITLE
Remover resumo do resultado de busca

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#97]
No primeiro PR: https://github.com/scieloorg/search-journals/pull/83, no resultado de pesquisa esta sendo exibido o resumo isso não esta em conformidade com o layout, ver: 
![screen shot 2015-04-30 at 10 49 21](https://cloud.githubusercontent.com/assets/373745/7414107/d2c74a74-ef26-11e4-9723-83fd0dd84a21.png)

Layout Proposto: 
![screen shot 2015-04-30 at 10 52 43](https://cloud.githubusercontent.com/assets/373745/7414153/156e3518-ef27-11e4-94fd-3a8390dabdf3.png)

**Comment by jamilatta** [comment]
O resumo continua no resultado da pesquisa.

**Comment by deandr** [comment]
Conforme o título do commit a correção este ponto é feito alterando o config da instância conforme o commit refere-se: https://github.com/deandr/search-journals/commit/04703a126e4d03bc88d7a17884f7b98588c0e44b

**Comment by jamilatta** [comment]
Qual alteração deve ser feita? Peço que qualquer alteração de configuração isso seja informado no ticket.

**Comment by deandr** [comment]
A alteração a ser realizada esta no link do meu último comentário.

**Comment by deandr** [comment]
Favor alterar o arquivo config.xml do sistema no item <format_list> para:
<format_list>
    <format>
         	<name>summary</name>
    </format>
</format_list>

**Comment by deandr** [comment]
Este item ainda esta pendente de ajuste no arquivo de configuração config.xml para que possa ser validado.

**Comment by fabiobatalha** [comment]
Fiz a configuração, deve ser feito algo mais? O ajuste não surtiu efeito.

**Comment by deandr** [comment]
Não, só é necessário carregar a página inicial da inteface novamente. Aqui já consegui validar que o formato de display não exibe mais o resumo.

**Comment by fabiobatalha** [comment]
verdade. Esta ok agora.

**Comment by deandr** [comment]
Aproveitando se puder realizar mais o ajuste abaixo no config.xml já validamos outro issue:

https://github.com/scieloorg/search-journals/issues/81#issuecomment-105634410

Obrigado. []s
