### ISSUE TITLE
Alterar os logos do SciELO 

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#98]
SciELO fica responsável por enviar os logos corretos para o @deandr, para que seja alterado, já qua qualidade dos logos não está boa, devemos conversar com o designer para sabermos qual o melhor formato de logo devemos fazer.

Estes logos foram incorporados no primeiro PR:  https://github.com/scieloorg/search-journals/pull/83

**Comment by jamilatta** [comment]
Logo não alterado, verifique no ambiente de homologação.

**Comment by deandr** [comment]
@jamilatta,

Conforme descrito no ticket: "SciELO fica responsável por enviar os logos corretos para o @deandr, para que seja alterado ..."

Os novo logos nunca foram enviados.
[]s

**Comment by jamilatta** [comment]
Os logos foram solicitados para a equipe interna, estou no aguardo.

**Comment by fabiobatalha** [comment]
Considerando que isso depende de tarefas a serem realizadas por nossa equipe, recomendo deixar este ticket para uma iteração futura.

**Comment by jamilatta** [comment]
![logo-scielo-signature](https://cloud.githubusercontent.com/assets/373745/7758114/7e54643c-ffdd-11e4-9618-80ea08558a51.png)
![logo-scielo](https://cloud.githubusercontent.com/assets/373745/7758113/7e543926-ffdd-11e4-9032-9ea9d2a0bd99.png)
![logo-scielo-org](https://cloud.githubusercontent.com/assets/373745/7758115/7e572500-ffdd-11e4-8f32-41a985a69b03.png)

**Comment by alexxxmendonca** [comment]
Testado e aprovado em http://homolog.search.scielo.org/
