### ISSUE TITLE
Remover javascript desnecessários inseridos na primeiro PR.

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/search-journals#99]
O designer havia comentado que criou os javascript com a intenção que tivéssemos um CDN. Como consequência temos um arquivo main.js que tem código desnecessários para esta aplicação, conforme havia conversado com o consultor não **iremos inserir código inúteis**, dessa forma esses códigos em javascript devem ser removido.

Exemplificando e pegando como exemplo o arquivo main.js este arquivo tem: 1195 linha, estamos agora incorporando todas essas linhas, mas precisamos efetivamente de 546 linhas, sendo que por hora 649 linhas não são utilizadas.

**Comment by deandr** [comment]
@jamilatta,

Pela descrição do issue e baseado em sua conversa com o designer você tem uma melhor noção de quais são as linhas realmente necessárias do protótipo. Poderia indicar qual são estas 546 linhas que devo manter no arquivo main.js, pois realmente não tenho claro quais seriam.

Obrigado.

**Comment by jamilatta** [comment]
As linhas entre 2 até 235 do arquivo **main.js** devem ser removida, todo esse código não faz sentido pois é código para o portal e 783 até 1196 do mesmo arquivo são códigos para o artigo, portanto também deve ser removido. 

Não realizei testes para garantir que esse código é essencial, mas caso seus **testes** indiquem isso peço para reportar nesse ticket para que eu possa verificar com o Designer.

**Comment by deandr** [comment]
Infelizmente existe dependência entre as partes do JS referentes ao Portal e talvez do Article. Ao remover as linhas citadas são apresentados no console do browser erros no JS e a função de compartilhar nas redes sociais para de funcionar. 

Recomendo mover este ticket para o backlog e entrar em contato com o designer solicitando o isolamento do código referente a pesquisa.

[]s

**Comment by fabiobatalha** [comment]
Movido para o backlog.
